In [1]:
import sys
import importlib
import warnings
import random
from collections import defaultdict
import pickle
import os
import re

import torch
from tqdm import tqdm
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns


sys.path.append("A:/Masters/Thesis/Dr. Mohsen Rashwan/projects/")

from stt_benchmarking.utils import helpers, metrics as mt, validate
from stt_benchmarking.etl import load_english_data

warnings.filterwarnings('ignore')
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
pd.set_option("display.max_colwidth", None)
random.seed(42)

print(device)

The torchaudio backend is switched to 'soundfile'. Note that 'sox_io' is not supported on Windows.
The torchaudio backend is switched to 'soundfile'. Note that 'sox_io' is not supported on Windows.

cuda

In [ ]:
data_path = "../../data/librispeech/LibriSpeech/test-clean"
records = load_english_data.load_librispeech(data_path)

In [2]:
def save_bootstrap_samples(samples, filepath="../../reports/phase_1_4/lists_info/librespeech/bootstrap_samples.pkl"):
    os.makedirs(os.path.dirname(filepath), exist_ok=True)
    with open(filepath, 'wb') as f:
        pickle.dump(samples, f)

def load_bootstrap_samples(filepath="../../reports/phase_1_4/lists_info/librespeech/bootstrap_samples.pkl"):
    with open(filepath, 'rb') as f:
        return pickle.load(f)

In [4]:
save_bootstrap_samples(records, filepath="../../reports/phase_1_4/lists_info/librespeech/records.pkl")

In [3]:
records = load_bootstrap_samples("../../results/librespeech/audios/records.pkl")
len(records)

2620

In [4]:
filtered_records = [record for record in records if record["audio_duration"] <= 30]
len(filtered_records)

2611

In [5]:
records_bigger_30 = [record for record in records if record["audio_duration"] > 30]
len(records_bigger_30)

9

# Models

In [6]:
import json
import inspect
import os

def save_model_info(obj, attr_name="samples_info", save_dir="../../reports/phase_1_4/models_info/librespeech", is_llm=False, level=0):
    """
    Save the model's info dictionary to a JSON file.
    
    Parameters
    ----------
    obj : object
        Class object containing the info dictionary (e.g., seamless_m4t).
    attr_name : str, optional
        The attribute name holding the dictionary (default: "samples_info").
    save_dir : str, optional
        Path to directory where file will be saved.
    """
    # Ensure save directory exists
    os.makedirs(save_dir, exist_ok=True)

    # Get class object name
    obj_name = [name for name, val in inspect.currentframe().f_back.f_locals.items() if val is obj]
    obj_name = obj_name[0] if obj_name else obj.__class__.__name__

    # Extract info
    if not hasattr(obj, attr_name):
        raise AttributeError(f"Object has no attribute '{attr_name}'")
    
    info_dict = getattr(obj, attr_name)

    # Save as JSON
    if is_llm:
        save_path = os.path.join(save_dir, f"{obj_name}_llm_{level}.json")
    else:
        save_path = os.path.join(save_dir, f"{obj_name}_{level}.json")
    with open(save_path, "w", encoding="utf-8") as f:
        json.dump(info_dict, f, ensure_ascii=False, indent=2)

def save_list_info(list_obj, filename, save_dir="../../reports/phase_1_4/lists_info/librespeech", is_llm=False):
    """
    Save a list of dictionaries to a JSON file.

    Parameters
    ----------
    list_obj : list[dict]
        The list of dictionaries to save.
    filename : str
        Base name for the saved file (without extension).
    save_dir : str, optional
        Directory where the file will be saved.
    """
    os.makedirs(save_dir, exist_ok=True)

    if is_llm:
        save_path = os.path.join(save_dir, f"{filename}_llm_.json")
    else:
        save_path = os.path.join(save_dir, f"{filename}.json")

    with open(save_path, "w", encoding="utf-8") as f:
        json.dump(list_obj, f, ensure_ascii=False, indent=2)

## Cohere

In [5]:
from stt_benchmarking.models.speech_to_text.english import cohere_english
importlib.reload(cohere_english)

cohere = cohere_english.CohereEnglishInference(device=device)
cohere.run_inference_one_by_one(records)
save_list_info(cohere.samples_info, "cohere_samples")
cohere.overall_metrics

Loading weights: 100%|██████████| 2150/2150 [00:04<00:00, 491.72it/s]
2026-07-14 01:53:17 - [stt_benchmarking.models.speech_to_text.english._load_model:43] INFO - Loaded Cohere Transcribe (03-2026)
Processing Records: 100%|██████████| 2620/2620 [11:06<00:00,  3.93it/s]
2026-07-14 02:04:23 - [stt_benchmarking.utils.decorators.execution_time_wrapper:22] INFO - Execution time for function run_inference_one_by_one: 11 minutes 6 seconds

{'word_error_rate': {'wer (%)': 1.26,
  'word_similarity_ratio (%)': 99.37,
  'word_edit_distance': 668,
  'substitutions': 508,
  'deletions': 75,
  'insertions': 85,
  'hits': 52444,
  'ref_length': 53027,
  'hyp_length': 53037},
 'character_error_rate': {'cer (%)': 0.38,
  'char_similarity_ratio (%)': 99.81,
  'char_edit_distance': 1071,
  'substitutions': 365,
  'deletions': 347,
  'insertions': 359,
  'hits': 279979,
  'ref_length': 280691,
  'hyp_length': 280703}}

## SpeechBrain

In [5]:
from stt_benchmarking.models.speech_to_text.english import speechbrain
importlib.reload(speechbrain)

sb_object = speechbrain.SpeechBrainInference(device=device)

sb_object.run_inference_one_by_one(records)
save_list_info(sb_object.samples_info, "sb_samples")
sb_object.overall_metrics

Unexpected exception formatting exception. Falling back to standard exception

Traceback (most recent call last):
  File "c:\Users\school.RABAH-DESKTOP\.conda\envs\pytorch_gpu\lib\site-packages\speechbrain\integrations\k2_fsa\__init__.py", line 12, in <module>
    import k2  # noqa
ModuleNotFoundError: No module named 'k2'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\school.RABAH-DESKTOP\.conda\envs\pytorch_gpu\lib\site-packages\speechbrain\utils\importutils.py", line 97, in ensure_module
    self.lazy_module = importlib.import_module(self.target)
  File "c:\Users\school.RABAH-DESKTOP\.conda\envs\pytorch_gpu\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "c:\Users\school.RABAH-DESKTOP\.conda\envs\pytorch_gpu\lib\site-packages\speechbrain\integrations\k2_fsa\__init__.py", line 16, in <module>
    raise ImportError(MSG) from e
ImportError: Please install k2 to use k2
Checkout: https://k2-fsa.github.io/k2/installation/from_wheels.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\school.RABAH-DESKTOP\.conda\envs\pytorch_gpu\lib\site-packages\IPython\core\interactiveshell.py", line 3579, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "C:\Users\school.RABAH-DESKTOP\AppData\Local\Temp\ipykernel_4480\3017359199.py", line 4, in <module>
    sb_object = speechbrain.SpeechBrainInference(device=device)
  File "A:\Masters/Thesis/Dr. Mohsen Rashwan/projects\stt_benchmarking\models\speech_to_text\english\speechbrain.py", line 27, in __init__
    self.model = self._load_model()
  File "A:\Masters/Thesis/Dr. Mohsen Rashwan/projects\stt_benchmarking\models\speech_to_text\english\speechbrain.py", line 42, in _load_model
    model = EncoderDecoderASR.from_hparams(
  File "c:\Users\school.RABAH-DESKTOP\.conda\envs\pytorch_gpu\lib\site-packages\speechbrain\inference\interfaces.py", line 487, in from_hparams
    return pretrained_from_hparams(
  File "c:\Users\school.RABAH-DESKTOP\.conda\envs\pytorch_gpu\lib\site-packages\speechbrain\inference\interfaces.py", line 194, in pretrained_from_hparams
    hparams = load_hyperpyyaml(fin, overrides, overrides_must_match)
  File "c:\Users\school.RABAH-DESKTOP\.conda\envs\pytorch_gpu\lib\site-packages\hyperpyyaml\core.py", line 189, in load_hyperpyyaml
    hparams = yaml.load(yaml_stream, Loader=loader)
  File "c:\Users\school.RABAH-DESKTOP\.conda\envs\pytorch_gpu\lib\site-packages\yaml\__init__.py", line 81, in load
    return loader.get_single_data()
  File "c:\Users\school.RABAH-DESKTOP\.conda\envs\pytorch_gpu\lib\site-packages\ruamel\yaml\constructor.py", line 119, in get_single_data
    return self.construct_document(node)
  File "c:\Users\school.RABAH-DESKTOP\.conda\envs\pytorch_gpu\lib\site-packages\ruamel\yaml\constructor.py", line 123, in construct_document
    data = self.construct_object(node)
  File "c:\Users\school.RABAH-DESKTOP\.conda\envs\pytorch_gpu\lib\site-packages\ruamel\yaml\constructor.py", line 150, in construct_object
    data = self.construct_non_recursive_object(node)
  File "c:\Users\school.RABAH-DESKTOP\.conda\envs\pytorch_gpu\lib\site-packages\ruamel\yaml\constructor.py", line 191, in construct_non_recursive_object
    for _dummy in generator:
  File "c:\Users\school.RABAH-DESKTOP\.conda\envs\pytorch_gpu\lib\site-packages\ruamel\yaml\constructor.py", line 629, in construct_yaml_map
    value = self.construct_mapping(node)
  File "c:\Users\school.RABAH-DESKTOP\.conda\envs\pytorch_gpu\lib\site-packages\ruamel\yaml\constructor.py", line 425, in construct_mapping
    return BaseConstructor.construct_mapping(self, node, deep=deep)
  File "c:\Users\school.RABAH-DESKTOP\.conda\envs\pytorch_gpu\lib\site-packages\ruamel\yaml\constructor.py", line 247, in construct_mapping
    value = self.construct_object(value_node, deep=deep)
  File "c:\Users\school.RABAH-DESKTOP\.conda\envs\pytorch_gpu\lib\site-packages\ruamel\yaml\constructor.py", line 150, in construct_object
    data = self.construct_non_recursive_object(node)
  File "c:\Users\school.RABAH-DESKTOP\.conda\envs\pytorch_gpu\lib\site-packages\ruamel\yaml\constructor.py", line 186, in construct_non_recursive_object
    data = constructor(self, tag_suffix, node)
  File "c:\Users\school.RABAH-DESKTOP\.conda\envs\pytorch_gpu\lib\site-packages\hyperpyyaml\core.py", line 482, in _construct_object
    return callable_(*args, **kwargs)
  File "c:\Users\school.RABAH-DESKTOP\.conda\envs\pytorch_gpu\lib\site-packages\speechbrain\lobes\models\transformer\TransformerASR.py", line 320, in __init__
    NormalizedEmbedding(d_model, tgt_vocab)
  File "c:\Users\school.RABAH-DESKTOP\.conda\envs\pytorch_gpu\lib\site-packages\speechbrain\lobes\models\transformer\Transformer.py", line 988, in __init__
    self.emb = sb.nnet.embedding.Embedding(
  File "c:\Users\school.RABAH-DESKTOP\.conda\envs\pytorch_gpu\lib\site-packages\speechbrain\utils\importutils.py", line 112, in __getattr__
    return getattr(self.ensure_module(1), attr)
  File "c:\Users\school.RABAH-DESKTOP\.conda\envs\pytorch_gpu\lib\site-packages\speechbrain\utils\importutils.py", line 80, in ensure_module
    importer_frame = inspect.getframeinfo(sys._getframe(stacklevel + 1))
  File "c:\Users\school.RABAH-DESKTOP\.conda\envs\pytorch_gpu\lib\inspect.py", line 1624, in getframeinfo
    lines, lnum = findsource(frame)
  File "c:\Users\school.RABAH-DESKTOP\.conda\envs\pytorch_gpu\lib\inspect.py", line 952, in findsource
    module = getmodule(object, file)
  File "c:\Users\school.RABAH-DESKTOP\.conda\envs\pytorch_gpu\lib\inspect.py", line 869, in getmodule
    if ismodule(module) and hasattr(module, '__file__'):
  File "c:\Users\school.RABAH-DESKTOP\.conda\envs\pytorch_gpu\lib\site-packages\speechbrain\utils\importutils.py", line 112, in __getattr__
    return getattr(self.ensure_module(1), attr)
  File "c:\Users\school.RABAH-DESKTOP\.conda\envs\pytorch_gpu\lib\site-packages\speechbrain\utils\importutils.py", line 172, in ensure_module
    module = super().ensure_module(stacklevel + 1)
  File "c:\Users\school.RABAH-DESKTOP\.conda\envs\pytorch_gpu\lib\site-packages\speechbrain\utils\importutils.py", line 103, in ensure_module
    raise ImportError(f"Lazy import of {repr(self)} failed") from e
ImportError: Lazy import of LazyModule(package=None, target=speechbrain.integrations.k2_fsa, loaded=False) failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\school.RABAH-DESKTOP\.conda\envs\pytorch_gpu\lib\site-packages\speechbrain\integrations\k2_fsa\__init__.py", line 12, in <module>
    import k2  # noqa
ModuleNotFoundError: No module named 'k2'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\school.RABAH-DESKTOP\.conda\envs\pytorch_gpu\lib\site-packages\speechbrain\utils\importutils.py", line 97, in ensure_module
    self.lazy_module = importlib.import_module(self.target)
  File "c:\Users\school.RABAH-DESKTOP\.conda\envs\pytorch_gpu\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "c:\Users\school.RABAH-DESKTOP\.conda\envs\pytorch_gpu\lib\site-packages\speechbrain\integrations\k2_fsa\__init__.py", line 16, in <module>
    raise ImportError(MSG) from e
ImportError: Please install k2 to use k2
Checkout: https://k2-fsa.github.io/k2/installation/from_wheels.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\school.RABAH-DESKTOP\.conda\envs\pytorch_gpu\lib\site-packages\IPython\core\interactiveshell.py", line 2170, in showtraceback
    stb = self.InteractiveTB.structured_traceback(
  File "c:\Users\school.RABAH-DESKTOP\.conda\envs\pytorch_gpu\lib\site-packages\IPython\core\ultratb.py", line 1457, in structured_traceback
    return FormattedTB.structured_traceback(
  File "c:\Users\school.RABAH-DESKTOP\.conda\envs\pytorch_gpu\lib\site-packages\IPython\core\ultratb.py", line 1348, in structured_traceback
    return VerboseTB.structured_traceback(
  File "c:\Users\school.RABAH-DESKTOP\.conda\envs\pytorch_gpu\lib\site-packages\IPython\core\ultratb.py", line 1195, in structured_traceback
    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,
  File "c:\Users\school.RABAH-DESKTOP\.conda\envs\pytorch_gpu\lib\site-packages\IPython\core\ultratb.py", line 1085, in format_exception_as_a_whole
    self.get_records(etb, number_of_lines_of_context, tb_offset) if etb else []
  File "c:\Users\school.RABAH-DESKTOP\.conda\envs\pytorch_gpu\lib\site-packages\IPython\core\ultratb.py", line 1153, in get_records
    mod = inspect.getmodule(cf.tb_frame)
  File "c:\Users\school.RABAH-DESKTOP\.conda\envs\pytorch_gpu\lib\inspect.py", line 861, in getmodule
    file = getabsfile(object, _filename)
  File "c:\Users\school.RABAH-DESKTOP\.conda\envs\pytorch_gpu\lib\inspect.py", line 844, in getabsfile
    _filename = getsourcefile(object) or getfile(object)
  File "c:\Users\school.RABAH-DESKTOP\.conda\envs\pytorch_gpu\lib\inspect.py", line 829, in getsourcefile
    module = getmodule(object, filename)
  File "c:\Users\school.RABAH-DESKTOP\.conda\envs\pytorch_gpu\lib\inspect.py", line 869, in getmodule
    if ismodule(module) and hasattr(module, '__file__'):
  File "c:\Users\school.RABAH-DESKTOP\.conda\envs\pytorch_gpu\lib\site-packages\speechbrain\utils\importutils.py", line 112, in __getattr__
    return getattr(self.ensure_module(1), attr)
  File "c:\Users\school.RABAH-DESKTOP\.conda\envs\pytorch_gpu\lib\site-packages\speechbrain\utils\importutils.py", line 172, in ensure_module
    module = super().ensure_module(stacklevel + 1)
  File "c:\Users\school.RABAH-DESKTOP\.conda\envs\pytorch_gpu\lib\site-packages\speechbrain\utils\importutils.py", line 103, in ensure_module
    raise ImportError(f"Lazy import of {repr(self)} failed") from e
ImportError: Lazy import of LazyModule(package=None, target=speechbrain.integrations.k2_fsa, loaded=False) failed

## Whisper

In [5]:
from stt_benchmarking.models.speech_to_text.english import whisper
importlib.reload(whisper)

whisper_v3 = whisper.FasterWhisperInference(device=device, model_version="v3", batch_size=8)
whisper_v3.run_inference_one_by_one(records)
save_list_info(whisper_v3.samples_info, "whisper_v3_samples")
whisper_v3.overall_metrics

2026-07-14 02:40:54 - [stt_benchmarking.models.speech_to_text.english._load_model:50] INFO - Loaded FasterWhisper V3 Model
2026-07-14 02:40:54 - [stt_benchmarking.models.speech_to_text.english._load_pipeline:61] INFO - Loaded Whisper V3 Pipeline
Processing Records: 100%|██████████| 2620/2620 [39:41<00:00,  1.10it/s]
2026-07-14 03:20:36 - [stt_benchmarking.utils.decorators.execution_time_wrapper:22] INFO - Execution time for function run_inference_one_by_one: 39 minutes 41 seconds

{'word_error_rate': {'wer (%)': 2.63,
  'word_similarity_ratio (%)': 98.69,
  'word_edit_distance': 1393,
  'substitutions': 697,
  'deletions': 131,
  'insertions': 565,
  'hits': 52199,
  'ref_length': 53027,
  'hyp_length': 53461},
 'character_error_rate': {'cer (%)': 1.36,
  'char_similarity_ratio (%)': 99.32,
  'char_edit_distance': 3825,
  'substitutions': 535,
  'deletions': 595,
  'insertions': 2695,
  'hits': 279561,
  'ref_length': 280691,
  'hyp_length': 282791}}

## Nvidia

In [5]:
# from stt_benchmarking.models.speech_to_text.english import nvidia
# importlib.reload(nvidia)

# CANARY_OBJ = nvidia.NvidiaInference(device=device, model_id="canary")
# CANARY_OBJ.run_inference_one_by_one(records)
# save_list_info(CANARY_OBJ.samples_info, "canary_samples")
# CANARY_OBJ.overall_metrics
# CANARY_OBJ.reset()

[NeMo I 2026-07-14 05:29:41 mixins:181] Tokenizer CanaryBPETokenizer initialized with 16384 tokens

[NeMo W 2026-07-14 05:29:41 modelPT:180] If you intend to do training or fine-tuning, please call the ModelPT.setup_training_data() method and provide a valid configuration file to setup the train data loader.
    Train config :
    use_lhotse: true
    skip_missing_manifest_entries: true
    input_cfg: null
    tarred_audio_filepaths: null
    manifest_filepath: null
    sample_rate: 16000
    shuffle: true
    num_workers: 4
    pin_memory: true
    prompt_format: canary2
    max_duration: 40.0
    min_duration: 0.01
    text_field: answer
    lang_field: target_lang
    use_bucketing: true
    max_tps: null
    bucket_duration_bins: null
    bucket_batch_size: null
    num_buckets: null
    bucket_buffer_size: 20000
    shuffle_buffer_size: 10000

[NeMo W 2026-07-14 05:29:41 modelPT:187] If you intend to do validation, please call the ModelPT.setup_validation_data() or ModelPT.setup_multiple_validation_data() method and provide a valid configuration file to setup the validation data loader(s).
    Validation config :
    use_lhotse: true
    prompt_format: canary2
    manifest_filepath: null
    sample_rate: 16000
    batch_size: 4
    shuffle: true
    max_duration: 40.0
    min_duration: 0.1
    num_workers: 2
    pin_memory: true
    text_field: answer
    lang_field: target_lang

[NeMo I 2026-07-14 05:29:41 features:305] PADDING: 0
[NeMo I 2026-07-14 05:29:47 save_restore_connector:275] Model EncDecMultiTaskModel was successfully restored from C:\Users\school.RABAH-DESKTOP\.cache\huggingface\hub\models--nvidia--canary-1b-v2\snapshots\87bc52657add533cd0156b3fc1aef027280754bf\canary-1b-v2.nemo.

2026-07-14 05:29:47 - [stt_benchmarking.models.speech_to_text.english._load_model:53] INFO - Loaded model nvidia canary
Processing Records:   0%|          | 0/2620 [00:00<?, ?it/s][NeMo W 2026-07-14 05:29:47 dataloader:732] The following configuration keys are ignored by Lhotse dataloader: trim_silence
[NeMo W 2026-07-14 05:29:47 dataloader:479] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)
Processing Records:   0%|          | 1/2620 [00:00<35:12,  1.24it/s][NeMo W 2026-07-14 05:29:47 dataloader:732] The following configuration keys are ignored by Lhotse dataloader: trim_silence
[NeMo W 2026-07-14 05:29:47 dataloader:479] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)
Processing Records:   0%|          | 2/2620 [00:00<18:47,  2.32it/s][NeMo W 2026-07-14 05:29:48 dataloader:732] The following configuration keys are ignored by Lhotse dataloader: trim_silence
[NeMo W 2026-07-14 05:29:48 dataloader:479] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)
Processing Records:   0%|          | 3/2620 [00:01<14:55,  2.92it/s][NeMo W 2026-07-14 05:29:48 dataloader:732] The following configuration keys are ignored by Lhotse dataloader: trim_silence
[NeMo W 2026-07-14 05:29:48 dataloader:479] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)
Processing Records:   0%|          | 4/2620 [00:01<11:40,  3.73it/s][NeMo W 2026-07-14 05:29:48 dataloader:732] The following configuration keys are ignored by Lhotse dataloader: trim_silence
[NeMo W 2026-07-14 05:29:48 dataloader:479] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)
Processing Records:   0%|          | 5/2620 [00:01<10:36,  4.11it/s][NeMo W 2026-07-14 05:29:48 dataloader:732] The following configuration keys are ignored by Lhotse dataloader: trim_silence
[NeMo W 2026-07-14 05:29:48 dataloader:479] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)
Processing Records:   0%|          | 6/2620 [00:01<11:57,  3.64it/s][NeMo W 2026-07-14 05:29:49 dataloader:732] The following configuration keys are ignored by Lhotse dataloader: trim_silence
[NeMo W 2026-07-14 05:29:49 dataloader:479] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)
Processing Records:   0%|          | 7/2620 [00:02<12:54,  3.37it/s][NeMo W 2026-07-14 05:29:49 dataloader:732] The following configuration keys are ignored by Lhotse dataloader: trim_silence
[NeMo W 2026-07-14 05:29:49 dataloader:479] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)
Processing Records:   0%|          | 8/2620 [00:02<11:06,  3.92it/s][NeMo W 2026-07-14 05:29:49 dataloader:732] The following configuration keys are ignored by Lhotse dataloader: trim_silence
[NeMo W 2026-07-14 05:29:49 dataloader:479] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)
Processing Records:   0%|          | 9/2620 [00:02<10:44,  4.05it/s][NeMo W 2026-07-14 05:29:49 dataloader:732] The following configuration keys are ignored by Lhotse dataloader: trim_silence
[NeMo W 2026-07-14 05:29:49 dataloader:479] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)
Processing Records:   0%|          | 10/2620 [00:02<11:52,  3.66it/s][NeMo W 2026-07-14 05:29:50 dataloader:732] The following configuration keys are ignored by Lhotse dataloader: trim_silence
[NeMo W 2026-07-14 05:29:50 dataloader:479] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)
Processing Records:   0%|          | 11/2620 [00:03<10:55,  3.98it/s][NeMo W 2026-07-14 05:29:50 dataloader:732] The following configuration keys are ignored by Lhotse dataloader: trim_silence
[NeMo W 2026-07-14 05:29:50 dataloader:479] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)
Processing Records:   0%|          | 12/2620 [00:03<12:55,  3.36it/s][NeMo W 2026-07-14 05:29:50 dataloader:732] The following configuration keys are ignored by Lhotse dataloader: trim_silence
[NeMo W 2026-07-14 05:29:50 dataloader:479] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)
Processing Records:   0%|          | 13/2620 [00:03<13:54,  3.12it/s][NeMo W 2026-07-14 05:29:51 dataloader:732] The following configuration keys are ignored by Lhotse dataloader: trim_silence
[NeMo W 2026-07-14 05:29:51 dataloader:479] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)
Processing Records:   1%|          | 14/2620 [00:04<12:55,  3.36it/s][NeMo W 2026-07-14 05:29:51 dataloader:732] The following configuration keys are ignored by Lhotse dataloader: trim_silence
[NeMo W 2026-07-14 05:29:51 dataloader:479] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)
Processing Records:   1%|          | 15/2620 [00:04<10:35,  4.10it/s][NeMo W 2026-07-14 05:29:51 dataloader:732] The following configuration keys are ignored by Lhotse dataloader: trim_silence
[NeMo W 2026-07-14 05:29:51 dataloader:479] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)
Processing Records:   1%|          | 16/2620 [00:04<11:01,  3.94it/s][NeMo W 2026-07-14 05:29:51 dataloader:732] The following configuration keys are ignored by Lhotse dataloader: trim_silence
[NeMo W 2026-07-14 05:29:51 dataloader:479] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)
Processing Records:   1%|          | 17/2620 [00:04<10:10,  4.26it/s][NeMo W 2026-07-14 05:29:51 dataloader:732] The following configuration keys are ignored by Lhotse dataloader: trim_silence
[NeMo W 2026-07-14 05:29:51 dataloader:479] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)
Processing Records:   1%|          | 18/2620 [00:05<11:35,  3.74it/s][NeMo W 2026-07-14 05:29:52 dataloader:732] The following configuration keys are ignored by Lhotse dataloader: trim_silence
[NeMo W 2026-07-14 05:29:52 dataloader:479] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)
Processing Records:   1%|          | 19/2620 [00:05<14:18,  3.03it/s][NeMo W 2026-07-14 05:29:52 dataloader:732] The following configuration keys are ignored by Lhotse dataloader: trim_silence
[NeMo W 2026-07-14 05:29:52 dataloader:479] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)
Processing Records:   1%|          | 20/2620 [00:05<15:07,  2.86it/s][NeMo W 2026-07-14 05:29:53 dataloader:732] The following configuration keys are ignored by Lhotse dataloader: trim_silence
[NeMo W 2026-07-14 05:29:53 dataloader:479] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)
Processing Records:   1%|          | 21/2620 [00:06<16:37,  2.61it/s][NeMo W 2026-07-14 05:29:53 dataloader:732] The following configuration keys are ignored by Lhotse dataloader: trim_silence
[NeMo W 2026-07-14 05:29:53 dataloader:479] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)
Processing Records:   1%|          | 22/2620 [00:06<14:34,  2.97it/s][NeMo W 2026-07-14 05:29:53 dataloader:732] The following configuration keys are ignored by Lhotse dataloader: trim_silence
[NeMo W 2026-07-14 05:29:53 dataloader:479] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)
Processing Records:   1%|          | 23/2620 [00:07<14:52,  2.91it/s][NeMo W 2026-07-14 05:29:54 dataloader:732] The following configuration keys are ignored by Lhotse dataloader: trim_silence
[NeMo W 2026-07-14 05:29:54 dataloader:479] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)
Processing Records:   1%|          | 24/2620 [00:07<15:19,  2.82it/s][NeMo W 2026-07-14 05:29:54 dataloader:732] The following configuration keys are ignored by Lhotse dataloader: trim_silence
[NeMo W 2026-07-14 05:29:54 dataloader:479] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)
Processing Records:   1%|          | 25/2620 [00:07<15:29,  2.79it/s][NeMo W 2026-07-14 05:29:54 dataloader:732] The following configuration keys are ignored by Lhotse dataloader: trim_silence
[NeMo W 2026-07-14 05:29:54 dataloader:479] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)
Processing Records:   1%|          | 26/2620 [00:08<14:41,  2.94it/s][NeMo W 2026-07-14 05:29:55 dataloader:732] The following configuration keys are ignored by Lhotse dataloader: trim_silence
[NeMo W 2026-07-14 05:29:55 dataloader:479] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)
Processing Records:   1%|          | 27/2620 [00:08<13:18,  3.25it/s][NeMo W 2026-07-14 05:29:55 dataloader:732] The following configuration keys are ignored by Lhotse dataloader: trim_silence
[NeMo W 2026-07-14 05:29:55 dataloader:479] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)
Processing Records:   1%|          | 28/2620 [00:08<11:16,  3.83it/s][NeMo W 2026-07-14 05:29:55 dataloader:732] The following configuration keys are ignored by Lhotse dataloader: trim_silence
[NeMo W 2026-07-14 05:29:55 dataloader:479] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)
Processing Records:   1%|          | 29/2620 [00:08<11:20,  3.81it/s][NeMo W 2026-07-14 05:29:55 dataloader:732] The following configuration keys are ignored by Lhotse dataloader: trim_silence
[NeMo W 2026-07-14 05:29:55 dataloader:479] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)
Processing Records:   1%|          | 30/2620 [00:08<10:23,  4.15it/s][NeMo W 2026-07-14 05:29:56 dataloader:732] The following configuration keys are ignored by Lhotse dataloader: trim_silence
[NeMo W 2026-07-14 05:29:56 dataloader:479] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)
Processing Records:   1%|          | 31/2620 [00:09<08:48,  4.90it/s][NeMo W 2026-07-14 05:29:56 dataloader:732] The following configuration keys are ignored by Lhotse dataloader: trim_silence

In [ ]:
# from stt_benchmarking.models.speech_to_text.english import nvidia
# importlib.reload(nvidia)

# CONFORMER_OBJ = nvidia.NvidiaInference(device=device, model_id="conformer")
# CONFORMER_OBJ.run_inference_one_by_one(records)
# save_list_info(CONFORMER_OBJ.samples_info, "conformer_samples")
# CONFORMER_OBJ.overall_metrics

[NeMo I 2026-07-13 19:44:05 mixins:181] Tokenizer SentencePieceTokenizer initialized with 128 tokens

[NeMo W 2026-07-13 19:44:05 modelPT:180] If you intend to do training or fine-tuning, please call the ModelPT.setup_training_data() method and provide a valid configuration file to setup the train data loader.
    Train config :
    manifest_filepath: /data/NeMo_ASR_SET/English/v2.0/train/tarred_audio_manifest.json
    sample_rate: 16000
    batch_size: 32
    shuffle: true
    num_workers: 8
    pin_memory: true
    use_start_end_token: false
    trim_silence: false
    max_duration: 20.0
    min_duration: 0.1
    shuffle_n: 2048
    is_tarred: true
    tarred_audio_filepaths: /data/NeMo_ASR_SET/English/v2.0/train/audio__OP_0..4095_CL_.tar

[NeMo W 2026-07-13 19:44:05 modelPT:187] If you intend to do validation, please call the ModelPT.setup_validation_data() or ModelPT.setup_multiple_validation_data() method and provide a valid configuration file to setup the validation data loader(s).
    Validation config :
    manifest_filepath:
    - /data/ASR/LibriSpeech/librispeech_withsp2/manifests/librivox-dev-other.json
    - /data/ASR/LibriSpeech/librispeech_withsp2/manifests/librivox-dev-clean.json
    - /data/ASR/LibriSpeech/librispeech_withsp2/manifests/librivox-test-other.json
    - /data/ASR/LibriSpeech/librispeech_withsp2/manifests/librivox-test-clean.json
    sample_rate: 16000
    batch_size: 16
    shuffle: false
    num_workers: 8
    pin_memory: true
    use_start_end_token: false
    is_tarred: false
    tarred_audio_filepaths: na

[NeMo W 2026-07-13 19:44:05 modelPT:194] Please call the ModelPT.setup_test_data() or ModelPT.setup_multiple_test_data() method and provide a valid configuration file to setup the test data loader(s).
    Test config :
    manifest_filepath:
    - /data/ASR/LibriSpeech/librispeech_withsp2/manifests/librivox-test-other.json
    - /data/ASR/LibriSpeech/librispeech_withsp2/manifests/librivox-dev-clean.json
    - /data/ASR/LibriSpeech/librispeech_withsp2/manifests/librivox-dev-other.json
    - /data/ASR/LibriSpeech/librispeech_withsp2/manifests/librivox-test-clean.json
    sample_rate: 16000
    batch_size: 16
    shuffle: false
    num_workers: 8
    pin_memory: true
    use_start_end_token: false
    is_tarred: false
    tarred_audio_filepaths: na

[NeMo I 2026-07-13 19:44:05 features:305] PADDING: 0
[NeMo I 2026-07-13 19:44:06 save_restore_connector:275] Model EncDecCTCModelBPE was successfully restored from C:\Users\school.RABAH-DESKTOP\.cache\huggingface\hub\models--nvidia--stt_en_conformer_ctc_large\snapshots\5f18b90411b9fdfc9b52b8caf636f204491afb01\stt_en_conformer_ctc_large.nemo.

2026-07-13 19:44:06 - [stt_benchmarking.models.speech_to_text.english._load_model:50] INFO - Loaded model nvidia conformer
Processing Records: 100%|██████████| 2620/2620 [02:13<00:00, 19.62it/s]
2026-07-13 19:46:20 - [stt_benchmarking.utils.decorators.execution_time_wrapper:22] INFO - Execution time for function run_inference_one_by_one: 2 minutes 14 seconds

NameError: name 'save_list_info' is not defined

In [6]:
from stt_benchmarking.models.speech_to_text.english import nvidia
importlib.reload(nvidia)

PARAKEET_OBJ = nvidia.NvidiaInference(device=device, model_id="parakeet")
PARAKEET_OBJ.run_inference_one_by_one(records)
save_list_info(PARAKEET_OBJ.samples_info, "parakeet_samples")
PARAKEET_OBJ.overall_metrics
PARAKEET_OBJ.reset()

[NeMo I 2026-07-14 05:42:54 mixins:181] Tokenizer SentencePieceTokenizer initialized with 1024 tokens

[NeMo W 2026-07-14 05:42:54 modelPT:180] If you intend to do training or fine-tuning, please call the ModelPT.setup_training_data() method and provide a valid configuration file to setup the train data loader.
    Train config :
    use_lhotse: true
    skip_missing_manifest_entries: true
    input_cfg: null
    tarred_audio_filepaths: null
    manifest_filepath: null
    sample_rate: 16000
    shuffle: true
    num_workers: 2
    pin_memory: true
    max_duration: 40.0
    min_duration: 0.1
    text_field: answer
    batch_duration: null
    use_bucketing: true
    bucket_duration_bins: null
    bucket_batch_size: null
    num_buckets: 30
    bucket_buffer_size: 20000
    shuffle_buffer_size: 10000

[NeMo W 2026-07-14 05:42:54 modelPT:187] If you intend to do validation, please call the ModelPT.setup_validation_data() or ModelPT.setup_multiple_validation_data() method and provide a valid configuration file to setup the validation data loader(s).
    Validation config :
    use_lhotse: true
    manifest_filepath: null
    sample_rate: 16000
    batch_size: 16
    shuffle: false
    max_duration: 40.0
    min_duration: 0.1
    num_workers: 2
    pin_memory: true
    text_field: answer

[NeMo I 2026-07-14 05:42:54 features:305] PADDING: 0
[NeMo I 2026-07-14 05:42:56 rnnt_models:226] Using RNNT Loss : tdt
    Loss tdt_kwargs: {'fastemit_lambda': 0.0, 'clamp': -1.0, 'durations': [0, 1, 2, 3, 4], 'sigma': 0.02, 'omega': 0.1}
[NeMo I 2026-07-14 05:42:56 rnnt_models:226] Using RNNT Loss : tdt
    Loss tdt_kwargs: {'fastemit_lambda': 0.0, 'clamp': -1.0, 'durations': [0, 1, 2, 3, 4], 'sigma': 0.02, 'omega': 0.1}
[NeMo I 2026-07-14 05:42:56 rnnt_models:226] Using RNNT Loss : tdt
    Loss tdt_kwargs: {'fastemit_lambda': 0.0, 'clamp': -1.0, 'durations': [0, 1, 2, 3, 4], 'sigma': 0.02, 'omega': 0.1}
[NeMo I 2026-07-14 05:42:58 save_restore_connector:275] Model EncDecRNNTBPEModel was successfully restored from C:\Users\school.RABAH-DESKTOP\.cache\huggingface\hub\models--nvidia--parakeet-tdt-0.6b-v2\snapshots\ae9ad07059c7c739ffaf932226a8fe64ae2620b0\parakeet-tdt-0.6b-v2.nemo.

2026-07-14 05:42:58 - [stt_benchmarking.models.speech_to_text.english._load_model:53] INFO - Loaded model nvidia parakeet
Processing Records: 100%|██████████| 2620/2620 [02:17<00:00, 19.08it/s]
2026-07-14 05:45:15 - [stt_benchmarking.utils.decorators.execution_time_wrapper:22] INFO - Execution time for function run_inference_one_by_one: 2 minutes 17 seconds
2026-07-14 05:45:15 - [stt_benchmarking.models.speech_to_text.english.reset:184] INFO - Fastconformer_hybridInference instance has been reset. Model remains loaded.

## Seamless M4t v2

In [6]:
from stt_benchmarking.models.speech_to_text.english import seamlessm4t_v2
importlib.reload(seamlessm4t_v2)

seamless_m4t = seamlessm4t_v2.SeamlessM4TFullInterface(device=device)
seamless_m4t.run_inference_optimized(records)
save_list_info(seamless_m4t.samples_info, "seamless_samples")
seamless_m4t.overall_metrics

`torch_dtype` is deprecated! Use `dtype` instead!

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

2026-07-14 03:27:40 - [stt_benchmarking.models.speech_to_text.english._load_model:73] INFO - Loaded Seamless M4T V2 Model
`torch_dtype` is deprecated! Use `dtype` instead!

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

Device set to use cuda:0
2026-07-14 03:27:47 - [stt_benchmarking.models.speech_to_text.english._load_pipeline:99] INFO - Loaded Seamless M4T V2 Pipeline (20s chunks / 1s stride)
2026-07-14 03:27:47 - [stt_benchmarking.models.speech_to_text.english.run_inference_optimized:279] INFO - Running one-by-one inference on 2611 short files (<30.0s)
Processing Records: 100%|██████████| 2611/2611 [47:50<00:00,  1.10s/it]
2026-07-14 04:15:38 - [stt_benchmarking.utils.decorators.execution_time_wrapper:22] INFO - Execution time for function run_inference_one_by_one: 47 minutes 50 seconds
2026-07-14 04:15:38 - [stt_benchmarking.models.speech_to_text.english.run_inference_optimized:283] INFO - Running batch inference on 9 long files (≥30.0s)

Processing Batches:   0%|          | 0/9 [00:00<?, ? examples/s]

2026-07-14 04:16:57 - [stt_benchmarking.utils.decorators.execution_time_wrapper:22] INFO - Execution time for function run_batch_inference: 1 minutes 19 seconds
2026-07-14 04:16:57 - [stt_benchmarking.utils.decorators.execution_time_wrapper:22] INFO - Execution time for function run_inference_optimized: 49 minutes 9 seconds

{'word_error_rate': {'wer (%)': 2.69,
  'word_similarity_ratio (%)': 98.66,
  'word_edit_distance': 1427,
  'substitutions': 1084,
  'deletions': 126,
  'insertions': 217,
  'hits': 51817,
  'ref_length': 53027,
  'hyp_length': 53118},
 'character_error_rate': {'cer (%)': 1.0,
  'char_similarity_ratio (%)': 99.5,
  'char_edit_distance': 2798,
  'substitutions': 1039,
  'deletions': 782,
  'insertions': 977,
  'hits': 278870,
  'ref_length': 280691,
  'hyp_length': 280886}}

In [6]:
import os
import json

def load_samples_info(file_name, file_dr="../../results/librespeech/audios"):
    """
    Load a JSON file from the given directory and normalize paths to start with ../../data
    
    Args:
        file_name (str): Name of the JSON file (with .json extension).
        file_dr (str): Directory where the file is stored.

    Returns:
        dict: Parsed JSON data with normalized paths as keys.
    """
    file_path = os.path.join(file_dr, file_name)
    with open(file_path, "r", encoding="utf-8") as f:
        data = json.load(f)
    
    normalized_data = {}
    for key, value in data.items():        
        normalized_data[key] = value
    
    return normalized_data

In [7]:
def collect_model_metrics(models_with_names):
    """
    Collect metrics from multiple model samples_info objects into a unified DataFrame.
    
    Parameters
    ----------
    models_with_names : list[tuple[str, dict]]
        List of tuples (model_name, samples_info_dict).
    
    Returns
    -------
    pd.DataFrame
        DataFrame containing all model metrics and metadata.
    """
    records = []
    for model_name, samples_info in models_with_names:
        for audio_id, content in samples_info.items():
            metrics = content["metrics"]
            wer_data = metrics["word_error_rate"]
            cer_data = metrics["character_error_rate"]

            wer = wer_data["wer (%)"]
            cer = cer_data["cer (%)"]

            if model_name in {"ensemble", "hybrid_ensemble", "rover"}:
                inference_time = content.get("fusion_time")
            else:
                inference_time = content.get("inference_time")

            records.append({
                "audio_id": audio_id,
                "model": model_name,
                "raw_transcription": content.get("raw_transcription"),
                "normalized_transcription": content.get("normalized_transcription"),
                "raw_prediction": content.get("raw_prediction"),
                "normalized_prediction": content.get("normalized_prediction"),
                "inference_time": inference_time,
                "rtf": content.get("rtf"),
                "fusion_time": content.get("fusion_time"),
                "duration": content.get("duration"),
                "wer": wer,
                "substitutions_w": wer_data["substitutions"],
                "deletions_w": wer_data["deletions"],
                "insertions_w": wer_data["insertions"],
                "hits_w": wer_data["hits"],
                "cer": cer,
                "substitutions_c": cer_data["substitutions"],
                "deletions_c": cer_data["deletions"],
                "insertions_c": cer_data["insertions"],
                "hits_c": cer_data["hits"],
            })

    return pd.DataFrame(records)

def filter_audio_records(df_samples, ensemble_name="ensemble"):
    empty = df_samples["normalized_prediction"].fillna("").str.strip() == ""
    is_ens = df_samples["model"] == ensemble_name
    ens_empty = (empty & is_ens).groupby(df_samples["audio_id"]).transform("any")

    empty_gt = df_samples["normalized_transcription"].fillna("").str.strip() == ""
    gt_empty = empty_gt.groupby(df_samples["audio_id"]).transform("any")

    drop = ens_empty | gt_empty
    df_filtered = df_samples[~drop].reset_index(drop=True)

    print(f"Audios dropped (empty ground truth): {df_samples.loc[gt_empty, 'audio_id'].nunique()}")
    print(f"Audios dropped (empty {ensemble_name}): {df_samples.loc[ens_empty, 'audio_id'].nunique()}")
    print(f"Audios: {df_samples['audio_id'].nunique()} -> {df_filtered['audio_id'].nunique()}")
    return df_filtered

def evaluate_absolute_metrics(df_filtered):
    """
    Compute absolute WER/CER metrics for each model against human references.
    """
    agg_results = []
    for model, g in df_filtered.groupby("model"):
        refs = g["normalized_transcription"].tolist()
        hyps = g["normalized_prediction"].tolist()

        duration_mean = pd.Series(g.get("duration", [])).dropna().mean()
        inference_time_mean = pd.Series(g.get("inference_time", [])).dropna().mean()
        rtf_mean = pd.Series(g.get("rtf", [])).dropna().mean()
        fusion_time_mean = pd.Series(g.get("fusion_time", [])).dropna().mean()
        eval_result = mt.BasicSTTMetrics.evaluate(refs=refs, hyps=hyps)
        word_metrics = eval_result['word_error_rate']
        char_metrics = eval_result['character_error_rate']

        agg_results.append({
            "model": model,
            "WER (%)": word_metrics["wer (%)"],
            "w_substitutions": word_metrics["substitutions"],
            "w_deletions": word_metrics["deletions"],
            "w_insertions": word_metrics["insertions"],
            "w_hits": word_metrics["hits"],
            "word_edit_distance": word_metrics["word_edit_distance"],
            "word_similarity_ratio (%)": word_metrics["word_similarity_ratio (%)"],
            "w_ref_length": word_metrics["ref_length"],
            "w_hyp_length": word_metrics["hyp_length"],

            "CER (%)": char_metrics["cer (%)"],
            "c_substitutions": char_metrics["substitutions"],
            "c_deletions": char_metrics["deletions"],
            "c_insertions": char_metrics["insertions"],
            "c_hits": char_metrics["hits"],
            "char_edit_distance": char_metrics["char_edit_distance"],
            "char_similarity_ratio (%)": char_metrics["char_similarity_ratio (%)"],
            "c_ref_length": char_metrics["ref_length"],
            "c_hyp_length": char_metrics["hyp_length"],

            "duration_mean": duration_mean if not pd.isna(duration_mean) else None,
            "inference_time_mean": inference_time_mean if not pd.isna(inference_time_mean) else None,
            "rtf_mean": rtf_mean if not pd.isna(rtf_mean) else None,
            "inference_time_total_h": (inference_time_mean * len(g) / 3600) if not pd.isna(inference_time_mean) else None,
            "fusion_time_mean": fusion_time_mean
            
        })

    df_eval = pd.DataFrame(agg_results)
    df_eval = df_eval.sort_values(
        by=["WER (%)", "word_similarity_ratio (%)"],
        ascending=[True, False]
    ).reset_index(drop=True)
    return df_eval

def evaluate_relative_metrics(df_filtered, model_name, exclude_models=[]):
    """
    Compute relative WER/CER metrics for each model using ensemble outputs as reference.
    """
    agg_results = []

    ensemble_df = (
        df_filtered[df_filtered['model'] == model_name]
        [["audio_id", "normalized_prediction"]]
        .reset_index(drop=True)
    )
    ensemble_df['_order'] = range(len(ensemble_df))

    assert ensemble_df["audio_id"].is_unique, "Duplicate audio_id in ensemble."
    assert ensemble_df["normalized_prediction"].notna().all(), "Ensemble contains None normalized_prediction."

    models_to_compare = df_filtered[~df_filtered['model'].isin(exclude_models)]

    for model, g in models_to_compare.groupby("model"):
        g = g[["audio_id", "normalized_prediction"]].reset_index(drop=True)

        assert g["audio_id"].is_unique, f"Duplicate audio_id in model {model}."
        assert g["normalized_prediction"].notna().all(), f"Model {model} contains None normalized_prediction."

        merged = ensemble_df.merge(g, on="audio_id", suffixes=("_ref", "_hyp"), how="inner")
        merged = merged.sort_values("_order").reset_index(drop=True)
        assert len(merged) == len(ensemble_df), f"Alignment mismatch for {model}: {len(merged)} vs {len(ensemble_df)}."

        refs = merged["normalized_prediction_ref"].tolist()
        hyps = merged["normalized_prediction_hyp"].tolist()
        assert len(refs) > 0, f"No valid reference for model {model}."

        eval_result = mt.BasicSTTMetrics.evaluate(refs=refs, hyps=hyps)
        word_metrics = eval_result['word_error_rate']
        char_metrics = eval_result['character_error_rate']

        agg_results.append({
            "model": model,
            "WER (%)": word_metrics["wer (%)"],
            "w_substitutions": word_metrics["substitutions"],
            "w_deletions": word_metrics["deletions"],
            "w_insertions": word_metrics["insertions"],
            "w_hits": word_metrics["hits"],
            "word_edit_distance": word_metrics["word_edit_distance"],
            "word_similarity_ratio (%)": word_metrics["word_similarity_ratio (%)"],
            "w_ref_length": word_metrics["ref_length"],
            "w_hyp_length": word_metrics["hyp_length"],

            "CER (%)": char_metrics["cer (%)"],
            "c_substitutions": char_metrics["substitutions"],
            "c_deletions": char_metrics["deletions"],
            "c_insertions": char_metrics["insertions"],
            "c_hits": char_metrics["hits"],
            "char_edit_distance": char_metrics["char_edit_distance"],
            "char_similarity_ratio (%)": char_metrics["char_similarity_ratio (%)"],
            "c_ref_length": char_metrics["ref_length"],
            "c_hyp_length": char_metrics["hyp_length"],
        })

    df_relative = pd.DataFrame(agg_results)
    df_relative = df_relative.sort_values(
        by=["WER (%)", "word_similarity_ratio (%)"],
        ascending=[True, False]
    ).reset_index(drop=True)
    return df_relative

In [8]:
import numpy as np
import pandas as pd
from scipy.stats import spearmanr, kendalltau, pearsonr

# assumes `mt` (your metrics module) is importable in the calling scope,
# i.e. mt.BasicSTTMetrics.evaluate(refs=..., hyps=...) as used elsewhere.


def add_pseudo_reference_wer(df_filtered, ensemble, transcript_key="normalized_prediction"):
    """
    Add per-sample pseudo-reference WER/CER.

    ensemble : dict[audio_id -> dict] with the fused transcript under `transcript_key`.
    """
    ens = {aid: v[transcript_key] for aid, v in ensemble.items()}

    refs = df_filtered["audio_id"].map(ens)
    hyps = df_filtered[transcript_key]

    pseudo_wer, pseudo_cer = [], []
    for ref, hyp in zip(refs, hyps):
        if not isinstance(ref, str) or not ref.strip() or not isinstance(hyp, str):
            pseudo_wer.append(np.nan)
            pseudo_cer.append(np.nan)
            continue
        r = mt.BasicSTTMetrics.evaluate(refs=ref, hyps=hyp)
        pseudo_wer.append(r["word_error_rate"]["wer (%)"])
        pseudo_cer.append(r["character_error_rate"]["cer (%)"])

    df = df_filtered.copy()
    df["pseudo_wer"] = pseudo_wer
    df["pseudo_cer"] = pseudo_cer

    missing = refs.isna().sum()
    if missing:
        print(f"Rows with no ensemble reference: {missing}")
    return df

def _corr(x, y):
    if len(x) < 3 or pd.Series(x).nunique() < 2 or pd.Series(y).nunique() < 2:
        return None
    sp = spearmanr(x, y)
    kt = kendalltau(x, y)
    pr = pearsonr(x, y)
    return {
        "pearson": pr.statistic, "pearson_p": pr.pvalue,
        "spearman": sp.statistic, "spearman_p": sp.pvalue,
        "kendall": kt.statistic, "kendall_p": kt.pvalue,
    }


def per_sample_correlation(df_pseudo, exclude_models=("ensemble", "rover"),
                           metric_pair=("wer", "pseudo_wer"), min_pairs=30):
    """
    Option A. Per-sample WER tracking: correlate true WER vs pseudo-reference WER.

    Returns a df with one row per model (within-model, across samples) plus an
    'ALL' row (pooled over every sample-model pair, the direct NoRefER analogue).
    """
    true_col, pseudo_col = metric_pair
    sub = df_pseudo[~df_pseudo["model"].isin(exclude_models)].copy()
    rows = []

    for model, g in sub.groupby("model"):
        d = g[[true_col, pseudo_col]].dropna()
        if len(d) < min_pairs:
            continue
        c = _corr(d[true_col].values, d[pseudo_col].values)
        if c:
            rows.append({"model": model, "n": len(d), **c})

    d_all = sub[[true_col, pseudo_col]].dropna()
    c_all = _corr(d_all[true_col].values, d_all[pseudo_col].values)
    if c_all:
        rows.append({"model": "ALL (pooled)", "n": len(d_all), **c_all})

    return pd.DataFrame(rows).sort_values("spearman", ascending=False).reset_index(drop=True)


def per_sample_ranking(df_pseudo, exclude_models=("ensemble", "rover"),
                       metric_cols=("wer", "pseudo_wer"),
                       tiebreak_cols=("cer", "pseudo_cer"),
                       min_models=3):
    """
    Per-sample ranking agreement, WER primary with CER as tiebreak only.

    For each sample, systems are ordered by true (WER, then CER) and by
    pseudo (WER, then CER); CER is consulted solely to break exact WER ties,
    so the axis remains a WER ranking, not a WER+CER blend. The two orderings
    are correlated within the sample, then aggregated across samples.

    Returns a one-row summary df with mean/median/std of Spearman and Kendall,
    usable/dropped sample counts, and the residual WER tie fraction.
    """
    true_w, pseudo_w = metric_cols
    true_c, pseudo_c = tiebreak_cols
    sub = df_pseudo[~df_pseudo["model"].isin(exclude_models)].copy()

    sp_vals, kt_vals, tie_fracs = [], [], []
    n_dropped = 0

    for audio_id, g in sub.groupby("audio_id"):
        d = g[[true_w, pseudo_w, true_c, pseudo_c]].dropna()
        if len(d) < min_models:
            n_dropped += 1
            continue

        # residual WER-only tie fraction, before CER breaks them (diagnostic)
        _, counts = np.unique(d[true_w].values, return_counts=True)
        tie_fracs.append(1.0 - len(counts) / len(d))

        # composite ranks: WER primary, CER tiebreak. lexsort keys are
        # applied last-key-first, so primary key goes last.
        true_rank = np.lexsort((d[true_c].values, d[true_w].values)).argsort()
        pseudo_rank = np.lexsort((d[pseudo_c].values, d[pseudo_w].values)).argsort()

        if pd.Series(true_rank).nunique() < 2 or pd.Series(pseudo_rank).nunique() < 2:
            n_dropped += 1
            continue

        sp_vals.append(spearmanr(true_rank, pseudo_rank).statistic)
        kt_vals.append(kendalltau(true_rank, pseudo_rank).statistic)

    summary = {
        "n_samples_used": len(sp_vals),
        "n_samples_dropped": n_dropped,
        "mean_wer_ties": float(np.mean(tie_fracs)) if tie_fracs else np.nan,
        "spearman_mean": float(np.nanmean(sp_vals)) if sp_vals else np.nan,
        "spearman_median": float(np.nanmedian(sp_vals)) if sp_vals else np.nan,
        "spearman_std": float(np.nanstd(sp_vals)) if sp_vals else np.nan,
        "kendall_mean": float(np.nanmean(kt_vals)) if kt_vals else np.nan,
        "kendall_median": float(np.nanmedian(kt_vals)) if kt_vals else np.nan,
        "kendall_std": float(np.nanstd(kt_vals)) if kt_vals else np.nan,
    }
    return pd.DataFrame([summary])


def ranking_correlation(df_absolute, df_relative, exclude_models=("ensemble", "rover")):
    """
    Option B (headline). Correlate the reference ranking against the
    pseudo-reference ranking over models, on full-set aggregate WER.

    df_absolute : output of evaluate_absolute_metrics
    df_relative : output of evaluate_relative_metrics
    Returns (merged_df, coefficients_dict).
    """
    a = df_absolute[["model", "WER (%)"]].rename(columns={"WER (%)": "wer_abs"})
    r = df_relative[["model", "WER (%)"]].rename(columns={"WER (%)": "wer_rel"})
    m = a.merge(r, on="model", how="inner")
    m = m[~m["model"].isin(exclude_models)].reset_index(drop=True)

    c = _corr(m["wer_abs"].values, m["wer_rel"].values)
    return m, c

In [9]:
seamless_samples = load_samples_info("seamless_samples.json")
whisper_samples = load_samples_info("whisper_v3_samples.json")
canary_samples = load_samples_info("canary_samples.json")
conformer_samples = load_samples_info("conformer_samples.json")
parakeet_samples = load_samples_info("parakeet_samples.json")
sb_samples = load_samples_info("sb_samples_flat.json")
cohere_samples = load_samples_info("cohere_samples.json")

In [10]:
def norm(p):
    return os.path.normpath(p).replace("\\","/")

exclude_paths={norm(r["audio_path"]) for r in records_bigger_30}

def drop_excluded(samples):
    return {k:v for k,v in samples.items() if norm(k) not in exclude_paths}

seamless_samples=drop_excluded(seamless_samples)
whisper_samples=drop_excluded(whisper_samples)
canary_samples=drop_excluded(canary_samples)
conformer_samples=drop_excluded(conformer_samples)
parakeet_samples=drop_excluded(parakeet_samples)
sb_samples=drop_excluded(sb_samples)
cohere_samples=drop_excluded(cohere_samples)

In [11]:
all_models = [
    seamless_samples,
    whisper_samples,
    canary_samples,
    conformer_samples,
    parakeet_samples,
    sb_samples,
    cohere_samples
]

model_names = [
    "seamless_m4t",
    "whisper_v3",
    "canary",
    "conformer",
    "parakeet",
    "sb",
    "cohere"
]
voters = ["seamless_m4t", "whisper_v3", "parakeet", "sb", "cohere"]
voters_as_elements = [seamless_samples, whisper_samples, parakeet_samples, sb_samples, cohere_samples]

## ROVER Evaluation Protocol

In [12]:
from stt_benchmarking.utils import evaluation_protocol
from stt_benchmarking.models.speech_to_text.english import ensemble, rover
importlib.reload(evaluation_protocol)

proto = evaluation_protocol.EvaluationProtocol(
    model_samples=dict(zip(model_names, all_models)),
    voters=voters,
    ensemble_factory=rover.ROVER,
    outdir="protocol_out/librispeech_clean_final_rover1.1",
    n_boot=10000, seed=42, min_pool_size=3,
    suffix="_rover_librespeech",
)
report = proto.run()

2026-09-09 13:50:42 - [stt_benchmarking.utils.evaluation_protocol.step0_decorrelation:265] INFO - Step 0 Finished.
ROVER Fusion...: 100%|██████████| 2611/2611 [00:05<00:00, 512.07it/s]
ROVER Fusion...: 100%|██████████| 2611/2611 [00:04<00:00, 633.98it/s]
ROVER Fusion...: 100%|██████████| 2611/2611 [00:02<00:00, 1134.00it/s]
ROVER Fusion...: 100%|██████████| 2611/2611 [00:05<00:00, 469.25it/s]
ROVER Fusion...: 100%|██████████| 2611/2611 [00:02<00:00, 874.01it/s]
ROVER Fusion...: 100%|██████████| 2611/2611 [00:06<00:00, 400.67it/s]
2026-09-09 13:51:21 - [stt_benchmarking.utils.evaluation_protocol.step1_bias:295] INFO - Step 1 Finished.
2026-09-09 13:51:21 - [stt_benchmarking.utils.evaluation_protocol.step2_ranking:328] INFO - Step 2 Finished.
ROVER Fusion...: 100%|██████████| 2611/2611 [00:08<00:00, 290.18it/s]
2026-09-09 13:51:33 - [stt_benchmarking.utils.evaluation_protocol.step3_pipeline:383] INFO - Step 3 Finished.
2026-09-09 13:51:35 - [stt_benchmarking.utils.evaluation_protocol.step4_bootstrap:427] INFO - Step 4 Finished.
2026-09-09 13:51:37 - [stt_benchmarking.utils.evaluation_protocol.step4_bootstrap:427] INFO - Step 4 Finished.
2026-09-09 13:51:46 - [stt_benchmarking.utils.evaluation_protocol.step5_baselines:471] INFO - Step 5 Finished.
ROVER Fusion...: 100%|██████████| 2611/2611 [00:02<00:00, 1052.37it/s]
ROVER Fusion...: 100%|██████████| 2611/2611 [00:00<00:00, 2704.39it/s]
ROVER Fusion...: 100%|██████████| 2611/2611 [00:02<00:00, 1015.92it/s]
ROVER Fusion...: 100%|██████████| 2611/2611 [00:05<00:00, 461.14it/s]
ROVER Fusion...: 100%|██████████| 2611/2611 [00:00<00:00, 7715.57it/s]
ROVER Fusion...: 100%|██████████| 2611/2611 [00:04<00:00, 527.64it/s]
ROVER Fusion...: 100%|██████████| 2611/2611 [00:00<00:00, 4881.84it/s]
ROVER Fusion...: 100%|██████████| 2611/2611 [00:07<00:00, 361.55it/s]
ROVER Fusion...: 100%|██████████| 2611/2611 [00:00<00:00, 2971.95it/s]
ROVER Fusion...: 100%|██████████| 2611/2611 [00:01<00:00, 1640.04it/s]
2026-09-09 13:53:02 - [stt_benchmarking.utils.evaluation_protocol.step6_ablation:585] INFO - Step 6 Finished.
2026-09-09 13:53:02 - [stt_benchmarking.utils.evaluation_protocol.step7_floor:611] INFO - Step 7 Finished.

=== skipped_empty_gt ===
0

=== main_kwargs_applied ===
{}

=== main_kwargs_dropped ===
[]

=== step0_cross_wer ===
              seamless_m4t  whisper_v3  canary  conformer  parakeet    sb  cohere
seamless_m4t          0.00        2.84    2.21       2.38      2.14  2.56    2.14
whisper_v3            2.84        0.00    2.35       2.60      2.22  2.81    2.16
canary                2.21        2.35    0.00       1.90      1.27  2.16    1.54
conformer             2.38        2.60    1.90       0.00      1.60  1.89    1.60
parakeet              2.14        2.22    1.27       1.60      0.00  1.88    1.29
sb                    2.56        2.81    2.16       1.89      1.88  0.00    1.74
cohere                2.14        2.16    1.54       1.60      1.29  1.74    0.00

=== step0_err_corr ===
              seamless_m4t  whisper_v3  canary  conformer  parakeet      sb  cohere
seamless_m4t        1.0000      0.5964  0.6161     0.6072    0.6198  0.5441  0.5400
whisper_v3          0.5964      1.0000  0.6137     0.5985    0.6236  0.5265  0.5666
canary              0.6161      0.6137  1.0000     0.6336    0.7444  0.5804  0.5842
conformer           0.6072      0.5985  0.6336     1.0000    0.6947  0.6515  0.6100
parakeet            0.6198      0.6236  0.7444     0.6947    1.0000  0.6234  0.6282
sb                  0.5441      0.5265  0.5804     0.6515    0.6234  1.0000  0.5721
cohere              0.5400      0.5666  0.5842     0.6100    0.6282  0.5721  1.0000

=== step0_flags ===
                 pair  cross_wer  err_corr                                                            note
0     canary|parakeet       1.27    0.7444  unusually similar hypotheses - suspect shared lab/data/teacher
1       canary|cohere       1.54    0.5842  unusually similar hypotheses - suspect shared lab/data/teacher
2  conformer|parakeet       1.60    0.6947  unusually similar hypotheses - suspect shared lab/data/teacher
3    conformer|cohere       1.60    0.6100  unusually similar hypotheses - suspect shared lab/data/teacher
4     parakeet|cohere       1.29    0.6282  unusually similar hypotheses - suspect shared lab/data/teacher

=== step1_bias ===
          model                  role  n_samples  spearman_full  spearman_loo  kendall_full  kendall_loo  delta_spearman  delta_kendall
0        cohere                 voter       2611         0.4111        0.4164        0.3932       0.3967          0.0053         0.0034
1      parakeet                 voter       2611         0.5803        0.6001        0.5560       0.5732          0.0197         0.0171
2    whisper_v3                 voter       2611         0.6424        0.6707        0.6133       0.6404          0.0282         0.0271
3            sb                 voter       2611         0.6693        0.6875        0.6395       0.6565          0.0182         0.0169
4        canary  ranked_only(control)       2611         0.6695        0.6695        0.6397       0.6397          0.0000         0.0000
5     conformer  ranked_only(control)       2611         0.7215        0.7215        0.6891       0.6891          0.0000         0.0000
6  seamless_m4t                 voter       2611         0.7489        0.7758        0.7148       0.7405          0.0268         0.0257

=== step2_ranking ===
          model         role  n_samples  wer_true  cer_true  wer_pseudo_loo  cer_pseudo_loo  rank_true  rank_pseudo  wer_compression
0        cohere        voter       2611    1.2245    0.3722          1.1257          0.3998          1            1           0.0988
1      parakeet        voter       2611    1.6677    0.4946          1.2396          0.4156          2            2           0.4280
2        canary  ranked_only       2611    1.8912    0.6029          1.2848          0.4303          3            3           0.6063
3     conformer  ranked_only       2611    2.0325    0.5964          1.3536          0.4003          4            4           0.6789
4            sb        voter       2611    2.2063    0.6697          1.6642          0.5276          5            5           0.5421
5  seamless_m4t        voter       2611    2.5693    0.9011          1.9443          0.7437          6            6           0.6250
6    whisper_v3        voter       2611    2.6018    1.3488          2.0302          1.1920          7            7           0.5715

=== step2_stats ===
{
  "n_models": 7,
  "spearman": 1.0,
  "kendall_b": 1.0,
  "spearman_exact_p_onetailed": 0.0001984126984126984,
  "kendall_exact_p_onetailed": 0.0001984126984126984,
  "p_method": "exact",
  "n_permutations": 5040,
  "min_attainable_p": 0.0001984126984126984,
  "pearson": 0.9395291415419034,
  "pearson_p": 0.0016714872289728428,
  "mean_wer_compression": 0.5072525031631511
}

=== step3_runs ===
                      run  n_voters  n_samples  filter_fire_rate  tie_rate  refsel_rover_full_wtn
0               full_pool         5       2611            0.4025    0.0033                    1.0
1  LOO_minus_seamless_m4t         4       2611            0.2830    0.0044                    1.0
2    LOO_minus_whisper_v3         4       2611            0.3095    0.0052                    1.0
3      LOO_minus_parakeet         4       2611            0.3275    0.0050                    1.0
4            LOO_minus_sb         4       2611            0.3052    0.0041                    1.0
5        LOO_minus_cohere         4       2611            0.3340    0.0051                    1.0

=== step3_model_dropout ===
          model  times_filtered_out  times_in_pool  filtered_out_rate
0  seamless_m4t                2114          13055             0.1619
3            sb                1499          13055             0.1148
1    whisper_v3                1269          13055             0.0972
2      parakeet                 826          13055             0.0633
4        cohere                 669          13055             0.0512

=== step3_determinism ===
{
  "identical_outputs": 2611,
  "n": 2611,
  "deterministic": true,
  "main_kwargs": {}
}

=== step4_pairs_true ===
                         pair  adjacent  gap_wer  preserved_frac  resolved_95
0   seamless_m4t < whisper_v3      True   0.0325          0.5275        False
1          canary < conformer      True   0.1414          0.9871         True
2              conformer < sb      True   0.1738          0.9965         True
3           parakeet < canary      True   0.2235          1.0000         True
4                 canary < sb     False   0.3152          1.0000         True
5           sb < seamless_m4t      True   0.3629          1.0000         True
6        parakeet < conformer     False   0.3649          1.0000         True
7             sb < whisper_v3     False   0.3954          0.9733         True
8           cohere < parakeet      True   0.4432          1.0000         True
9    conformer < seamless_m4t     False   0.5368          1.0000         True
10              parakeet < sb     False   0.5387          1.0000         True
11     conformer < whisper_v3     False   0.5693          0.9993         True
12            cohere < canary     False   0.6667          1.0000         True
13      canary < seamless_m4t     False   0.6781          1.0000         True
14        canary < whisper_v3     False   0.7106          1.0000         True
15         cohere < conformer     False   0.8080          1.0000         True
16    parakeet < seamless_m4t     False   0.9016          1.0000         True
17      parakeet < whisper_v3     False   0.9341          1.0000         True
18                cohere < sb     False   0.9819          1.0000         True
19      cohere < seamless_m4t     False   1.3448          1.0000         True
20        cohere < whisper_v3     False   1.3773          1.0000         True

=== step4_resolution_true ===
{
  "reference": "true",
  "n_boot": 10000,
  "n_samples": 2611,
  "min_resolved_gap_wer": 0.14135895623603112,
  "max_unresolved_gap_wer": 0.032474354810980266,
  "n_resolved": 20,
  "n_pairs": 21
}

=== step4_pairs_pseudo ===
                         pair  adjacent  gap_wer  preserved_frac  resolved_95
0           parakeet < canary      True   0.0452          0.7742        False
1          canary < conformer      True   0.0687          0.8400        False
2   seamless_m4t < whisper_v3      True   0.0859          0.6245        False
3           cohere < parakeet      True   0.1140          0.9850         True
4        parakeet < conformer     False   0.1140          0.9715         True
5             cohere < canary     False   0.1592          0.9955         True
6          cohere < conformer     False   0.2279          0.9998         True
7           sb < seamless_m4t      True   0.2801          1.0000         True
8              conformer < sb      True   0.3106          1.0000         True
9             sb < whisper_v3     False   0.3660          0.9631         True
10                canary < sb     False   0.3794          1.0000         True
11              parakeet < sb     False   0.4246          1.0000         True
12                cohere < sb     False   0.5386          1.0000         True
13   conformer < seamless_m4t     False   0.5908          1.0000         True
14      canary < seamless_m4t     False   0.6595          1.0000         True
15     conformer < whisper_v3     False   0.6767          1.0000         True
16    parakeet < seamless_m4t     False   0.7047          1.0000         True
17        canary < whisper_v3     False   0.7454          1.0000         True
18      parakeet < whisper_v3     False   0.7906          1.0000         True
19      cohere < seamless_m4t     False   0.8187          1.0000         True
20        cohere < whisper_v3     False   0.9046          1.0000         True

=== step4_resolution_pseudo ===
{
  "reference": "pseudo",
  "n_boot": 10000,
  "n_samples": 2611,
  "min_resolved_gap_wer": 0.11395292593008444,
  "max_unresolved_gap_wer": 0.0859018532006568,
  "n_resolved": 18,
  "n_pairs": 21
}

=== step5_baselines ===
                                        reference  n_models  spearman  kendall_b  spearman_exact_p_onetailed  kendall_exact_p_onetailed p_method  n_permutations  min_attainable_p  mean_abs_wer_err
0                         LOO ensemble (proposed)         7    1.0000     1.0000                      0.0002                     0.0002    exact            5040            0.0002            0.5073
1                          full ensemble (biased)         7    1.0000     1.0000                      0.0002                     0.0002    exact            5040            0.0002            0.7447
2                      single model: seamless_m4t         6    1.0000     1.0000                      0.0014                     0.0014    exact             720            0.0014            0.4404
3   LOO ensemble matched to n-1 (vs seamless_m4t)         6    1.0000     1.0000                      0.0014                     0.0014    exact             720            0.0014            0.4876
4                        single model: whisper_v3         6    1.0000     1.0000                      0.0014                     0.0014    exact             720            0.0014            0.5616
5     LOO ensemble matched to n-1 (vs whisper_v3)         6    1.0000     1.0000                      0.0014                     0.0014    exact             720            0.0014            0.4965
6                          single model: parakeet         6    0.9429     0.8667                      0.0083                     0.0083    exact             720            0.0014            0.3735
7       LOO ensemble matched to n-1 (vs parakeet)         6    1.0000     1.0000                      0.0014                     0.0014    exact             720            0.0014            0.5205
8                                single model: sb         6    0.9429     0.8667                      0.0083                     0.0083    exact             720            0.0014            0.2294
9             LOO ensemble matched to n-1 (vs sb)         6    1.0000     1.0000                      0.0014                     0.0014    exact             720            0.0014            0.5014
10                           single model: cohere         6    1.0000     1.0000                      0.0014                     0.0014    exact             720            0.0014            0.4138
11        LOO ensemble matched to n-1 (vs cohere)         6    1.0000     1.0000                      0.0014                     0.0014    exact             720            0.0014            0.5753

=== step6_pools ===
                                          pool  k  ensemble_wer_vs_true  ensemble_cer_vs_true  ranking_spearman  ranking_exact_p  ranking_kendall_b  ranking_kendall_exact_p  n_pairs_wrong  n_pairs_wrong_resolvable  worst_wrong_gap_wer     worst_wrong_pair
0                whisper_v3+parakeet+sb+cohere  4                1.3620                0.4516            0.2857           0.2780             0.2381                   0.2810            8.0                       8.0               1.3448  cohere|seamless_m4t
1   seamless_m4t+whisper_v3+parakeet+sb+cohere  5                1.3773                0.4195            1.0000           0.0002             1.0000                   0.0002            0.0                       0.0               0.0000
2              seamless_m4t+parakeet+sb+cohere  4                1.3907                0.4368            0.8214           0.0171             0.6190                   0.0345            4.0                       3.0               0.3649   parakeet|conformer
3                           parakeet+sb+cohere  3                1.4193                0.5426               NaN              NaN                NaN                      NaN            NaN                       NaN                  NaN
4      seamless_m4t+whisper_v3+parakeet+cohere  4                1.4270                0.4614            0.0357           0.4817             0.1429                   0.3863            9.0                       8.0               1.3773    cohere|whisper_v3
5            seamless_m4t+whisper_v3+sb+cohere  4                1.5015                0.5036            0.6429           0.0694             0.4286                   0.1194            6.0                       5.0               0.8080     cohere|conformer
6                 seamless_m4t+parakeet+cohere  3                1.5416                0.6534               NaN              NaN                NaN                      NaN            NaN                       NaN                  NaN
7          seamless_m4t+whisper_v3+parakeet+sb  4                1.6065                0.5303            0.6071           0.0833             0.5238                   0.0681            5.0                       4.0               0.9341  parakeet|whisper_v3
8                       seamless_m4t+sb+cohere  3                1.6657                0.6617               NaN              NaN                NaN                      NaN            NaN                       NaN                  NaN
9                     seamless_m4t+parakeet+sb  3                1.7842                0.7340               NaN              NaN                NaN                      NaN            NaN                       NaN                  NaN
10                  whisper_v3+parakeet+cohere  3                2.2274                1.3181               NaN              NaN                NaN                      NaN            NaN                       NaN                  NaN
11                        whisper_v3+sb+cohere  3                2.3076                1.3668               NaN              NaN                NaN                      NaN            NaN                       NaN                  NaN
12                      whisper_v3+parakeet+sb  3                2.4260                1.4073               NaN              NaN                NaN                      NaN            NaN                       NaN                  NaN
13              seamless_m4t+whisper_v3+cohere  3                2.5196                1.4874               NaN              NaN                NaN                      NaN            NaN                       NaN                  NaN
14            seamless_m4t+whisper_v3+parakeet  3                2.6457                1.5246               NaN              NaN                NaN                      NaN            NaN                       NaN                  NaN
15                  seamless_m4t+whisper_v3+sb  3                2.7489                1.5603               NaN              NaN                NaN                      NaN            NaN                       NaN                  NaN

=== step6_contribution ===
  model_removed  delta_ensemble_wer  delta_ranking_spearman  helps_reference_quality  helps_ranking  delta_pairs_wrong  delta_pairs_wrong_resolvable
0  seamless_m4t             -0.0153                 -0.7143                    False          False                8.0                           8.0
1    whisper_v3              0.0134                 -0.1786                     True          False                4.0                           3.0
2      parakeet              0.1242                 -0.3571                     True          False                6.0                           5.0
3            sb              0.0497                 -0.9643                     True          False                9.0                           8.0
4        cohere              0.2292                 -0.3929                     True          False                5.0                           4.0

=== step6_wrong_pairs ===
                                       pool  k                     pair   true_winner   pred_winner  wer_true_a  wer_true_b  wer_pseudo_a  wer_pseudo_b  gap_wer_true  gap_wer_pseudo  human_resolvable
0   seamless_m4t+whisper_v3+parakeet+cohere  4        cohere|whisper_v3        cohere    whisper_v3      1.2245      2.6018        2.1936        2.1700        1.3773          0.0235              True
1             whisper_v3+parakeet+sb+cohere  4      cohere|seamless_m4t        cohere  seamless_m4t      1.2245      2.5693        1.9605        1.9443        1.3448          0.0161              True
2   seamless_m4t+whisper_v3+parakeet+cohere  4                cohere|sb        cohere            sb      1.2245      2.2063        2.1936        1.6642        0.9819          0.5294              True
3       seamless_m4t+whisper_v3+parakeet+sb  4      parakeet|whisper_v3      parakeet    whisper_v3      1.6677      2.6018        2.3396        2.2856        0.9341          0.0540              True
4   seamless_m4t+whisper_v3+parakeet+cohere  4      parakeet|whisper_v3      parakeet    whisper_v3      1.6677      2.6018        2.2610        2.1700        0.9341          0.0910              True
5             whisper_v3+parakeet+sb+cohere  4    parakeet|seamless_m4t      parakeet  seamless_m4t      1.6677      2.5693        2.0963        1.9443        0.9016          0.1520              True
6   seamless_m4t+whisper_v3+parakeet+cohere  4         cohere|conformer        cohere     conformer      1.2245      2.0325        2.1936        1.4428        0.8080          0.7507              True
7         seamless_m4t+whisper_v3+sb+cohere  4         cohere|conformer        cohere     conformer      1.2245      2.0325        2.2396        1.4742        0.8080          0.7654              True
8             whisper_v3+parakeet+sb+cohere  4         cohere|conformer        cohere     conformer      1.2245      2.0325        1.9605        1.3700        0.8080          0.5905              True
9   seamless_m4t+whisper_v3+parakeet+cohere  4            cohere|canary        cohere        canary      1.2245      1.8912        2.1936        1.2844        0.6667          0.9091              True

## Ensemble Evaluation Protocol

In [13]:
from stt_benchmarking.utils import evaluation_protocol
from stt_benchmarking.models.speech_to_text.english import ensemble
importlib.reload(evaluation_protocol)

proto = evaluation_protocol.EvaluationProtocol(
    model_samples=dict(zip(model_names, all_models)),
    voters=voters,
    ensemble_factory=ensemble.HybridEnsemble,
    outdir="protocol_out/librispeech_validated_ensemble",
    n_boot=10000, seed=42, min_pool_size=3,
    suffix="_validated_ensemble_librispeech",
)
report = proto.run()

2026-09-22 17:33:02 - [stt_benchmarking.utils.evaluation_protocol.step0_decorrelation:265] INFO - Step 0 Finished.
Fusing Inputs...: 100%|██████████| 2611/2611 [00:05<00:00, 503.99it/s]
Fusing Inputs...: 100%|██████████| 2611/2611 [00:04<00:00, 641.32it/s]
Fusing Inputs...: 100%|██████████| 2611/2611 [00:04<00:00, 638.25it/s]
Fusing Inputs...: 100%|██████████| 2611/2611 [00:04<00:00, 628.10it/s]
Fusing Inputs...: 100%|██████████| 2611/2611 [00:04<00:00, 628.89it/s]
Fusing Inputs...: 100%|██████████| 2611/2611 [00:04<00:00, 582.68it/s]
2026-09-22 17:33:31 - [stt_benchmarking.utils.evaluation_protocol.step1_bias:295] INFO - Step 1 Finished.
2026-09-22 17:33:31 - [stt_benchmarking.utils.evaluation_protocol.step2_ranking:328] INFO - Step 2 Finished.
Fusing Inputs...: 100%|██████████| 2611/2611 [00:05<00:00, 477.06it/s]
2026-09-22 17:33:36 - [stt_benchmarking.utils.evaluation_protocol.step3_pipeline:383] INFO - Step 3 Finished.
2026-09-22 17:33:37 - [stt_benchmarking.utils.evaluation_protocol.step4_bootstrap:427] INFO - Step 4 Finished.
2026-09-22 17:33:38 - [stt_benchmarking.utils.evaluation_protocol.step4_bootstrap:427] INFO - Step 4 Finished.
2026-09-22 17:33:42 - [stt_benchmarking.utils.evaluation_protocol.step5_baselines:471] INFO - Step 5 Finished.
Fusing Inputs...: 100%|██████████| 2611/2611 [00:01<00:00, 1586.02it/s]
Fusing Inputs...: 100%|██████████| 2611/2611 [00:01<00:00, 1574.57it/s]
Fusing Inputs...: 100%|██████████| 2611/2611 [00:02<00:00, 1259.04it/s]
Fusing Inputs...: 100%|██████████| 2611/2611 [00:01<00:00, 1578.59it/s]
Fusing Inputs...: 100%|██████████| 2611/2611 [00:02<00:00, 1247.55it/s]
Fusing Inputs...: 100%|██████████| 2611/2611 [00:01<00:00, 1588.92it/s]
Fusing Inputs...: 100%|██████████| 2611/2611 [00:01<00:00, 1612.21it/s]
Fusing Inputs...: 100%|██████████| 2611/2611 [00:01<00:00, 1635.09it/s]
Fusing Inputs...: 100%|██████████| 2611/2611 [00:01<00:00, 1607.30it/s]
Fusing Inputs...: 100%|██████████| 2611/2611 [00:02<00:00, 1176.12it/s]
2026-09-22 17:34:06 - [stt_benchmarking.utils.evaluation_protocol.step6_ablation:585] INFO - Step 6 Finished.
2026-09-22 17:34:06 - [stt_benchmarking.utils.evaluation_protocol.step7_floor:611] INFO - Step 7 Finished.
Fusing Inputs...: 100%|██████████| 2611/2611 [00:05<00:00, 512.64it/s]
2026-09-22 17:34:11 - [stt_benchmarking.utils.evaluation_protocol.step8_permutation:652] INFO - Step 8 permutation 0: 2611/2611 identical.
Fusing Inputs...: 100%|██████████| 2611/2611 [00:05<00:00, 450.46it/s]
2026-09-22 17:34:17 - [stt_benchmarking.utils.evaluation_protocol.step8_permutation:652] INFO - Step 8 permutation 1: 2611/2611 identical.
Fusing Inputs...: 100%|██████████| 2611/2611 [00:05<00:00, 507.77it/s]
2026-09-22 17:34:22 - [stt_benchmarking.utils.evaluation_protocol.step8_permutation:652] INFO - Step 8 permutation 2: 2611/2611 identical.
Fusing Inputs...: 100%|██████████| 2611/2611 [00:05<00:00, 508.10it/s]
2026-09-22 17:34:27 - [stt_benchmarking.utils.evaluation_protocol.step8_permutation:652] INFO - Step 8 permutation 3: 2611/2611 identical.
Fusing Inputs...: 100%|██████████| 2611/2611 [00:05<00:00, 445.22it/s]
2026-09-22 17:34:33 - [stt_benchmarking.utils.evaluation_protocol.step8_permutation:652] INFO - Step 8 permutation 4: 2611/2611 identical.
Fusing Inputs...: 100%|██████████| 2611/2611 [00:05<00:00, 506.64it/s]
2026-09-22 17:34:39 - [stt_benchmarking.utils.evaluation_protocol.step8_permutation:652] INFO - Step 8 permutation 5: 2611/2611 identical.
2026-09-22 17:34:39 - [stt_benchmarking.utils.evaluation_protocol.step8_permutation:660] INFO - Step 8 Finished.

=== skipped_empty_gt ===
0

=== main_kwargs_applied ===
{}

=== main_kwargs_dropped ===
[]

=== step0_cross_wer ===
              seamless_m4t  whisper_v3  canary  conformer  parakeet    sb  cohere
seamless_m4t          0.00        2.84    2.21       2.38      2.14  2.56    2.14
whisper_v3            2.84        0.00    2.35       2.60      2.22  2.81    2.16
canary                2.21        2.35    0.00       1.90      1.27  2.16    1.54
conformer             2.38        2.60    1.90       0.00      1.60  1.89    1.60
parakeet              2.14        2.22    1.27       1.60      0.00  1.88    1.29
sb                    2.56        2.81    2.16       1.89      1.88  0.00    1.74
cohere                2.14        2.16    1.54       1.60      1.29  1.74    0.00

=== step0_err_corr ===
              seamless_m4t  whisper_v3  canary  conformer  parakeet      sb  cohere
seamless_m4t        1.0000      0.5964  0.6161     0.6072    0.6198  0.5441  0.5400
whisper_v3          0.5964      1.0000  0.6137     0.5985    0.6236  0.5265  0.5666
canary              0.6161      0.6137  1.0000     0.6336    0.7444  0.5804  0.5842
conformer           0.6072      0.5985  0.6336     1.0000    0.6947  0.6515  0.6100
parakeet            0.6198      0.6236  0.7444     0.6947    1.0000  0.6234  0.6282
sb                  0.5441      0.5265  0.5804     0.6515    0.6234  1.0000  0.5721
cohere              0.5400      0.5666  0.5842     0.6100    0.6282  0.5721  1.0000

=== step0_flags ===
                 pair  cross_wer  err_corr                                                            note
0     canary|parakeet       1.27    0.7444  unusually similar hypotheses - suspect shared lab/data/teacher
1       canary|cohere       1.54    0.5842  unusually similar hypotheses - suspect shared lab/data/teacher
2  conformer|parakeet       1.60    0.6947  unusually similar hypotheses - suspect shared lab/data/teacher
3    conformer|cohere       1.60    0.6100  unusually similar hypotheses - suspect shared lab/data/teacher
4     parakeet|cohere       1.29    0.6282  unusually similar hypotheses - suspect shared lab/data/teacher

=== step1_bias ===
          model                  role  n_samples  spearman_full  spearman_loo  kendall_full  kendall_loo  delta_spearman  delta_kendall
0        cohere                 voter       2611         0.4029        0.4275        0.3858       0.4076          0.0246         0.0218
1      parakeet                 voter       2611         0.5876        0.6003        0.5627       0.5739          0.0127         0.0112
2    whisper_v3                 voter       2611         0.6428        0.6729        0.6134       0.6433          0.0301         0.0299
3            sb                 voter       2611         0.6646        0.6828        0.6352       0.6530          0.0182         0.0178
4        canary  ranked_only(control)       2611         0.6737        0.6737        0.6438       0.6438          0.0000         0.0000
5     conformer  ranked_only(control)       2611         0.7172        0.7172        0.6849       0.6849          0.0000         0.0000
6  seamless_m4t                 voter       2611         0.7518        0.7772        0.7175       0.7440          0.0254         0.0265

=== step2_ranking ===
          model         role  n_samples  wer_true  cer_true  wer_pseudo_loo  cer_pseudo_loo  rank_true  rank_pseudo  wer_compression
0        cohere        voter       2611    1.2245    0.3722          1.0833          0.3562          1            1           0.1412
1      parakeet        voter       2611    1.6677    0.4946          1.1573          0.3496          2            2           0.5103
2        canary  ranked_only       2611    1.8912    0.6029          1.2491          0.4156          3            3           0.6420
3     conformer  ranked_only       2611    2.0325    0.5964          1.3179          0.3821          4            4           0.7146
4            sb        voter       2611    2.2063    0.6697          1.6315          0.4992          5            5           0.5749
5  seamless_m4t        voter       2611    2.5693    0.9011          1.9065          0.7159          6            6           0.6628
6    whisper_v3        voter       2611    2.6018    1.3488          2.0014          1.1836          7            7           0.6004

=== step2_stats ===
{
  "n_models": 7,
  "spearman": 1.0,
  "kendall_b": 1.0,
  "spearman_exact_p_onetailed": 0.0001984126984126984,
  "kendall_exact_p_onetailed": 0.0001984126984126984,
  "p_method": "exact",
  "n_permutations": 5040,
  "min_attainable_p": 0.0001984126984126984,
  "pearson": 0.9399785777953488,
  "pearson_p": 0.001641006078654304,
  "mean_wer_compression": 0.5494495883398274
}

=== step3_runs ===
                      run  n_voters  n_samples  filter_fire_rate  tie_rate  refsel_longest_match_validation  refsel_most_common_words
0               full_pool         5       2611            0.4025    0.0031                           0.9360                    0.0640
1  LOO_minus_seamless_m4t         4       2611            0.2827    0.0040                           0.9272                    0.0728
2    LOO_minus_whisper_v3         4       2611            0.3095    0.0047                           0.9207                    0.0793
3      LOO_minus_parakeet         4       2611            0.3275    0.0046                           0.9138                    0.0862
4            LOO_minus_sb         4       2611            0.3052    0.0038                           0.9291                    0.0709
5        LOO_minus_cohere         4       2611            0.3336    0.0048                           0.9180                    0.0820

=== step3_model_dropout ===
          model  times_filtered_out  times_in_pool  filtered_out_rate
0  seamless_m4t                2114          13055             0.1619
3            sb                1499          13055             0.1148
1    whisper_v3                1269          13055             0.0972
2      parakeet                 824          13055             0.0631
4        cohere                 669          13055             0.0512

=== step3_determinism ===
{
  "identical_outputs": 2611,
  "n": 2611,
  "deterministic": true,
  "main_kwargs": {}
}

=== step4_pairs_true ===
                         pair  adjacent  gap_wer  preserved_frac  resolved_95
0   seamless_m4t < whisper_v3      True   0.0325          0.5275        False
1          canary < conformer      True   0.1414          0.9871         True
2              conformer < sb      True   0.1738          0.9965         True
3           parakeet < canary      True   0.2235          1.0000         True
4                 canary < sb     False   0.3152          1.0000         True
5           sb < seamless_m4t      True   0.3629          1.0000         True
6        parakeet < conformer     False   0.3649          1.0000         True
7             sb < whisper_v3     False   0.3954          0.9733         True
8           cohere < parakeet      True   0.4432          1.0000         True
9    conformer < seamless_m4t     False   0.5368          1.0000         True
10              parakeet < sb     False   0.5387          1.0000         True
11     conformer < whisper_v3     False   0.5693          0.9993         True
12            cohere < canary     False   0.6667          1.0000         True
13      canary < seamless_m4t     False   0.6781          1.0000         True
14        canary < whisper_v3     False   0.7106          1.0000         True
15         cohere < conformer     False   0.8080          1.0000         True
16    parakeet < seamless_m4t     False   0.9016          1.0000         True
17      parakeet < whisper_v3     False   0.9341          1.0000         True
18                cohere < sb     False   0.9819          1.0000         True
19      cohere < seamless_m4t     False   1.3448          1.0000         True
20        cohere < whisper_v3     False   1.3773          1.0000         True

=== step4_resolution_true ===
{
  "reference": "true",
  "n_boot": 10000,
  "n_samples": 2611,
  "min_resolved_gap_wer": 0.14135895623603112,
  "max_unresolved_gap_wer": 0.032474354810980266,
  "n_resolved": 20,
  "n_pairs": 21
}

=== step4_pairs_pseudo ===
                         pair  adjacent  gap_wer  preserved_frac  resolved_95
0          canary < conformer      True   0.0688          0.8394        False
1           cohere < parakeet      True   0.0741          0.9308        False
2           parakeet < canary      True   0.0918          0.9434        False
3   seamless_m4t < whisper_v3      True   0.0949          0.6378        False
4        parakeet < conformer     False   0.1606          0.9964         True
5             cohere < canary     False   0.1659          0.9965         True
6          cohere < conformer     False   0.2346          0.9998         True
7           sb < seamless_m4t      True   0.2750          0.9999         True
8              conformer < sb      True   0.3136          1.0000         True
9             sb < whisper_v3     False   0.3699          0.9641         True
10                canary < sb     False   0.3823          1.0000         True
11              parakeet < sb     False   0.4741          1.0000         True
12                cohere < sb     False   0.5482          1.0000         True
13   conformer < seamless_m4t     False   0.5886          1.0000         True
14      canary < seamless_m4t     False   0.6574          1.0000         True
15     conformer < whisper_v3     False   0.6835          1.0000         True
16    parakeet < seamless_m4t     False   0.7492          1.0000         True
17        canary < whisper_v3     False   0.7523          1.0000         True
18      cohere < seamless_m4t     False   0.8232          1.0000         True
19      parakeet < whisper_v3     False   0.8441          1.0000         True
20        cohere < whisper_v3     False   0.9182          1.0000         True

=== step4_resolution_pseudo ===
{
  "reference": "pseudo",
  "n_boot": 10000,
  "n_samples": 2611,
  "min_resolved_gap_wer": 0.1605505911391265,
  "max_unresolved_gap_wer": 0.09490472020582064,
  "n_resolved": 17,
  "n_pairs": 21
}

=== step5_baselines ===
                                        reference  n_models  spearman  kendall_b  spearman_exact_p_onetailed  kendall_exact_p_onetailed p_method  n_permutations  min_attainable_p  mean_abs_wer_err
0                         LOO ensemble (proposed)         7    1.0000     1.0000                      0.0002                     0.0002    exact            5040            0.0002            0.5494
1                          full ensemble (biased)         7    1.0000     1.0000                      0.0002                     0.0002    exact            5040            0.0002            0.7648
2                      single model: seamless_m4t         6    1.0000     1.0000                      0.0014                     0.0014    exact             720            0.0014            0.4404
3   LOO ensemble matched to n-1 (vs seamless_m4t)         6    1.0000     1.0000                      0.0014                     0.0014    exact             720            0.0014            0.5306
4                        single model: whisper_v3         6    1.0000     1.0000                      0.0014                     0.0014    exact             720            0.0014            0.5616
5     LOO ensemble matched to n-1 (vs whisper_v3)         6    1.0000     1.0000                      0.0014                     0.0014    exact             720            0.0014            0.5410
6                          single model: parakeet         6    0.9429     0.8667                      0.0083                     0.0083    exact             720            0.0014            0.3735
7       LOO ensemble matched to n-1 (vs parakeet)         6    1.0000     1.0000                      0.0014                     0.0014    exact             720            0.0014            0.5560
8                                single model: sb         6    0.9429     0.8667                      0.0083                     0.0083    exact             720            0.0014            0.2294
9             LOO ensemble matched to n-1 (vs sb)         6    1.0000     1.0000                      0.0014                     0.0014    exact             720            0.0014            0.5452
10                           single model: cohere         6    1.0000     1.0000                      0.0014                     0.0014    exact             720            0.0014            0.4138
11        LOO ensemble matched to n-1 (vs cohere)         6    1.0000     1.0000                      0.0014                     0.0014    exact             720            0.0014            0.6175

=== step6_pools ===
                                          pool  k  ensemble_wer_vs_true  ensemble_cer_vs_true  ranking_spearman  ranking_exact_p  ranking_kendall_b  ranking_kendall_exact_p  n_pairs_wrong  n_pairs_wrong_resolvable  worst_wrong_gap_wer  worst_wrong_pair
0                           parakeet+sb+cohere  3                1.3162                0.4072               NaN              NaN                NaN                      NaN            NaN                       NaN                  NaN
1                whisper_v3+parakeet+sb+cohere  4                1.3181                0.4220            1.0000           0.0002             1.0000                   0.0002            0.0                       0.0               0.0000
2                   whisper_v3+parakeet+cohere  3                1.3200                0.3968               NaN              NaN                NaN                      NaN            NaN                       NaN                  NaN
3                         whisper_v3+sb+cohere  3                1.3219                0.4047               NaN              NaN                NaN                      NaN            NaN                       NaN                  NaN
4   seamless_m4t+whisper_v3+parakeet+sb+cohere  5                1.3697                0.4155            1.0000           0.0002             1.0000                   0.0002            0.0                       0.0               0.0000
5              seamless_m4t+parakeet+sb+cohere  4                1.3735                0.4372            0.9910           0.0004             0.9759                   0.0004            1.0                       1.0               0.1414  canary|conformer
6                 seamless_m4t+parakeet+cohere  3                1.4002                0.4329               NaN              NaN                NaN                      NaN            NaN                       NaN                  NaN
7      seamless_m4t+whisper_v3+parakeet+cohere  4                1.4021                0.4372            1.0000           0.0002             1.0000                   0.0002            0.0                       0.0               0.0000
8            seamless_m4t+whisper_v3+sb+cohere  4                1.4442                0.4581            0.9286           0.0034             0.8095                   0.0054            2.0                       2.0               0.4432   cohere|parakeet
9                       whisper_v3+parakeet+sb  3                1.4575                0.4574               NaN              NaN                NaN                      NaN            NaN                       NaN                  NaN
10                      seamless_m4t+sb+cohere  3                1.4938                0.4614               NaN              NaN                NaN                      NaN            NaN                       NaN                  NaN
11              seamless_m4t+whisper_v3+cohere  3                1.5263                0.4672               NaN              NaN                NaN                      NaN            NaN                       NaN                  NaN
12         seamless_m4t+whisper_v3+parakeet+sb  4                1.5530                0.4838            1.0000           0.0002             1.0000                   0.0002            0.0                       0.0               0.0000
13            seamless_m4t+whisper_v3+parakeet  3                1.6161                0.5116               NaN              NaN                NaN                      NaN            NaN                       NaN                  NaN
14                    seamless_m4t+parakeet+sb  3                1.6294                0.5069               NaN              NaN                NaN                      NaN            NaN                       NaN                  NaN
15                  seamless_m4t+whisper_v3+sb  3                1.7211                0.5484               NaN              NaN                NaN                      NaN            NaN                       NaN                  NaN

=== step6_contribution ===
  model_removed  delta_ensemble_wer  delta_ranking_spearman  helps_reference_quality  helps_ranking  delta_pairs_wrong  delta_pairs_wrong_resolvable
0  seamless_m4t             -0.0516                  0.0000                    False           True                0.0                           0.0
1    whisper_v3              0.0038                 -0.0090                     True          False                1.0                           1.0
2      parakeet              0.0745                 -0.0714                     True          False                2.0                           2.0
3            sb              0.0325                  0.0000                     True           True                0.0                           0.0
4        cohere              0.1834                  0.0000                     True           True                0.0                           0.0

=== step6_wrong_pairs ===
                                pool  k              pair true_winner pred_winner  wer_true_a  wer_true_b  wer_pseudo_a  wer_pseudo_b  gap_wer_true  gap_wer_pseudo  human_resolvable
0  seamless_m4t+whisper_v3+sb+cohere  4   cohere|parakeet      cohere    parakeet      1.2245      1.6677        1.2377        1.1573        0.4432          0.0804              True
1  seamless_m4t+whisper_v3+sb+cohere  4  canary|conformer      canary   conformer      1.8912      2.0325        1.4133        1.4075        0.1414          0.0057              True
2    seamless_m4t+parakeet+sb+cohere  4  canary|conformer      canary   conformer      1.8912      2.0325        1.3196        1.3196        0.1414          0.0000              True

=== step7_floor ===
          model  frac_zero_wer_samples  kendall_b_all  kendall_b_nonzero  n_nonzero  kendall_b_editdist
0        cohere                 0.8407         0.4076             0.2388        416              0.4175
1      parakeet                 0.7920         0.5739             0.3158        543              0.5928
2        canary                 0.7641         0.6438             0.3266        616              0.6631
3     conformer                 0.7472         0.6849             0.3547        660              0.7031
4    whisper_v3                 0.7465         0.6433             0.3579        662              0.6674
5            sb                 0.7442         0.6530             0.4146        668              0.6751
6  seamless_m4t                 0.6967         0.7440             0.4939        792              0.7603

=== step8_permutation ===
   perm                                       order     n  identical  differing  identical_frac
0     0  cohere+sb+parakeet+whisper_v3+seamless_m4t  2611       2611          0             1.0
1     1  parakeet+cohere+sb+seamless_m4t+whisper_v3  2611       2611          0             1.0
2     2  seamless_m4t+cohere+parakeet+sb+whisper_v3  2611       2611          0             1.0
3     3  cohere+whisper_v3+sb+parakeet+seamless_m4t  2611       2611          0             1.0
4     4  cohere+seamless_m4t+parakeet+sb+whisper_v3  2611       2611          0             1.0

In [15]:
from stt_benchmarking.utils import deployment_protocol as dp
from stt_benchmarking.models.speech_to_text.english import ensemble

importlib.reload(dp)

dp = dp.DeploymentProtocol.from_hypotheses(
    model_samples=dict(zip(model_names, all_models)),
    voters=model_names,
    ensemble_factory=ensemble.HybridEnsemble,
    n_boot=1000, seed=42, min_pool_size=3,
    outdir="deployment_out/librispeech_validated_all_voting_ensemble", suffix="librispeech_validated_all_voting_ensemble")
    
r = dp.run(weighting="filtration")

2026-09-22 17:44:44 - [stt_benchmarking.utils.decorators.execution_time_wrapper:21] INFO - Execution time for function cross_wer: 0 minutes 1 seconds (1.5s)
Fusing Inputs...: 100%|██████████| 2611/2611 [00:06<00:00, 373.37it/s]
Fusing Inputs...: 100%|██████████| 2611/2611 [00:08<00:00, 303.24it/s]
Fusing Inputs...: 100%|██████████| 2611/2611 [00:12<00:00, 213.87it/s]
Fusing Inputs...: 100%|██████████| 2611/2611 [00:12<00:00, 212.00it/s]
Fusing Inputs...: 100%|██████████| 2611/2611 [00:12<00:00, 209.14it/s]
Fusing Inputs...: 100%|██████████| 2611/2611 [00:12<00:00, 212.64it/s]
Fusing Inputs...: 100%|██████████| 2611/2611 [00:12<00:00, 213.08it/s]
2026-09-22 17:46:06 - [stt_benchmarking.utils.decorators.execution_time_wrapper:21] INFO - Execution time for function ranking: 1 minutes 22 seconds (82.3s)
2026-09-22 17:46:06 - [stt_benchmarking.utils.decorators.execution_time_wrapper:21] INFO - Execution time for function ranking: 0 minutes 0 seconds (0.0s)
Fusing Inputs...: 100%|██████████| 2611/2611 [00:07<00:00, 332.75it/s]
Fusing Inputs...: 100%|██████████| 2611/2611 [00:07<00:00, 336.50it/s]
Fusing Inputs...: 100%|██████████| 2611/2611 [00:09<00:00, 263.61it/s]
Fusing Inputs...: 100%|██████████| 2611/2611 [00:08<00:00, 316.79it/s]
Fusing Inputs...: 100%|██████████| 2611/2611 [00:08<00:00, 320.85it/s]
Fusing Inputs...: 100%|██████████| 2611/2611 [00:08<00:00, 323.21it/s]
Fusing Inputs...: 100%|██████████| 2611/2611 [00:10<00:00, 256.69it/s]
Fusing Inputs...: 100%|██████████| 2611/2611 [00:08<00:00, 321.96it/s]
Fusing Inputs...: 100%|██████████| 2611/2611 [00:08<00:00, 325.08it/s]
Fusing Inputs...: 100%|██████████| 2611/2611 [00:08<00:00, 323.32it/s]
Fusing Inputs...: 100%|██████████| 2611/2611 [00:08<00:00, 321.69it/s]
Fusing Inputs...: 100%|██████████| 2611/2611 [00:10<00:00, 254.65it/s]
Fusing Inputs...: 100%|██████████| 2611/2611 [00:07<00:00, 331.58it/s]
Fusing Inputs...: 100%|██████████| 2611/2611 [00:07<00:00, 330.76it/s]
Fusing Inputs...: 100%|██████████| 2611/2611 [00:07<00:00, 333.80it/s]
Fusing Inputs...: 100%|██████████| 2611/2611 [00:08<00:00, 326.21it/s]
Fusing Inputs...: 100%|██████████| 2611/2611 [00:10<00:00, 249.41it/s]
Fusing Inputs...: 100%|██████████| 2611/2611 [00:07<00:00, 326.86it/s]
Fusing Inputs...: 100%|██████████| 2611/2611 [00:08<00:00, 325.68it/s]
Fusing Inputs...: 100%|██████████| 2611/2611 [00:08<00:00, 323.42it/s]
Fusing Inputs...: 100%|██████████| 2611/2611 [00:07<00:00, 326.60it/s]
Fusing Inputs...: 100%|██████████| 2611/2611 [00:07<00:00, 328.34it/s]
Fusing Inputs...: 100%|██████████| 2611/2611 [00:10<00:00, 237.42it/s]
Fusing Inputs...: 100%|██████████| 2611/2611 [00:08<00:00, 320.46it/s]
Fusing Inputs...: 100%|██████████| 2611/2611 [00:05<00:00, 437.01it/s]
Fusing Inputs...: 100%|██████████| 2611/2611 [00:04<00:00, 628.48it/s]
Fusing Inputs...: 100%|██████████| 2611/2611 [00:04<00:00, 632.59it/s]
Fusing Inputs...: 100%|██████████| 2611/2611 [00:04<00:00, 559.26it/s]
Fusing Inputs...: 100%|██████████| 2611/2611 [00:11<00:00, 231.42it/s]
Fusing Inputs...: 100%|██████████| 2611/2611 [00:07<00:00, 332.74it/s]
Fusing Inputs...: 100%|██████████| 2611/2611 [00:07<00:00, 330.87it/s]
Fusing Inputs...: 100%|██████████| 2611/2611 [00:07<00:00, 332.82it/s]
Fusing Inputs...: 100%|██████████| 2611/2611 [00:07<00:00, 333.42it/s]
Fusing Inputs...: 100%|██████████| 2611/2611 [00:07<00:00, 331.21it/s]
Fusing Inputs...: 100%|██████████| 2611/2611 [00:08<00:00, 321.84it/s]
Fusing Inputs...: 100%|██████████| 2611/2611 [00:13<00:00, 190.30it/s]
Fusing Inputs...: 100%|██████████| 2611/2611 [00:09<00:00, 262.51it/s]
Fusing Inputs...: 100%|██████████| 2611/2611 [00:09<00:00, 263.40it/s]
Fusing Inputs...: 100%|██████████| 2611/2611 [00:10<00:00, 258.24it/s]
Fusing Inputs...: 100%|██████████| 2611/2611 [00:09<00:00, 261.98it/s]
Fusing Inputs...: 100%|██████████| 2611/2611 [00:09<00:00, 262.76it/s]
Fusing Inputs...: 100%|██████████| 2611/2611 [00:09<00:00, 261.93it/s]
Fusing Inputs...: 100%|██████████| 2611/2611 [00:10<00:00, 259.24it/s]
Fusing Inputs...: 100%|██████████| 2611/2611 [00:10<00:00, 239.08it/s]
Fusing Inputs...: 100%|██████████| 2611/2611 [00:09<00:00, 271.54it/s]
Fusing Inputs...: 100%|██████████| 2611/2611 [00:09<00:00, 269.54it/s]
Fusing Inputs...: 100%|██████████| 2611/2611 [00:09<00:00, 271.41it/s]
Fusing Inputs...: 100%|██████████| 2611/2611 [00:09<00:00, 270.66it/s]
Fusing Inputs...: 100%|██████████| 2611/2611 [00:09<00:00, 272.26it/s]
Fusing Inputs...: 100%|██████████| 2611/2611 [00:09<00:00, 272.32it/s]
Fusing Inputs...: 100%|██████████| 2611/2611 [00:09<00:00, 268.70it/s]
Fusing Inputs...: 100%|██████████| 2611/2611 [00:09<00:00, 271.31it/s]
Fusing Inputs...: 100%|██████████| 2611/2611 [00:09<00:00, 269.50it/s]
Fusing Inputs...: 100%|██████████| 2611/2611 [00:09<00:00, 274.24it/s]
Fusing Inputs...: 100%|██████████| 2611/2611 [00:09<00:00, 266.97it/s]
Fusing Inputs...: 100%|██████████| 2611/2611 [00:09<00:00, 270.27it/s]
Fusing Inputs...: 100%|██████████| 2611/2611 [00:14<00:00, 178.65it/s]
2026-09-22 17:54:44 - [stt_benchmarking.utils.decorators.execution_time_wrapper:21] INFO - Execution time for function model_filtration: 8 minutes 38 seconds (518.4s)
Fusing Inputs...: 100%|██████████| 2611/2611 [00:02<00:00, 1107.65it/s]
Fusing Inputs...: 100%|██████████| 2611/2611 [00:01<00:00, 1574.84it/s]
Fusing Inputs...: 100%|██████████| 2611/2611 [00:02<00:00, 899.66it/s]
Fusing Inputs...: 100%|██████████| 2611/2611 [00:02<00:00, 903.70it/s]
Fusing Inputs...: 100%|██████████| 2611/2611 [00:02<00:00, 923.51it/s]
Fusing Inputs...: 100%|██████████| 2611/2611 [00:02<00:00, 1132.24it/s]
Fusing Inputs...: 100%|██████████| 2611/2611 [00:02<00:00, 984.55it/s]
Fusing Inputs...: 100%|██████████| 2611/2611 [00:02<00:00, 905.96it/s]
Fusing Inputs...: 100%|██████████| 2611/2611 [00:02<00:00, 891.74it/s]
Fusing Inputs...: 100%|██████████| 2611/2611 [00:02<00:00, 894.40it/s]
Fusing Inputs...: 100%|██████████| 2611/2611 [00:02<00:00, 914.43it/s]
Fusing Inputs...: 100%|██████████| 2611/2611 [00:02<00:00, 1063.15it/s]
Fusing Inputs...: 100%|██████████| 2611/2611 [00:02<00:00, 962.59it/s]
Fusing Inputs...: 100%|██████████| 2611/2611 [00:02<00:00, 906.30it/s]
Fusing Inputs...: 100%|██████████| 2611/2611 [00:02<00:00, 891.98it/s]
Fusing Inputs...: 100%|██████████| 2611/2611 [00:02<00:00, 906.09it/s]
Fusing Inputs...: 100%|██████████| 2611/2611 [00:02<00:00, 922.01it/s]
Fusing Inputs...: 100%|██████████| 2611/2611 [00:02<00:00, 890.69it/s]
Fusing Inputs...: 100%|██████████| 2611/2611 [00:02<00:00, 883.65it/s]
Fusing Inputs...: 100%|██████████| 2611/2611 [00:02<00:00, 1066.36it/s]
Fusing Inputs...: 100%|██████████| 2611/2611 [00:02<00:00, 916.39it/s]
Fusing Inputs...: 100%|██████████| 2611/2611 [00:02<00:00, 942.22it/s]
Fusing Inputs...: 100%|██████████| 2611/2611 [00:02<00:00, 1117.41it/s]
Fusing Inputs...: 100%|██████████| 2611/2611 [00:02<00:00, 931.24it/s]
Fusing Inputs...: 100%|██████████| 2611/2611 [00:01<00:00, 1370.73it/s]
Fusing Inputs...: 100%|██████████| 2611/2611 [00:02<00:00, 918.39it/s]
Fusing Inputs...: 100%|██████████| 2611/2611 [00:02<00:00, 895.59it/s]
Fusing Inputs...: 100%|██████████| 2611/2611 [00:02<00:00, 941.86it/s]
Fusing Inputs...: 100%|██████████| 2611/2611 [00:09<00:00, 264.99it/s]
Fusing Inputs...: 100%|██████████| 2611/2611 [00:03<00:00, 771.82it/s]
Fusing Inputs...: 100%|██████████| 2611/2611 [00:03<00:00, 806.57it/s]
Fusing Inputs...: 100%|██████████| 2611/2611 [00:02<00:00, 893.85it/s]
Fusing Inputs...: 100%|██████████| 2611/2611 [00:02<00:00, 958.79it/s]
Fusing Inputs...: 100%|██████████| 2611/2611 [00:02<00:00, 1166.91it/s]
Fusing Inputs...: 100%|██████████| 2611/2611 [00:01<00:00, 1624.63it/s]
2026-09-22 17:57:29 - [stt_benchmarking.utils.deployment_protocol.rank_distribution:498] INFO - Rank distribution finished.
2026-09-22 17:57:29 - [stt_benchmarking.utils.decorators.execution_time_wrapper:21] INFO - Execution time for function rank_distribution: 11 minutes 23 seconds (683.5s)
2026-09-22 17:57:29 - [stt_benchmarking.utils.deployment_protocol.run:509] INFO - Deployment protocol finished.
2026-09-22 17:57:29 - [stt_benchmarking.utils.decorators.execution_time_wrapper:21] INFO - Execution time for function run: 12 minutes 47 seconds (767.2s)

In [14]:
from stt_benchmarking.utils import deployment_protocol as dp
from stt_benchmarking.models.speech_to_text.english import ensemble

dp = dp.DeploymentProtocol.from_hypotheses(
    model_samples={n: s for n, s in zip(model_names, all_models) if n in voters},
    voters=voters,
    ensemble_factory=ensemble.HybridEnsemble,
    n_boot=1000, seed=42, min_pool_size=3,
    outdir="deployment_out/librispeech_validated_voters_ensemble", suffix="librispeech_validated_voters_ensemble")

r = dp.run(weighting="filtration")

2026-09-22 17:43:37 - [stt_benchmarking.utils.decorators.execution_time_wrapper:21] INFO - Execution time for function cross_wer: 0 minutes 0 seconds (0.7s)
Fusing Inputs...: 100%|██████████| 2611/2611 [00:04<00:00, 529.62it/s]
Fusing Inputs...: 100%|██████████| 2611/2611 [00:04<00:00, 624.49it/s]
Fusing Inputs...: 100%|██████████| 2611/2611 [00:04<00:00, 618.52it/s]
Fusing Inputs...: 100%|██████████| 2611/2611 [00:04<00:00, 526.20it/s]
Fusing Inputs...: 100%|██████████| 2611/2611 [00:04<00:00, 635.05it/s]
2026-09-22 17:44:00 - [stt_benchmarking.utils.decorators.execution_time_wrapper:21] INFO - Execution time for function ranking: 0 minutes 23 seconds (23.2s)
2026-09-22 17:44:00 - [stt_benchmarking.utils.decorators.execution_time_wrapper:21] INFO - Execution time for function ranking: 0 minutes 0 seconds (0.0s)
Fusing Inputs...: 100%|██████████| 2611/2611 [00:05<00:00, 519.44it/s]
2026-09-22 17:44:06 - [stt_benchmarking.utils.decorators.execution_time_wrapper:21] INFO - Execution time for function model_filtration: 0 minutes 5 seconds (5.1s)
Fusing Inputs...: 100%|██████████| 2611/2611 [00:02<00:00, 1063.99it/s]
Fusing Inputs...: 100%|██████████| 2611/2611 [00:01<00:00, 1608.06it/s]
Fusing Inputs...: 100%|██████████| 2611/2611 [00:01<00:00, 1608.43it/s]
Fusing Inputs...: 100%|██████████| 2611/2611 [00:01<00:00, 1633.54it/s]
Fusing Inputs...: 100%|██████████| 2611/2611 [00:02<00:00, 1017.59it/s]
Fusing Inputs...: 100%|██████████| 2611/2611 [00:01<00:00, 1609.28it/s]
Fusing Inputs...: 100%|██████████| 2611/2611 [00:01<00:00, 1626.26it/s]
Fusing Inputs...: 100%|██████████| 2611/2611 [00:01<00:00, 1610.76it/s]
Fusing Inputs...: 100%|██████████| 2611/2611 [00:02<00:00, 951.10it/s]
Fusing Inputs...: 100%|██████████| 2611/2611 [00:01<00:00, 1610.98it/s]
2026-09-22 17:44:28 - [stt_benchmarking.utils.deployment_protocol.rank_distribution:498] INFO - Rank distribution finished.
2026-09-22 17:44:28 - [stt_benchmarking.utils.decorators.execution_time_wrapper:21] INFO - Execution time for function rank_distribution: 0 minutes 27 seconds (27.0s)
2026-09-22 17:44:28 - [stt_benchmarking.utils.deployment_protocol.run:509] INFO - Deployment protocol finished.
2026-09-22 17:44:28 - [stt_benchmarking.utils.decorators.execution_time_wrapper:21] INFO - Execution time for function run: 0 minutes 51 seconds (51.0s)

### Uniofmr Rank Distribution - Ensemble Deployment Protocol

In [12]:
from stt_benchmarking.utils import deployment_protocol as dp
from stt_benchmarking.models.speech_to_text.english import ensemble

importlib.reload(dp)

dp = dp.DeploymentProtocol.from_hypotheses(
    model_samples={n: s for n, s in zip(model_names, all_models) if n in voters},
    voters=voters,
    ensemble_factory=ensemble.HybridEnsemble,
    n_boot=1000, seed=42, min_pool_size=3,
    outdir="deployment_out/librispeech_validated_voters_unweighted_ensemble", suffix="librispeech_validated_voters_unweighted_ensemble")

rep = dp.run(weighting="uniform")

2026-09-22 22:30:11 - [stt_benchmarking.utils.decorators.execution_time_wrapper:21] INFO - Execution time for function cross_wer: 0 minutes 1 seconds (1.6s)
Fusing Inputs...: 100%|██████████| 2611/2611 [00:08<00:00, 320.61it/s]
Fusing Inputs...: 100%|██████████| 2611/2611 [00:08<00:00, 317.19it/s]
Fusing Inputs...: 100%|██████████| 2611/2611 [00:08<00:00, 312.44it/s]
Fusing Inputs...: 100%|██████████| 2611/2611 [00:08<00:00, 311.59it/s]
Fusing Inputs...: 100%|██████████| 2611/2611 [00:08<00:00, 311.31it/s]
2026-09-22 22:30:55 - [stt_benchmarking.utils.decorators.execution_time_wrapper:21] INFO - Execution time for function ranking: 0 minutes 43 seconds (43.5s)
2026-09-22 22:30:55 - [stt_benchmarking.utils.decorators.execution_time_wrapper:21] INFO - Execution time for function ranking: 0 minutes 0 seconds (0.0s)
Fusing Inputs...: 100%|██████████| 2611/2611 [00:02<00:00, 1094.41it/s]
Fusing Inputs...: 100%|██████████| 2611/2611 [00:03<00:00, 851.58it/s]
Fusing Inputs...: 100%|██████████| 2611/2611 [00:03<00:00, 730.51it/s]
Fusing Inputs...: 100%|██████████| 2611/2611 [00:02<00:00, 1107.87it/s]
Fusing Inputs...: 100%|██████████| 2611/2611 [00:02<00:00, 897.14it/s]
Fusing Inputs...: 100%|██████████| 2611/2611 [00:03<00:00, 695.18it/s]
Fusing Inputs...: 100%|██████████| 2611/2611 [00:02<00:00, 874.20it/s]
Fusing Inputs...: 100%|██████████| 2611/2611 [00:03<00:00, 762.75it/s]
Fusing Inputs...: 100%|██████████| 2611/2611 [00:02<00:00, 881.16it/s]
Fusing Inputs...: 100%|██████████| 2611/2611 [00:03<00:00, 869.61it/s]
2026-09-22 22:31:33 - [stt_benchmarking.utils.deployment_protocol.rank_distribution:498] INFO - Rank distribution finished.
2026-09-22 22:31:33 - [stt_benchmarking.utils.decorators.execution_time_wrapper:21] INFO - Execution time for function rank_distribution: 0 minutes 38 seconds (38.7s)
2026-09-22 22:31:33 - [stt_benchmarking.utils.deployment_protocol.run:509] INFO - Deployment protocol finished.
2026-09-22 22:31:33 - [stt_benchmarking.utils.decorators.execution_time_wrapper:21] INFO - Execution time for function run: 1 minutes 23 seconds (83.9s)

## ROVER

In [12]:
from stt_benchmarking.models.speech_to_text.english import rover
importlib.reload(rover)

ROVEROBJECT = rover.ROVER()
ROVEROBJECT.combine_models_transcriptions(
    seamless_samples,
    whisper_samples,
    parakeet_samples,
    sb_samples,
    cohere_samples
)
ROVEROBJECT.main()
ROVEROBJECT.eval(filtered_records)
rover_samples = ROVEROBJECT.fusion_results
ROVEROBJECT.overall_metrics

ROVER Fusion...: 100%|██████████| 2611/2611 [00:05<00:00, 515.19it/s]

{'word_error_rate': {'wer (%)': 1.38,
  'word_similarity_ratio (%)': 99.31,
  'word_edit_distance': 721,
  'substitutions': 534,
  'deletions': 78,
  'insertions': 109,
  'hits': 51737,
  'ref_length': 52349,
  'hyp_length': 52380},
 'character_error_rate': {'cer (%)': 0.42,
  'char_similarity_ratio (%)': 99.79,
  'char_edit_distance': 1162,
  'substitutions': 377,
  'deletions': 374,
  'insertions': 411,
  'hits': 276242,
  'ref_length': 276993,
  'hyp_length': 277030}}

In [1]:
ROVEROBJECT.fusion_wall_time

NameError: name 'ROVEROBJECT' is not defined

## Ensemble

In [12]:
from stt_benchmarking.models.speech_to_text.english import ensemble
importlib.reload(ensemble)

ENSEMBLE_OBJ = ensemble.HybridEnsemble()
ENSEMBLE_OBJ.combine_models_transcriptions(
    seamless_samples,
    whisper_samples,
    parakeet_samples,
    sb_samples,
    cohere_samples
)
ENSEMBLE_OBJ.main()
ENSEMBLE_OBJ.eval(filtered_records)
ensemble_samples = ENSEMBLE_OBJ.samples_info
ENSEMBLE_OBJ.overall_metrics

Fusing Inputs...: 100%|██████████| 2611/2611 [00:06<00:00, 403.51it/s]

{'word_error_rate': {'wer (%)': 1.37,
  'word_similarity_ratio (%)': 99.32,
  'word_edit_distance': 717,
  'substitutions': 534,
  'deletions': 87,
  'insertions': 96,
  'hits': 51728,
  'ref_length': 52349,
  'hyp_length': 52358},
 'character_error_rate': {'cer (%)': 0.41,
  'char_similarity_ratio (%)': 99.79,
  'char_edit_distance': 1142,
  'substitutions': 370,
  'deletions': 419,
  'insertions': 353,
  'hits': 276204,
  'ref_length': 276993,
  'hyp_length': 276927}}

In [13]:
ENSEMBLE_OBJ.fusion_wall_time

6.596327543258667

In [14]:
model_dicts = {
    "seamless_m4t": seamless_samples,
    "whisper_v3": whisper_samples,
    "parakeet": parakeet_samples,
    "sb": sb_samples,
    "cohere": cohere_samples,
}
disp = {
    "seamless_m4t": "SeamlessM4T v2",
    "whisper_v3": "Whisper large-v3",
    "parakeet": "Parakeet",
    "sb": "SpeechBrain",
    "cohere": "Cohere Transcribe",
}
assert set(model_dicts) == set(voters) == set(disp), (set(model_dicts), set(voters), set(disp))

In [15]:
def wer_of(samples, path):
    m = samples.get(path, {}).get("metrics")
    if not m: return None
    return m["word_error_rate"]["wer (%)"]

In [16]:
rows = []
for path in ensemble_samples:
    ens_wer = wer_of(ensemble_samples, path)
    if ens_wer is None: continue
    sys_wers = {n: wer_of(d, path) for n, d in model_dicts.items()}
    sys_wers = {n: w for n, w in sys_wers.items() if w is not None}
    if not sys_wers: continue
    best_single = min(sys_wers.values())
    margin = best_single - ens_wer
    ref = ensemble_samples[path].get("normalized_transcription", "")
    n_words = len(ref.split())
    md = ensemble_samples[path]["metadata"]
    n_filtered = md["records_filtration"].get("num_filtered", 0)
    n_ties = sum(
        1 for vd in md["voting"]["voting_details"]
        if vd.get("token_votes") and
        sorted(vd["token_votes"].values())[-1] == (sorted(vd["token_votes"].values())[-2] if len(vd["token_votes"])>1 else -1)
    )
    rows.append({"path": path, "ens_wer": round(ens_wer,2), "best_single": round(best_single,2),
                 "margin": round(margin,2), "n_words": n_words, "n_filtered": n_filtered,
                 "n_ties": n_ties, "strategy": md["reference_selection"].get("strategy_metric")})

cand = [r for r in rows if r["margin"] > 0 and 5 <= r["n_words"] <= 12]
cand.sort(key=lambda r: (r["n_filtered"]>0, r["n_ties"]>0, r["margin"]), reverse=True)

for r in cand[:15]: 
    print(r)

In [17]:
print("rows:", len(rows))
if rows:
    import statistics
    print("n_words range:", min(r["n_words"] for r in rows), "-", max(r["n_words"] for r in rows))
    print("margin>0 count:", sum(1 for r in rows if r["margin"] > 0))
    print("n_words 5-12 count:", sum(1 for r in rows if 5 <= r["n_words"] <= 12))
print("cand:", len(cand))

rows: 2611
n_words range: 1 - 87
margin>0 count: 2
n_words 5-12 count: 851
cand: 0

In [18]:
print(ensemble_samples[list(ensemble_samples)[0]]["normalized_prediction"])
print(ensemble_samples[list(ensemble_samples)[0]]["normalized_transcription"])

he hoped there would be stew for dinner turnips and carrots and bruised potatoes and fat mutton pieces to be ladled out in thick peppered flour fattened sauce
he hoped there would be stew for dinner turnips and carrots and bruised potatoes and fat mutton pieces to be ladled out in thick peppered flour fattened sauce

In [21]:
cand = sorted(rows, key=lambda r: (-r["margin"], -(r["n_filtered"]>0), -(r["n_ties"]>0)))
cand = [r for r in cand if 5 <= r["n_words"] <= 25][:15]
for r in cand: print(r)

{'path': '../../data/librispeech/LibriSpeech/test-clean\\2094\\142345\\2094-142345-0028.flac', 'ens_wer': 0.0, 'best_single': 6.25, 'margin': 6.25, 'n_words': 16, 'n_filtered': 2, 'n_ties': 1, 'strategy': 'most_common_words'}
{'path': '../../data/librispeech/LibriSpeech/test-clean\\1089\\134691\\1089-134691-0010.flac', 'ens_wer': 60.0, 'best_single': 60.0, 'margin': 0.0, 'n_words': 5, 'n_filtered': 1, 'n_ties': 2, 'strategy': 'most_common_words'}
{'path': '../../data/librispeech/LibriSpeech/test-clean\\1580\\141083\\1580-141083-0018.flac', 'ens_wer': 0.0, 'best_single': 0.0, 'margin': 0.0, 'n_words': 6, 'n_filtered': 1, 'n_ties': 1, 'strategy': 'most_common_words'}
{'path': '../../data/librispeech/LibriSpeech/test-clean\\1995\\1837\\1995-1837-0016.flac', 'ens_wer': 0.0, 'best_single': 0.0, 'margin': 0.0, 'n_words': 17, 'n_filtered': 1, 'n_ties': 1, 'strategy': 'most_common_words'}
{'path': '../../data/librispeech/LibriSpeech/test-clean\\237\\126133\\237-126133-0016.flac', 'ens_wer': 9.09, 'best_single': 9.09, 'margin': 0.0, 'n_words': 11, 'n_filtered': 2, 'n_ties': 1, 'strategy': 'most_common_words'}
{'path': '../../data/librispeech/LibriSpeech/test-clean\\3575\\170457\\3575-170457-0005.flac', 'ens_wer': 9.09, 'best_single': 9.09, 'margin': 0.0, 'n_words': 22, 'n_filtered': 1, 'n_ties': 1, 'strategy': 'most_common_words'}
{'path': '../../data/librispeech/LibriSpeech/test-clean\\3729\\6852\\3729-6852-0043.flac', 'ens_wer': 22.22, 'best_single': 22.22, 'margin': 0.0, 'n_words': 9, 'n_filtered': 2, 'n_ties': 1, 'strategy': 'longest_match_validation'}
{'path': '../../data/librispeech/LibriSpeech/test-clean\\4507\\16021\\4507-16021-0022.flac', 'ens_wer': 7.14, 'best_single': 7.14, 'margin': 0.0, 'n_words': 14, 'n_filtered': 2, 'n_ties': 1, 'strategy': 'longest_match_validation'}
{'path': '../../data/librispeech/LibriSpeech/test-clean\\4992\\41797\\4992-41797-0002.flac', 'ens_wer': 0.0, 'best_single': 0.0, 'margin': 0.0, 'n_words': 12, 'n_filtered': 1, 'n_ties': 2, 'strategy': 'most_common_words'}
{'path': '../../data/librispeech/LibriSpeech/test-clean\\5142\\33396\\5142-33396-0006.flac', 'ens_wer': 0.0, 'best_single': 0.0, 'margin': 0.0, 'n_words': 22, 'n_filtered': 1, 'n_ties': 1, 'strategy': 'most_common_words'}
{'path': '../../data/librispeech/LibriSpeech/test-clean\\5639\\40744\\5639-40744-0006.flac', 'ens_wer': 5.26, 'best_single': 5.26, 'margin': 0.0, 'n_words': 19, 'n_filtered': 1, 'n_ties': 1, 'strategy': 'most_common_words'}
{'path': '../../data/librispeech/LibriSpeech/test-clean\\5683\\32865\\5683-32865-0005.flac', 'ens_wer': 0.0, 'best_single': 0.0, 'margin': 0.0, 'n_words': 22, 'n_filtered': 1, 'n_ties': 1, 'strategy': 'most_common_words'}
{'path': '../../data/librispeech/LibriSpeech/test-clean\\5683\\32865\\5683-32865-0007.flac', 'ens_wer': 0.0, 'best_single': 0.0, 'margin': 0.0, 'n_words': 15, 'n_filtered': 1, 'n_ties': 1, 'strategy': 'most_common_words'}
{'path': '../../data/librispeech/LibriSpeech/test-clean\\7127\\75947\\7127-75947-0021.flac', 'ens_wer': 22.22, 'best_single': 22.22, 'margin': 0.0, 'n_words': 9, 'n_filtered': 1, 'n_ties': 2, 'strategy': 'most_common_words'}
{'path': '../../data/librispeech/LibriSpeech/test-clean\\7127\\75947\\7127-75947-0026.flac', 'ens_wer': 12.5, 'best_single': 12.5, 'margin': 0.0, 'n_words': 16, 'n_filtered': 1, 'n_ties': 1, 'strategy': 'most_common_words'}

In [27]:
from stt_benchmarking.utils import ensemble_analysis
importlib.reload(ensemble_analysis)

fp=ensemble_analysis.download_amiri("fonts")     # OFL, one-time; returns Amiri-Regular.ttf
AUDIO_ID = "../../data/librispeech/LibriSpeech/test-clean\\2094\\142345\\2094-142345-0028.flac"
ensemble_analysis.render_stages(AUDIO_ID, ensemble_samples, model_dicts, voters, disp,
    ensemble_name="Proposed ensemble", fig_dir="figures_librespeech",
    font_path=fp, max_tokens=16, col_chunk=16)

font: fonts\Amiri-Regular.ttf

TSIV NOT subset; don't know how to subset; dropped

saved: figures_librespeech\stage0_reference.pdf | figures_librespeech\stage0_reference.png

TSIV NOT subset; don't know how to subset; dropped
TSIV NOT subset; don't know how to subset; dropped

saved: figures_librespeech\stage1_filtration.pdf | figures_librespeech\stage1_filtration.png
saved: figures_librespeech\stage2_reference_selection.pdf | figures_librespeech\stage2_reference_selection.png

TSIV NOT subset; don't know how to subset; dropped

saved: figures_librespeech\stage3_alignment.pdf | figures_librespeech\stage3_alignment.png

TSIV NOT subset; don't know how to subset; dropped

saved: figures_librespeech\stage4_voting.pdf | figures_librespeech\stage4_voting.png

TSIV NOT subset; don't know how to subset; dropped

saved: figures_librespeech\stage5_comparison.pdf | figures_librespeech\stage5_comparison.png

['figures_librespeech\\stage0_reference.pdf',
 'figures_librespeech\\stage0_reference.png',
 'figures_librespeech\\stage1_filtration.pdf',
 'figures_librespeech\\stage1_filtration.png',
 'figures_librespeech\\stage2_reference_selection.pdf',
 'figures_librespeech\\stage2_reference_selection.png',
 'figures_librespeech\\stage3_alignment.pdf',
 'figures_librespeech\\stage3_alignment.png',
 'figures_librespeech\\stage4_voting.pdf',
 'figures_librespeech\\stage4_voting.png',
 'figures_librespeech\\stage5_comparison.pdf',
 'figures_librespeech\\stage5_comparison.png']

In [14]:
all_models.append(rover_samples)
model_names.append("rover")

all_models.append(ensemble_samples)
model_names.append("ensemble")

In [15]:
models_with_names = list(zip(model_names, all_models))
df_full = collect_model_metrics(models_with_names)
df_filtered_full = filter_audio_records(df_full)

Audios dropped (empty ground truth): 0
Audios dropped (empty ensemble): 0
Audios: 2611 -> 2611

In [16]:
df_full_eval = evaluate_absolute_metrics(df_filtered_full)
df_full_eval[["model", "WER (%)", "CER (%)", "rtf_mean", "inference_time_total_h", "fusion_time_mean"]]

,model,WER (%),CER (%),rtf_mean,inference_time_total_h,fusion_time_mean
0,cohere,1.22,0.37,0.040616,0.182711,NaN
1,ensemble,1.37,0.41,NaN,0.015430,0.021274
2,rover,1.38,0.42,NaN,0.012156,0.016760
3,parakeet,1.67,0.49,0.009393,0.037694,NaN
4,canary,1.89,0.60,0.040443,0.191791,NaN
5,conformer,2.03,0.60,0.009641,0.036378,NaN
6,sb,2.21,0.67,0.176632,1.267476,NaN
7,seamless_m4t,2.57,0.90,0.137370,0.796933,NaN
8,whisper_v3,2.60,1.35,0.138758,0.642775,NaN

In [20]:
df_relative_ensemble = evaluate_relative_metrics(df_filtered_full, "ensemble", exclude_models=["rover", "hybrid_ensemble"])
df_relative_ensemble[["model", "WER (%)", "CER (%)"]]

          model  WER (%)  CER (%)
0      ensemble     0.00     0.00
1        cohere     0.75     0.24
2      parakeet     0.83     0.24
3        canary     1.25     0.41
4     conformer     1.32     0.38
5            sb     1.35     0.41
6  seamless_m4t     1.65     0.62
7    whisper_v3     1.70     1.08

# END

In [30]:
# ---- Option B: headline ranking correlation (reference order vs pseudo-reference order) ----
merged_B, coeffs_B = ranking_correlation(df_full_eval, df_relative_ensemble)
print("=== Option B: pooled system-ranking correlation (ensemble as pseudo-reference) ===")
print(merged_B.to_string(index=False))
print(coeffs_B)

# ---- Option A: per-sample pseudo-WER tracking (NoRefER analogue) ----
df_ps = add_pseudo_reference_wer(df_filtered_full, ensemble_samples)
corr_A = per_sample_correlation(df_ps)
corr_A.to_csv("../../reports/phase_1_4/metrics/relative/librespeech/per_sample_correlation_cohere.csv", index=False)
print("\n=== Option A: per-sample WER tracking (per-model + pooled) ===")
print(corr_A.to_string(index=False))

=== Option B: pooled system-ranking correlation (ensemble as pseudo-reference) ===
       model  wer_abs  wer_rel
      cohere     1.26     0.77
    parakeet     1.69     0.83
      canary     1.92     1.27
   conformer     2.06     1.33
          sb     2.23     1.36
  whisper_v3     2.63     1.71
seamless_m4t     2.69     1.77
{'pearson': 0.9707799291244992, 'pearson_p': 0.00027594632496072164, 'spearman': 1.0, 'spearman_p': 0.0, 'kendall': 1.0, 'kendall_p': 0.0003968253968253968}

=== Option A: per-sample WER tracking (per-model + pooled) ===
       model     n  pearson     pearson_p  spearman    spearman_p  kendall     kendall_p
seamless_m4t  2620 0.885930  0.000000e+00  0.754591  0.000000e+00 0.719971  0.000000e+00
   conformer  2620 0.763584  0.000000e+00  0.718475  0.000000e+00 0.685742  0.000000e+00
      canary  2620 0.528124 3.750476e-188  0.673913  0.000000e+00 0.643661 1.283233e-290
          sb  2620 0.575403 6.913579e-231  0.665267  0.000000e+00 0.635745 1.233749e-286
ALL (pooled) 18340 0.718155  0.000000e+00  0.654831  0.000000e+00 0.625458  0.000000e+00
  whisper_v3  2620 0.780288  0.000000e+00  0.645752 4.441861e-309 0.615448 3.237264e-267
    parakeet  2620 0.647534 2.478602e-311  0.589346 7.203300e-245 0.564024 3.178033e-214
      cohere  2620 0.522380 2.070782e-183  0.411203 1.886227e-107 0.393540 9.259513e-103

In [17]:
df_full_rel_rover = evaluate_relative_metrics(df_full, "rover", exclude_models=["ensemble", "rover"])
df_full_rel_ensemble = evaluate_relative_metrics(df_full, "ensemble", exclude_models=["rover", "ensemble"])

In [18]:
df_full_rel_ensemble[["model", "WER (%)", "CER (%)"]]

          model  WER (%)  CER (%)
0      parakeet     0.79     0.24
1        cohere     0.82     0.27
2        canary     1.09     0.37
3     conformer     1.20     0.36
4            sb     1.41     0.44
5    whisper_v2     1.80     0.79
6  seamless_m4t     1.82     0.74
7    whisper_v3     1.92     1.25

In [ ]:
df_full_rel_ensemble[["model", "WER (%)", "CER (%)"]]

          model  WER (%)  CER (%)
0      parakeet     0.78     0.24
1        canary     1.06     0.37
2     conformer     1.17     0.34
3            sb     1.42     0.43
4  seamless_m4t     1.77     0.71
5    whisper_v2     1.79     0.78
6    whisper_v3     1.92     1.24