In [1]:
import sys
import importlib
import warnings
import random
from collections import defaultdict
import pickle
import os
import re

import torch
from tqdm import tqdm
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns


sys.path.append("A:/Masters/Thesis/Dr. Mohsen Rashwan/projects/")

from stt_benchmarking.utils import helpers, text_processing, metrics as mt, validate
from stt_benchmarking.etl import load_data
from stt_benchmarking.models.speech_to_text.arabic import ensemble, rover
from stt_benchmarking.models.llms import reinforcer



warnings.filterwarnings('ignore')
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
pd.set_option("display.max_colwidth", None)
random.seed(42)

print(device)

e:\Masters\Thesis\Dr. Mohsen Rashwan\projects\.venv\lib\site-packages\torch\backends\__init__.py:46: UserWarning: Please use the new API settings to control TF32 behavior, such as torch.backends.cudnn.conv.fp32_precision = 'tf32' or torch.backends.cuda.matmul.fp32_precision = 'ieee'. Old settings, e.g, torch.backends.cuda.matmul.allow_tf32 = True, torch.backends.cudnn.allow_tf32 = True, allowTF32CuDNN() and allowTF32CuBLAS() will be deprecated after Pytorch 2.9. Please see https://pytorch.org/docs/main/notes/cuda.html#tensorfloat-32-tf32-on-ampere-and-later-devices (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\Context.cpp:85.)
  self.setter(val)

cuda

In [ ]:
test_cv_path = "../../data/mozilla_commonvoice/cv-corpus/ar/test.tsv"
audio_paths = "../../data/mozilla_commonvoice/cv-corpus/ar/clips"
test_df = pd.read_csv(test_cv_path, sep="\t")

In [2]:
cv_audios = load_data.load_mozilla_cv(df=test_df, audio_path=audio_paths)

NameError: name 'test_df' is not defined

In [2]:
def save_bootstrap_samples(samples, filepath="../../reports/phase_1_4/lists_info/mozilla_cv/bootstrap_samples.pkl"):
    os.makedirs(os.path.dirname(filepath), exist_ok=True)
    with open(filepath, 'wb') as f:
        pickle.dump(samples, f)

def load_bootstrap_samples(filepath="../../reports/phase_1_4/lists_info/mozilla_cv/bootstrap_samples.pkl"):
    with open(filepath, 'rb') as f:
        return pickle.load(f)

In [5]:
save_bootstrap_samples(cv_audios, filepath="../../reports/phase_1_4/lists_info/mozilla_cv/cv_audios.pkl")

In [3]:
cv_audios = load_bootstrap_samples("../../results/mozilla_common_voice/audios/cv_audios.pkl")

# Models

In [4]:
import json
import inspect
import os

def save_model_info(obj, attr_name="samples_info", save_dir="../../reports/phase_1_4/models_info/mozilla_cv", is_llm=False, level=0):
    """
    Save the model's info dictionary to a JSON file.
    
    Parameters
    ----------
    obj : object
        Class object containing the info dictionary (e.g., seamless_m4t).
    attr_name : str, optional
        The attribute name holding the dictionary (default: "samples_info").
    save_dir : str, optional
        Path to directory where file will be saved.
    """
    # Ensure save directory exists
    os.makedirs(save_dir, exist_ok=True)

    # Get class object name
    obj_name = [name for name, val in inspect.currentframe().f_back.f_locals.items() if val is obj]
    obj_name = obj_name[0] if obj_name else obj.__class__.__name__

    # Extract info
    if not hasattr(obj, attr_name):
        raise AttributeError(f"Object has no attribute '{attr_name}'")
    
    info_dict = getattr(obj, attr_name)

    # Save as JSON
    if is_llm:
        save_path = os.path.join(save_dir, f"{obj_name}_llm_{level}.json")
    else:
        save_path = os.path.join(save_dir, f"{obj_name}_{level}.json")
    with open(save_path, "w", encoding="utf-8") as f:
        json.dump(info_dict, f, ensure_ascii=False, indent=2)

def save_list_info(list_obj, filename, save_dir="../../reports/phase_1_4/lists_info/mozilla_cv", is_llm=False):
    """
    Save a list of dictionaries to a JSON file.

    Parameters
    ----------
    list_obj : list[dict]
        The list of dictionaries to save.
    filename : str
        Base name for the saved file (without extension).
    save_dir : str, optional
        Directory where the file will be saved.
    """
    os.makedirs(save_dir, exist_ok=True)

    if is_llm:
        save_path = os.path.join(save_dir, f"{filename}_llm_.json")
    else:
        save_path = os.path.join(save_dir, f"{filename}.json")

    with open(save_path, "w", encoding="utf-8") as f:
        json.dump(list_obj, f, ensure_ascii=False, indent=2)

## Cohere

In [ ]:
from stt_benchmarking.models.speech_to_text.arabic import cohere_arabic
importlib.reload(cohere_arabic)

cohere = cohere_arabic.CohereArabicInference(device=device)
cohere.run_inference_one_by_one(cv_audios, substitute=False, normalize_final_letters=True)
save_list_info(cohere.samples_info, "cohere_samples")
cohere.overall_metrics

Loading weights: 100%|██████████| 2150/2150 [00:05<00:00, 403.88it/s]
2026-07-13 14:48:32 - [stt_benchmarking.models.speech_to_text.arabic._load_model:44] INFO - Loaded Cohere Transcribe Arabic (07-2026)
2026-07-13 14:48:32 - [stt_benchmarking.models.speech_to_text.arabic.run_inference_one_by_one:49] INFO - Using substitute: False, Replace Final Char: True
Processing Records: 100%|██████████| 10500/10500 [33:30<00:00,  5.22it/s]
2026-07-13 15:22:03 - [stt_benchmarking.utils.decorators.execution_time_wrapper:22] INFO - Execution time for function run_inference_one_by_one: 33 minutes 30 seconds

{'word_error_rate': {'wer (%)': 5.62,
  'word_similarity_ratio (%)': 97.19,
  'word_edit_distance': 2995,
  'substitutions': 2504,
  'deletions': 294,
  'insertions': 197,
  'hits': 50466,
  'ref_length': 53264,
  'hyp_length': 53167},
 'character_error_rate': {'cer (%)': 1.57,
  'char_similarity_ratio (%)': 99.21,
  'char_edit_distance': 4128,
  'substitutions': 1411,
  'deletions': 1552,
  'insertions': 1165,
  'hits': 260056,
  'ref_length': 263019,
  'hyp_length': 262632}}

## HUBERT

In [6]:
from stt_benchmarking.models.speech_to_text.arabic import hubert
importlib.reload(hubert)

hubert_object = hubert.HubertInference(device=device)
hubert_object.run_inference_one_by_one(cv_audios, substitute=False, normalize_final_letters=True)
save_list_info(hubert_object.samples_info, "hubert_samples")
hubert_object.overall_metrics

Running on Windows; torchaudio backend switching is not available in this version.
Running on Windows; torchaudio backend switching is not available in this version.
During parameter transfer to HubertModel(
  (feature_extractor): HubertFeatureEncoder(
    (conv_layers): ModuleList(
      (0): HubertLayerNormConvLayer(
        (conv): Conv1d(1, 512, kernel_size=(10,), stride=(5,))
        (layer_norm): LayerNorm((512,), eps=1e-05, elementwise_affine=True)
        (activation): GELUActivation()
      )
      (1-4): 4 x HubertLayerNormConvLayer(
        (conv): Conv1d(512, 512, kernel_size=(3,), stride=(2,))
        (layer_norm): LayerNorm((512,), eps=1e-05, elementwise_affine=True)
        (activation): GELUActivation()
      )
      (5-6): 2 x HubertLayerNormConvLayer(
        (conv): Conv1d(512, 512, kernel_size=(2,), stride=(2,))
        (layer_norm): LayerNorm((512,), eps=1e-05, elementwise_affine=True)
        (activation): GELUActivation()
      )
    )
  )
  (feature_projection): HubertFeatureProjection(
    (layer_norm): LayerNorm((512,), eps=1e-05, elementwise_affine=True)
    (projection): Linear(in_features=512, out_features=1024, bias=True)
    (dropout): Dropout(p=0.1, inplace=False)
  )
  (encoder): HubertEncoderStableLayerNorm(
    (pos_conv_embed): HubertPositionalConvEmbedding(
      (conv): ParametrizedConv1d(
        1024, 1024, kernel_size=(128,), stride=(1,), padding=(64,), groups=16
        (parametrizations): ModuleDict(
          (weight): ParametrizationList(
            (0): _WeightNorm()
          )
        )
      )
      (padding): HubertSamePadLayer()
      (activation): GELUActivation()
    )
    (layer_norm): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
    (dropout): Dropout(p=0.1, inplace=False)
    (layers): ModuleList(
      (0-23): 24 x HubertEncoderLayerStableLayerNorm(
        (attention): HubertAttention(
          (k_proj): Linear(in_features=1024, out_features=1024, bias=True)
          (v_proj): Linear(in_features=1024, out_features=1024, bias=True)
          (q_proj): Linear(in_features=1024, out_features=1024, bias=True)
          (out_proj): Linear(in_features=1024, out_features=1024, bias=True)
        )
        (dropout): Dropout(p=0.1, inplace=False)
        (layer_norm): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
        (feed_forward): HubertFeedForward(
          (intermediate_dropout): Dropout(p=0.0, inplace=False)
          (intermediate_dense): Linear(in_features=1024, out_features=4096, bias=True)
          (intermediate_act_fn): GELUActivation()
          (output_dense): Linear(in_features=4096, out_features=1024, bias=True)
          (output_dropout): Dropout(p=0.1, inplace=False)
        )
        (final_layer_norm): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
      )
    )
  )
) loading from wav2vec2_checkpoint\model.ckpt, the transferred parameters did not have parameters for the key: masked_spec_embed
During parameter transfer to HubertModel(
  (feature_extractor): HubertFeatureEncoder(
    (conv_layers): ModuleList(
      (0): HubertLayerNormConvLayer(
        (conv): Conv1d(1, 512, kernel_size=(10,), stride=(5,))
        (layer_norm): LayerNorm((512,), eps=1e-05, elementwise_affine=True)
        (activation): GELUActivation()
      )
      (1-4): 4 x HubertLayerNormConvLayer(
        (conv): Conv1d(512, 512, kernel_size=(3,), stride=(2,))
        (layer_norm): LayerNorm((512,), eps=1e-05, elementwise_affine=True)
        (activation): GELUActivation()
      )
      (5-6): 2 x HubertLayerNormConvLayer(
        (conv): Conv1d(512, 512, kernel_size=(2,), stride=(2,))
        (layer_norm): LayerNorm((512,), eps=1e-05, elementwise_affine=True)
        (activation): GELUActivation()
      )
    )
  )
  (feature_projection): HubertFeatureProjection(
    (layer_norm): LayerNorm((512,), eps=1e-05, elementwise_affine=True)
    (projection): Linear(in_features=512, out_features=1024, bias=True)
    (dropout): Dropout(p=0.1, inplace=False)
  )
  (encoder): HubertEncoderStableLayerNorm(
    (pos_conv_embed): HubertPositionalConvEmbedding(
      (conv): ParametrizedConv1d(
        1024, 1024, kernel_size=(128,), stride=(1,), padding=(64,), groups=16
        (parametrizations): ModuleDict(
          (weight): ParametrizationList(
            (0): _WeightNorm()
          )
        )
      )
      (padding): HubertSamePadLayer()
      (activation): GELUActivation()
    )
    (layer_norm): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
    (dropout): Dropout(p=0.1, inplace=False)
    (layers): ModuleList(
      (0-23): 24 x HubertEncoderLayerStableLayerNorm(
        (attention): HubertAttention(
          (k_proj): Linear(in_features=1024, out_features=1024, bias=True)
          (v_proj): Linear(in_features=1024, out_features=1024, bias=True)
          (q_proj): Linear(in_features=1024, out_features=1024, bias=True)
          (out_proj): Linear(in_features=1024, out_features=1024, bias=True)
        )
        (dropout): Dropout(p=0.1, inplace=False)
        (layer_norm): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
        (feed_forward): HubertFeedForward(
          (intermediate_dropout): Dropout(p=0.0, inplace=False)
          (intermediate_dense): Linear(in_features=1024, out_features=4096, bias=True)
          (intermediate_act_fn): GELUActivation()
          (output_dense): Linear(in_features=4096, out_features=1024, bias=True)
          (output_dropout): Dropout(p=0.1, inplace=False)
        )
        (final_layer_norm): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
      )
    )
  )
) loading from wav2vec2_checkpoint\model.ckpt, the transferred parameters did not have parameters for the key: feature_extractor.conv_layers.0.conv.weight
During parameter transfer to HubertModel(
  (feature_extractor): HubertFeatureEncoder(
    (conv_layers): ModuleList(
      (0): HubertLayerNormConvLayer(
        (conv): Conv1d(1, 512, kernel_size=(10,), stride=(5,))
        (layer_norm): LayerNorm((512,), eps=1e-05, elementwise_affine=True)
        (activation): GELUActivation()
      )
      (1-4): 4 x HubertLayerNormConvLayer(
        (conv): Conv1d(512, 512, kernel_size=(3,), stride=(2,))
        (layer_norm): LayerNorm((512,), eps=1e-05, elementwise_affine=True)
        (activation): GELUActivation()
      )
      (5-6): 2 x HubertLayerNormConvLayer(
        (conv): Conv1d(512, 512, kernel_size=(2,), stride=(2,))
        (layer_norm): LayerNorm((512,), eps=1e-05, elementwise_affine=True)
        (activation): GELUActivation()
      )
    )
  )
  (feature_projection): HubertFeatureProjection(
    (layer_norm): LayerNorm((512,), eps=1e-05, elementwise_affine=True)
    (projection): Linear(in_features=512, out_features=1024, bias=True)
    (dropout): Dropout(p=0.1, inplace=False)
  )
  (encoder): HubertEncoderStableLayerNorm(
    (pos_conv_embed): HubertPositionalConvEmbedding(
      (conv): ParametrizedConv1d(
        1024, 1024, kernel_size=(128,), stride=(1,), padding=(64,), groups=16
        (parametrizations): ModuleDict(
          (weight): ParametrizationList(
            (0): _WeightNorm()
          )
        )
      )
      (padding): HubertSamePadLayer()
      (activation): GELUActivation()
    )
    (layer_norm): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
    (dropout): Dropout(p=0.1, inplace=False)
    (layers): ModuleList(
      (0-23): 24 x HubertEncoderLayerStableLayerNorm(
        (attention): HubertAttention(
          (k_proj): Linear(in_features=1024, out_features=1024, bias=True)
          (v_proj): Linear(in_features=1024, out_features=1024, bias=True)
          (q_proj): Linear(in_features=1024, out_features=1024, bias=True)
          (out_proj): Linear(in_features=1024, out_features=1024, bias=True)
        )
        (dropout): Dropout(p=0.1, inplace=False)
        (layer_norm): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
        (feed_forward): HubertFeedForward(
          (intermediate_dropout): Dropout(p=0.0, inplace=False)
          (intermediate_dense): Linear(in_features=1024, out_features=4096, bias=True)
          (intermediate_act_fn): GELUActivation()
          (output_dense): Linear(in_features=4096, out_features=1024, bias=True)
          (output_dropout): Dropout(p=0.1, inplace=False)
        )
        (final_layer_norm): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
      )
    )
  )
) loading from wav2vec2_checkpoint\model.ckpt, the transferred parameters did not have parameters for the key: feature_extractor.conv_layers.0.conv.bias
During parameter transfer to HubertModel(
  (feature_extractor): HubertFeatureEncoder(
    (conv_layers): ModuleList(
      (0): HubertLayerNormConvLayer(
        (conv): Conv1d(1, 512, kernel_size=(10,), stride=(5,))
        (layer_norm): LayerNorm((512,), eps=1e-05, elementwise_affine=True)
        (activation): GELUActivation()
      )
      (1-4): 4 x HubertLayerNormConvLayer(
        (conv): Conv1d(512, 512, kernel_size=(3,), stride=(2,))
        (layer_norm): LayerNorm((512,), eps=1e-05, elementwise_affine=True)
        (activation): GELUActivation()
      )
      (5-6): 2 x HubertLayerNormConvLayer(
        (conv): Conv1d(512, 512, kernel_size=(2,), stride=(2,))
        (layer_norm): LayerNorm((512,), eps=1e-05, elementwise_affine=True)
        (activation): GELUActivation()
      )
    )
  )
  (feature_projection): HubertFeatureProjection(
    (layer_norm): LayerNorm((512,), eps=1e-05, elementwise_affine=True)
    (projection): Linear(in_features=512, out_features=1024, bias=True)
    (dropout): Dropout(p=0.1, inplace=False)
  )
  (encoder): HubertEncoderStableLayerNorm(
    (pos_conv_embed): HubertPositionalConvEmbedding(
      (conv): ParametrizedConv1d(
        1024, 1024, kernel_size=(128,), stride=(1,), padding=(64,), groups=16
        (parametrizations): ModuleDict(
          (weight): ParametrizationList(
            (0): _WeightNorm()
          )
        )
      )
      (padding): HubertSamePadLayer()
      (activation): GELUActivation()
    )
    (layer_norm): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
    (dropout): Dropout(p=0.1, inplace=False)
    (layers): ModuleList(
      (0-23): 24 x HubertEncoderLayerStableLayerNorm(
        (attention): HubertAttention(
          (k_proj): Linear(in_features=1024, out_features=1024, bias=True)
          (v_proj): Linear(in_features=1024, out_features=1024, bias=True)
          (q_proj): Linear(in_features=1024, out_features=1024, bias=True)
          (out_proj): Linear(in_features=1024, out_features=1024, bias=True)
        )
        (dropout): Dropout(p=0.1, inplace=False)
        (layer_norm): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
        (feed_forward): HubertFeedForward(
          (intermediate_dropout): Dropout(p=0.0, inplace=False)
          (intermediate_dense): Linear(in_features=1024, out_features=4096, bias=True)
          (intermediate_act_fn): GELUActivation()
          (output_dense): Linear(in_features=4096, out_features=1024, bias=True)
          (output_dropout): Dropout(p=0.1, inplace=False)
        )
        (final_layer_norm): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
      )
    )
  )
) loading from wav2vec2_checkpoint\model.ckpt, the transferred parameters did not have parameters for the key: feature_extractor.conv_layers.0.layer_norm.weight
During parameter transfer to HubertModel(
  (feature_extractor): HubertFeatureEncoder(
    (conv_layers): ModuleList(
      (0): HubertLayerNormConvLayer(
        (conv): Conv1d(1, 512, kernel_size=(10,), stride=(5,))
        (layer_norm): LayerNorm((512,), eps=1e-05, elementwise_affine=True)
        (activation): GELUActivation()
      )
      (1-4): 4 x HubertLayerNormConvLayer(
        (conv): Conv1d(512, 512, kernel_size=(3,), stride=(2,))
        (layer_norm): LayerNorm((512,), eps=1e-05, elementwise_affine=True)
        (activation): GELUActivation()
      )
      (5-6): 2 x HubertLayerNormConvLayer(
        (conv): Conv1d(512, 512, kernel_size=(2,), stride=(2,))
        (layer_norm): LayerNorm((512,), eps=1e-05, elementwise_affine=True)
        (activation): GELUActivation()
      )
    )
  )
  (feature_projection): HubertFeatureProjection(
    (layer_norm): LayerNorm((512,), eps=1e-05, elementwise_affine=True)
    (projection): Linear(in_features=512, out_features=1024, bias=True)
    (dropout): Dropout(p=0.1, inplace=False)
  )
  (encoder): HubertEncoderStableLayerNorm(
    (pos_conv_embed): HubertPositionalConvEmbedding(
      (conv): ParametrizedConv1d(
        1024, 1024, kernel_size=(128,), stride=(1,), padding=(64,), groups=16
        (parametrizations): ModuleDict(
          (weight): ParametrizationList(
            (0): _WeightNorm()
          )
        )
      )
      (padding): HubertSamePadLayer()
      (activation): GELUActivation()
    )
    (layer_norm): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
    (dropout): Dropout(p=0.1, inplace=False)
    (layers): ModuleList(
      (0-23): 24 x HubertEncoderLayerStableLayerNorm(
        (attention): HubertAttention(
          (k_proj): Linear(in_features=1024, out_features=1024, bias=True)
          (v_proj): Linear(in_features=1024, out_features=1024, bias=True)
          (q_proj): Linear(in_features=1024, out_features=1024, bias=True)
          (out_proj): Linear(in_features=1024, out_features=1024, bias=True)
        )
        (dropout): Dropout(p=0.1, inplace=False)
        (layer_norm): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
        (feed_forward): HubertFeedForward(
          (intermediate_dropout): Dropout(p=0.0, inplace=False)
          (intermediate_dense): Linear(in_features=1024, out_features=4096, bias=True)
          (intermediate_act_fn): GELUActivation()
          (output_dense): Linear(in_features=4096, out_features=1024, bias=True)
          (output_dropout): Dropout(p=0.1, inplace=False)
        )
        (final_layer_norm): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
      )
    )
  )
) loading from wav2vec2_checkpoint\model.ckpt, the transferred parameters did not have parameters for the key: feature_extractor.conv_layers.0.layer_norm.bias
During parameter transfer to HubertModel(
  (feature_extractor): HubertFeatureEncoder(
    (conv_layers): ModuleList(
      (0): HubertLayerNormConvLayer(
        (conv): Conv1d(1, 512, kernel_size=(10,), stride=(5,))
        (layer_norm): LayerNorm((512,), eps=1e-05, elementwise_affine=True)
        (activation): GELUActivation()
      )
      (1-4): 4 x HubertLayerNormConvLayer(
        (conv): Conv1d(512, 512, kernel_size=(3,), stride=(2,))
        (layer_norm): LayerNorm((512,), eps=1e-05, elementwise_affine=True)
        (activation): GELUActivation()
      )
      (5-6): 2 x HubertLayerNormConvLayer(
        (conv): Conv1d(512, 512, kernel_size=(2,), stride=(2,))
        (layer_norm): LayerNorm((512,), eps=1e-05, elementwise_affine=True)
        (activation): GELUActivation()
      )
    )
  )
  (feature_projection): HubertFeatureProjection(
    (layer_norm): LayerNorm((512,), eps=1e-05, elementwise_affine=True)
    (projection): Linear(in_features=512, out_features=1024, bias=True)
    (dropout): Dropout(p=0.1, inplace=False)
  )
  (encoder): HubertEncoderStableLayerNorm(
    (pos_conv_embed): HubertPositionalConvEmbedding(
      (conv): ParametrizedConv1d(
        1024, 1024, kernel_size=(128,), stride=(1,), padding=(64,), groups=16
        (parametrizations): ModuleDict(
          (weight): ParametrizationList(
            (0): _WeightNorm()
          )
        )
      )
      (padding): HubertSamePadLayer()
      (activation): GELUActivation()
    )
    (layer_norm): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
    (dropout): Dropout(p=0.1, inplace=False)
    (layers): ModuleList(
      (0-23): 24 x HubertEncoderLayerStableLayerNorm(
        (attention): HubertAttention(
          (k_proj): Linear(in_features=1024, out_features=1024, bias=True)
          (v_proj): Linear(in_features=1024, out_features=1024, bias=True)
          (q_proj): Linear(in_features=1024, out_features=1024, bias=True)
          (out_proj): Linear(in_features=1024, out_features=1024, bias=True)
        )
        (dropout): Dropout(p=0.1, inplace=False)
        (layer_norm): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
        (feed_forward): HubertFeedForward(
          (intermediate_dropout): Dropout(p=0.0, inplace=False)
          (intermediate_dense): Linear(in_features=1024, out_features=4096, bias=True)
          (intermediate_act_fn): GELUActivation()
          (output_dense): Linear(in_features=4096, out_features=1024, bias=True)
          (output_dropout): Dropout(p=0.1, inplace=False)
        )
        (final_layer_norm): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
      )
    )
  )
) loading from wav2vec2_checkpoint\model.ckpt, the transferred parameters did not have parameters for the key: feature_extractor.conv_layers.1.conv.weight
During parameter transfer to HubertModel(
  (feature_extractor): HubertFeatureEncoder(
    (conv_layers): ModuleList(
      (0): HubertLayerNormConvLayer(
        (conv): Conv1d(1, 512, kernel_size=(10,), stride=(5,))
        (layer_norm): LayerNorm((512,), eps=1e-05, elementwise_affine=True)
        (activation): GELUActivation()
      )
      (1-4): 4 x HubertLayerNormConvLayer(
        (conv): Conv1d(512, 512, kernel_size=(3,), stride=(2,))
        (layer_norm): LayerNorm((512,), eps=1e-05, elementwise_affine=True)
        (activation): GELUActivation()
      )
      (5-6): 2 x HubertLayerNormConvLayer(
        (conv): Conv1d(512, 512, kernel_size=(2,), stride=(2,))
        (layer_norm): LayerNorm((512,), eps=1e-05, elementwise_affine=True)
        (activation): GELUActivation()
      )
    )
  )
  (feature_projection): HubertFeatureProjection(
    (layer_norm): LayerNorm((512,), eps=1e-05, elementwise_affine=True)
    (projection): Linear(in_features=512, out_features=1024, bias=True)
    (dropout): Dropout(p=0.1, inplace=False)
  )
  (encoder): HubertEncoderStableLayerNorm(
    (pos_conv_embed): HubertPositionalConvEmbedding(
      (conv): ParametrizedConv1d(
        1024, 1024, kernel_size=(128,), stride=(1,), padding=(64,), groups=16
        (parametrizations): ModuleDict(
          (weight): ParametrizationList(
            (0): _WeightNorm()
          )
        )
      )
      (padding): HubertSamePadLayer()
      (activation): GELUActivation()
    )
    (layer_norm): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
    (dropout): Dropout(p=0.1, inplace=False)
    (layers): ModuleList(
      (0-23): 24 x HubertEncoderLayerStableLayerNorm(
        (attention): HubertAttention(
          (k_proj): Linear(in_features=1024, out_features=1024, bias=True)
          (v_proj): Linear(in_features=1024, out_features=1024, bias=True)
          (q_proj): Linear(in_features=1024, out_features=1024, bias=True)
          (out_proj): Linear(in_features=1024, out_features=1024, bias=True)
        )
        (dropout): Dropout(p=0.1, inplace=False)
        (layer_norm): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
        (feed_forward): HubertFeedForward(
          (intermediate_dropout): Dropout(p=0.0, inplace=False)
          (intermediate_dense): Linear(in_features=1024, out_features=4096, bias=True)
          (intermediate_act_fn): GELUActivation()
          (output_dense): Linear(in_features=4096, out_features=1024, bias=True)
          (output_dropout): Dropout(p=0.1, inplace=False)
        )
        (final_layer_norm): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
      )
    )
  )
) loading from wav2vec2_checkpoint\model.ckpt, the transferred parameters did not have parameters for the key: feature_extractor.conv_layers.1.conv.bias
During parameter transfer to HubertModel(
  (feature_extractor): HubertFeatureEncoder(
    (conv_layers): ModuleList(
      (0): HubertLayerNormConvLayer(

{'word_error_rate': {'wer (%)': 7.87,
  'word_similarity_ratio (%)': 96.07,
  'word_edit_distance': 4194,
  'substitutions': 3413,
  'deletions': 312,
  'insertions': 469,
  'hits': 49539,
  'ref_length': 53264,
  'hyp_length': 53421},
 'character_error_rate': {'cer (%)': 2.2,
  'char_similarity_ratio (%)': 98.9,
  'char_edit_distance': 5781,
  'substitutions': 1853,
  'deletions': 2164,
  'insertions': 1764,
  'hits': 259002,
  'ref_length': 263019,
  'hyp_length': 262619}}

## SpeechBrain

In [8]:
from stt_benchmarking.models.speech_to_text.arabic import speechbrain
importlib.reload(speechbrain)

wav2vec_sb_object = speechbrain.SpeechBrainInference(device=device)
wav2vec_sb_object.run_inference_one_by_one(cv_audios, substitute=False, normalize_final_letters=True)
save_list_info(wav2vec_sb_object.samples_info, "wav2vec_sb_samples")
wav2vec_sb_object.overall_metrics

config.json: 0.00B [00:00, ?B/s]

pytorch_model.bin:   0%|          | 0.00/1.27G [00:00<?, ?B/s]

speechbrain.lobes.models.huggingface_transformers.huggingface - Wav2Vec2Model is frozen.

model.safetensors:   0%|          | 0.00/1.27G [00:00<?, ?B/s]

preprocessor_config.json:   0%|          | 0.00/212 [00:00<?, ?B/s]

2026-07-13 14:03:52 - [stt_benchmarking.models.speech_to_text._load_model:43] INFO - Loaded model speechbrain/asr-wav2vec2-commonvoice-14-ar
2026-07-13 14:03:52 - [stt_benchmarking.models.speech_to_text.run_inference_one_by_one:55] INFO - Using substitute: False, Replace Final Char: True
Processing Records: 100%|██████████| 10500/10500 [04:34<00:00, 38.30it/s]
2026-07-13 14:08:28 - [stt_benchmarking.utils.decorators.execution_time_wrapper:22] INFO - Execution time for function run_inference_one_by_one: 4 minutes 35 seconds

{'word_error_rate': {'wer (%)': 29.17,
  'word_similarity_ratio (%)': 85.34,
  'word_edit_distance': 15537,
  'substitutions': 13154,
  'deletions': 1475,
  'insertions': 908,
  'hits': 38635,
  'ref_length': 53264,
  'hyp_length': 52697},
 'character_error_rate': {'cer (%)': 9.72,
  'char_similarity_ratio (%)': 95.12,
  'char_edit_distance': 25565,
  'substitutions': 8095,
  'deletions': 9726,
  'insertions': 7744,
  'hits': 245198,
  'ref_length': 263019,
  'hyp_length': 261037}}

## XLSR

In [10]:
from stt_benchmarking.models.speech_to_text.arabic import xlsr_53
importlib.reload(xlsr_53)

xlsr_object = xlsr_53.XLSRInference(device=device)
xlsr_object.run_inference_one_by_one(cv_audios, substitute=False, normalize_final_letters=True)
save_list_info(xlsr_object.samples_info, "xlsr_samples")
xlsr_object.overall_metrics

`torch_dtype` is deprecated! Use `dtype` instead!
2026-07-13 14:09:52 - [stt_benchmarking.models.speech_to_text._load_model:66] INFO - Loaded Wav2Vec2 XLSR-53 XLSR-53 Model
2026-07-13 14:09:52 - [stt_benchmarking.models.speech_to_text.run_inference_one_by_one:78] INFO - Using substitute: False, Replace Final Char: True
Processing Records: 100%|██████████| 10500/10500 [05:19<00:00, 32.90it/s]
2026-07-13 14:15:13 - [stt_benchmarking.utils.decorators.execution_time_wrapper:22] INFO - Execution time for function run_inference_one_by_one: 5 minutes 20 seconds

{'word_error_rate': {'wer (%)': 22.87,
  'word_similarity_ratio (%)': 88.53,
  'word_edit_distance': 12183,
  'substitutions': 10621,
  'deletions': 937,
  'insertions': 625,
  'hits': 41706,
  'ref_length': 53264,
  'hyp_length': 52952},
 'character_error_rate': {'cer (%)': 6.49,
  'char_similarity_ratio (%)': 96.75,
  'char_edit_distance': 17069,
  'substitutions': 7361,
  'deletions': 5536,
  'insertions': 4172,
  'hits': 250122,
  'ref_length': 263019,
  'hyp_length': 261655}}

## W2v-BERT-AR

In [11]:
from stt_benchmarking.models.speech_to_text.arabic import w2v_bert_ar
importlib.reload(w2v_bert_ar)

w2v_bert_object = w2v_bert_ar.w2vBERTInference(device=device)
w2v_bert_object.run_inference_one_by_one(cv_audios, substitute=False, normalize_final_letters=True)
save_list_info(w2v_bert_object.samples_info, "w2vbert_samples")
w2v_bert_object.overall_metrics

`torch_dtype` is deprecated! Use `dtype` instead!
2026-07-13 14:16:31 - [stt_benchmarking.models.speech_to_text._load_model:48] INFO - Loaded model w2v Bert Arabic
2026-07-13 14:16:31 - [stt_benchmarking.models.speech_to_text.run_inference_one_by_one:60] INFO - Using substitute: False, Replace Final Char: True
Processing Records: 100%|██████████| 10500/10500 [06:27<00:00, 27.12it/s]
2026-07-13 14:22:59 - [stt_benchmarking.utils.decorators.execution_time_wrapper:22] INFO - Execution time for function run_inference_one_by_one: 6 minutes 28 seconds

{'word_error_rate': {'wer (%)': 24.03,
  'word_similarity_ratio (%)': 87.98,
  'word_edit_distance': 12802,
  'substitutions': 10979,
  'deletions': 944,
  'insertions': 879,
  'hits': 41341,
  'ref_length': 53264,
  'hyp_length': 53199},
 'character_error_rate': {'cer (%)': 6.65,
  'char_similarity_ratio (%)': 96.68,
  'char_edit_distance': 17483,
  'substitutions': 5913,
  'deletions': 5734,
  'insertions': 5836,
  'hits': 251372,
  'ref_length': 263019,
  'hyp_length': 263121}}

## Whisper

In [6]:
from stt_benchmarking.models.speech_to_text.arabic import whisper
importlib.reload(whisper)

whisper_v2 = whisper.FasterWhisperInference(device=device, model_version="v2", batch_size=4)
whisper_v2.run_inference_one_by_one(cv_audios, substitute=False, normalize_final_letters=True)
save_list_info(whisper_v2.samples_info, "whisper_v2_samples")
whisper_v2.overall_metrics

2026-07-15 12:40:54 - [stt_benchmarking.models.speech_to_text._load_model:53] INFO - Loaded FasterWhisper V2 Model
2026-07-15 12:40:54 - [stt_benchmarking.models.speech_to_text._load_pipeline:64] INFO - Loaded Whisper V2 Pipeline
2026-07-15 12:40:54 - [stt_benchmarking.models.speech_to_text.run_inference_one_by_one:77] INFO - Using substitute: False, Replace Final Char: True
Processing Records: 100%|██████████| 10500/10500 [2:00:20<00:00,  1.45it/s]
2026-07-15 14:41:16 - [stt_benchmarking.utils.decorators.execution_time_wrapper:22] INFO - Execution time for function run_inference_one_by_one: 120 minutes 21 seconds

{'word_error_rate': {'wer (%)': 18.47,
  'word_similarity_ratio (%)': 90.74,
  'word_edit_distance': 9840,
  'substitutions': 8395,
  'deletions': 827,
  'insertions': 618,
  'hits': 44042,
  'ref_length': 53264,
  'hyp_length': 53055},
 'character_error_rate': {'cer (%)': 6.06,
  'char_similarity_ratio (%)': 96.97,
  'char_edit_distance': 15948,
  'substitutions': 6618,
  'deletions': 4119,
  'insertions': 5211,
  'hits': 252282,
  'ref_length': 263019,
  'hyp_length': 264111}}

In [5]:
from stt_benchmarking.models.speech_to_text.arabic import whisper
importlib.reload(whisper)

whisper_v3 = whisper.FasterWhisperInference(device=device, model_version="v3", batch_size=8)
whisper_v3.run_inference_one_by_one(cv_audios, substitute=False, normalize_final_letters=True)
save_list_info(whisper_v3.samples_info, "whisper_v3_samples")
whisper_v3.overall_metrics

2026-07-13 16:40:58 - [stt_benchmarking.models.speech_to_text._load_model:53] INFO - Loaded FasterWhisper V3 Model
2026-07-13 16:40:58 - [stt_benchmarking.models.speech_to_text._load_pipeline:64] INFO - Loaded Whisper V3 Pipeline
2026-07-13 16:40:58 - [stt_benchmarking.models.speech_to_text.run_inference_one_by_one:77] INFO - Using substitute: False, Replace Final Char: True
Processing Records: 100%|██████████| 10500/10500 [1:55:24<00:00,  1.52it/s]
2026-07-13 18:36:24 - [stt_benchmarking.utils.decorators.execution_time_wrapper:22] INFO - Execution time for function run_inference_one_by_one: 115 minutes 26 seconds

{'word_error_rate': {'wer (%)': 14.77,
  'word_similarity_ratio (%)': 92.6,
  'word_edit_distance': 7867,
  'substitutions': 6741,
  'deletions': 685,
  'insertions': 441,
  'hits': 45838,
  'ref_length': 53264,
  'hyp_length': 53020},
 'character_error_rate': {'cer (%)': 4.69,
  'char_similarity_ratio (%)': 97.65,
  'char_edit_distance': 12340,
  'substitutions': 4984,
  'deletions': 3700,
  'insertions': 3656,
  'hits': 254335,
  'ref_length': 263019,
  'hyp_length': 262975}}

## Fastconformer

In [12]:
from stt_benchmarking.models.speech_to_text.arabic import fastconformer_nvidia
importlib.reload(fastconformer_nvidia)

nvidia_object = fastconformer_nvidia.FastConformerInference(device=device)
nvidia_object.run_inference_one_by_one(cv_audios, substitute=False, normalize_final_letters=True)
save_list_info(nvidia_object.samples_info, "fastconformer_samples")
nvidia_object.overall_metrics

[NeMo W 2026-07-13 14:23:05 model_utils:535] Skipped conversion for config/subconfig:
    {'manifest_filepath': '???', 'sample_rate': 16000, 'batch_size': 16, 'shuffle': True, 'num_workers': 8, 'pin_memory': True, 'max_duration': 20, 'min_duration': 0.5, 'is_tarred': True, 'tarred_audio_filepaths': '???', 'shuffle_n': 2048, 'bucketing_strategy': 'fully_randomized', 'bucketing_batch_size': None}
     Reason: Missing mandatory value: train_ds.manifest_filepath
        full_key: train_ds.manifest_filepath
        object_type=dict.
[NeMo W 2026-07-13 14:23:05 model_utils:535] Skipped conversion for config/subconfig:
    {'manifest_filepath': '???', 'sample_rate': 16000, 'batch_size': 16, 'shuffle': False, 'use_start_end_token': False, 'num_workers': 8, 'pin_memory': True}
     Reason: Missing mandatory value: validation_ds.manifest_filepath
        full_key: validation_ds.manifest_filepath
        object_type=dict.
[NeMo W 2026-07-13 14:23:05 model_utils:535] Skipped conversion for config/subconfig:
    {'manifest_filepath': '???', 'sample_rate': 16000, 'batch_size': 16, 'shuffle': False, 'use_start_end_token': False, 'num_workers': 8, 'pin_memory': True}
     Reason: Missing mandatory value: test_ds.manifest_filepath
        full_key: test_ds.manifest_filepath
        object_type=dict.
[NeMo W 2026-07-13 14:23:05 model_utils:535] Skipped conversion for config/subconfig:
    {'dir': '???', 'type': 'bpe', 'model_path': 'nemo:43c84e71237048ddab3bb273bdc00fa0_tokenizer.model', 'vocab_path': 'nemo:1e7bbe36b91a472896c99283bda08bf3_vocab.txt', 'spe_tokenizer_vocab': 'nemo:e7a019581cd54cce88ac2acf8e4c54a3_tokenizer.vocab'}
     Reason: Missing mandatory value: tokenizer.dir
        full_key: tokenizer.dir
        object_type=dict.
[NeMo W 2026-07-13 14:23:06 model_utils:535] Skipped conversion for config/subconfig:
    {'manifest_filepath': '???', 'sample_rate': 16000, 'batch_size': 16, 'shuffle': True, 'num_workers': 8, 'pin_memory': True, 'max_duration': 20, 'min_duration': 0.5, 'is_tarred': True, 'tarred_audio_filepaths': '???', 'shuffle_n': 2048, 'bucketing_strategy': 'fully_randomized', 'bucketing_batch_size': None}
     Reason: Missing mandatory value: train_ds.manifest_filepath
        full_key: train_ds.manifest_filepath
        object_type=dict.
[NeMo W 2026-07-13 14:23:06 model_utils:535] Skipped conversion for config/subconfig:
    {'manifest_filepath': '???', 'sample_rate': 16000, 'batch_size': 16, 'shuffle': False, 'use_start_end_token': False, 'num_workers': 8, 'pin_memory': True}
     Reason: Missing mandatory value: validation_ds.manifest_filepath
        full_key: validation_ds.manifest_filepath
        object_type=dict.
[NeMo W 2026-07-13 14:23:06 model_utils:535] Skipped conversion for config/subconfig:
    {'manifest_filepath': '???', 'sample_rate': 16000, 'batch_size': 16, 'shuffle': False, 'use_start_end_token': False, 'num_workers': 8, 'pin_memory': True}
     Reason: Missing mandatory value: test_ds.manifest_filepath
        full_key: test_ds.manifest_filepath
        object_type=dict.
[NeMo W 2026-07-13 14:23:06 model_utils:535] Skipped conversion for config/subconfig:
    {'dir': '???', 'type': 'bpe', 'model_path': 'nemo:43c84e71237048ddab3bb273bdc00fa0_tokenizer.model', 'vocab_path': 'nemo:1e7bbe36b91a472896c99283bda08bf3_vocab.txt', 'spe_tokenizer_vocab': 'nemo:e7a019581cd54cce88ac2acf8e4c54a3_tokenizer.vocab'}
     Reason: Missing mandatory value: tokenizer.dir
        full_key: tokenizer.dir
        object_type=dict.

[NeMo I 2026-07-13 14:23:06 mixins:181] Tokenizer SentencePieceTokenizer initialized with 1024 tokens

[NeMo W 2026-07-13 14:23:06 model_utils:535] Skipped conversion for config/subconfig:
    {'manifest_filepath': '???', 'sample_rate': 16000, 'batch_size': 16, 'shuffle': True, 'num_workers': 8, 'pin_memory': True, 'max_duration': 20, 'min_duration': 0.5, 'is_tarred': True, 'tarred_audio_filepaths': '???', 'shuffle_n': 2048, 'bucketing_strategy': 'fully_randomized', 'bucketing_batch_size': None}
     Reason: Missing mandatory value: train_ds.manifest_filepath
        full_key: train_ds.manifest_filepath
        object_type=dict.
[NeMo W 2026-07-13 14:23:06 model_utils:535] Skipped conversion for config/subconfig:
    {'manifest_filepath': '???', 'sample_rate': 16000, 'batch_size': 16, 'shuffle': False, 'use_start_end_token': False, 'num_workers': 8, 'pin_memory': True}
     Reason: Missing mandatory value: validation_ds.manifest_filepath
        full_key: validation_ds.manifest_filepath
        object_type=dict.
[NeMo W 2026-07-13 14:23:06 model_utils:535] Skipped conversion for config/subconfig:
    {'manifest_filepath': '???', 'sample_rate': 16000, 'batch_size': 16, 'shuffle': False, 'use_start_end_token': False, 'num_workers': 8, 'pin_memory': True}
     Reason: Missing mandatory value: test_ds.manifest_filepath
        full_key: test_ds.manifest_filepath
        object_type=dict.
[NeMo W 2026-07-13 14:23:06 model_utils:535] Skipped conversion for config/subconfig:
    {'dir': '???', 'type': 'bpe', 'model_path': 'nemo:43c84e71237048ddab3bb273bdc00fa0_tokenizer.model', 'vocab_path': 'nemo:1e7bbe36b91a472896c99283bda08bf3_vocab.txt', 'spe_tokenizer_vocab': 'nemo:e7a019581cd54cce88ac2acf8e4c54a3_tokenizer.vocab'}
     Reason: Missing mandatory value: tokenizer.dir
        full_key: tokenizer.dir
        object_type=dict.
[NeMo W 2026-07-13 14:23:06 model_utils:535] Skipped conversion for config/subconfig:
    {'manifest_filepath': '???', 'sample_rate': 16000, 'batch_size': 16, 'shuffle': True, 'num_workers': 8, 'pin_memory': True, 'max_duration': 20, 'min_duration': 0.5, 'is_tarred': True, 'tarred_audio_filepaths': '???', 'shuffle_n': 2048, 'bucketing_strategy': 'fully_randomized', 'bucketing_batch_size': None}
     Reason: Missing mandatory value: train_ds.manifest_filepath
        full_key: train_ds.manifest_filepath
        object_type=dict.
[NeMo W 2026-07-13 14:23:06 model_utils:535] Skipped conversion for config/subconfig:
    {'manifest_filepath': '???', 'sample_rate': 16000, 'batch_size': 16, 'shuffle': False, 'use_start_end_token': False, 'num_workers': 8, 'pin_memory': True}
     Reason: Missing mandatory value: validation_ds.manifest_filepath
        full_key: validation_ds.manifest_filepath
        object_type=dict.
[NeMo W 2026-07-13 14:23:06 model_utils:535] Skipped conversion for config/subconfig:
    {'manifest_filepath': '???', 'sample_rate': 16000, 'batch_size': 16, 'shuffle': False, 'use_start_end_token': False, 'num_workers': 8, 'pin_memory': True}
     Reason: Missing mandatory value: test_ds.manifest_filepath
        full_key: test_ds.manifest_filepath
        object_type=dict.
[NeMo W 2026-07-13 14:23:06 model_utils:535] Skipped conversion for config/subconfig:
    {'dir': '???', 'type': 'bpe', 'model_path': 'nemo:43c84e71237048ddab3bb273bdc00fa0_tokenizer.model', 'vocab_path': 'nemo:1e7bbe36b91a472896c99283bda08bf3_vocab.txt', 'spe_tokenizer_vocab': 'nemo:e7a019581cd54cce88ac2acf8e4c54a3_tokenizer.vocab'}
     Reason: Missing mandatory value: tokenizer.dir
        full_key: tokenizer.dir
        object_type=dict.
[NeMo W 2026-07-13 14:23:07 modelPT:180] If you intend to do training or fine-tuning, please call the ModelPT.setup_training_data() method and provide a valid configuration file to setup the train data loader.
    Train config :
    manifest_filepath: ???
    sample_rate: 16000
    batch_size: 16
    shuffle: true
    num_workers: 8
    pin_memory: true
    max_duration: 20
    min_duration: 0.5
    is_tarred: true
    tarred_audio_filepaths: ???
    shuffle_n: 2048
    bucketing_strategy: fully_randomized
    bucketing_batch_size: null

[NeMo W 2026-07-13 14:23:07 modelPT:187] If you intend to do validation, please call the ModelPT.setup_validation_data() or ModelPT.setup_multiple_validation_data() method and provide a valid configuration file to setup the validation data loader(s).
    Validation config :
    manifest_filepath: ???
    sample_rate: 16000
    batch_size: 16
    shuffle: false
    use_start_end_token: false
    num_workers: 8
    pin_memory: true

[NeMo W 2026-07-13 14:23:07 modelPT:194] Please call the ModelPT.setup_test_data() or ModelPT.setup_multiple_test_data() method and provide a valid configuration file to setup the test data loader(s).
    Test config :
    manifest_filepath: ???
    sample_rate: 16000
    batch_size: 16
    shuffle: false
    use_start_end_token: false
    num_workers: 8
    pin_memory: true

[NeMo I 2026-07-13 14:23:07 features:305] PADDING: 0
[NeMo I 2026-07-13 14:23:07 rnnt_models:226] Using RNNT Loss : warprnnt_numba
    Loss warprnnt_numba_kwargs: {'fastemit_lambda': 0.0, 'clamp': -1.0}
[NeMo I 2026-07-13 14:23:07 rnnt_models:226] Using RNNT Loss : warprnnt_numba
    Loss warprnnt_numba_kwargs: {'fastemit_lambda': 0.0, 'clamp': -1.0}
[NeMo I 2026-07-13 14:23:08 rnnt_models:226] Using RNNT Loss : warprnnt_numba
    Loss warprnnt_numba_kwargs: {'fastemit_lambda': 0.0, 'clamp': -1.0}
[NeMo I 2026-07-13 14:23:08 save_restore_connector:275] Model EncDecHybridRNNTCTCBPEModel was successfully restored from C:\Users\school.RABAH-DESKTOP\.cache\huggingface\hub\models--nvidia--stt_ar_fastconformer_hybrid_large_pcd_v1.0\snapshots\7f32349d952f42a28dce979ba73270aa2bbdfa89\stt_ar_fastconformer_hybrid_large_pcd_v1.0.nemo.

2026-07-13 14:23:08 - [stt_benchmarking.models.speech_to_text._load_model:41] INFO - Loaded model stt conformer hybrid
2026-07-13 14:23:08 - [stt_benchmarking.models.speech_to_text.run_inference_one_by_one:53] INFO - Using substitute: False, Replace Final Char: True
Processing Records: 100%|██████████| 10500/10500 [11:58<00:00, 14.61it/s]
2026-07-13 14:35:08 - [stt_benchmarking.utils.decorators.execution_time_wrapper:22] INFO - Execution time for function run_inference_one_by_one: 12 minutes 0 seconds

{'word_error_rate': {'wer (%)': 7.25,
  'word_similarity_ratio (%)': 96.37,
  'word_edit_distance': 3863,
  'substitutions': 3222,
  'deletions': 421,
  'insertions': 220,
  'hits': 49621,
  'ref_length': 53264,
  'hyp_length': 53063},
 'character_error_rate': {'cer (%)': 2.22,
  'char_similarity_ratio (%)': 98.88,
  'char_edit_distance': 5852,
  'substitutions': 1998,
  'deletions': 2578,
  'insertions': 1276,
  'hits': 258443,
  'ref_length': 263019,
  'hyp_length': 261717}}

## Seamless M4t v2

In [5]:
from stt_benchmarking.models.speech_to_text.arabic import seamlessm4t_v2
importlib.reload(seamlessm4t_v2)

seamless_m4t = seamlessm4t_v2.SeamlessM4TFullInterface(device=device)
seamless_m4t.run_inference_optimized(cv_audios, substitute=False, normalize_final_letters=True)
save_list_info(seamless_m4t.samples_info, "seamless_samples")
seamless_m4t.overall_metrics

`torch_dtype` is deprecated! Use `dtype` instead!

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

2026-07-13 15:30:06 - [stt_benchmarking.models.speech_to_text.arabic._load_model:86] INFO - Loaded Seamless M4T V2 Model
`torch_dtype` is deprecated! Use `dtype` instead!

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

Device set to use cuda:0
2026-07-13 15:30:13 - [stt_benchmarking.models.speech_to_text.arabic._load_pipeline:112] INFO - Loaded Seamless M4T V2 Pipeline (20s chunks / 1s stride)
2026-07-13 15:30:13 - [stt_benchmarking.models.speech_to_text.arabic.run_inference_optimized:282] INFO - Using substitute: False, Replace Final Char: True
2026-07-13 15:30:13 - [stt_benchmarking.models.speech_to_text.arabic.run_inference_optimized:290] INFO - Running one-by-one inference on 10500 short files (<30.0s)
Processing Records: 100%|██████████| 10500/10500 [1:05:17<00:00,  2.68it/s]
2026-07-13 16:35:31 - [stt_benchmarking.utils.decorators.execution_time_wrapper:22] INFO - Execution time for function run_inference_one_by_one: 65 minutes 17 seconds
2026-07-13 16:35:31 - [stt_benchmarking.utils.decorators.execution_time_wrapper:22] INFO - Execution time for function run_inference_optimized: 65 minutes 18 seconds

{'word_error_rate': {'wer (%)': 10.84,
  'word_similarity_ratio (%)': 94.59,
  'word_edit_distance': 5774,
  'substitutions': 4983,
  'deletions': 334,
  'insertions': 457,
  'hits': 47947,
  'ref_length': 53264,
  'hyp_length': 53387},
 'character_error_rate': {'cer (%)': 3.55,
  'char_similarity_ratio (%)': 98.23,
  'char_edit_distance': 9340,
  'substitutions': 3507,
  'deletions': 2327,
  'insertions': 3506,
  'hits': 257185,
  'ref_length': 263019,
  'hyp_length': 264198}}

In [4]:
import os
import json

def load_samples_info(file_name, file_dr="../../results/mozilla_common_voice/audios"):
    """
    Load a JSON file from the given directory and normalize paths to start with ../../data
    
    Args:
        file_name (str): Name of the JSON file (with .json extension).
        file_dr (str): Directory where the file is stored.

    Returns:
        dict: Parsed JSON data with normalized paths as keys.
    """
    file_path = os.path.join(file_dr, file_name)
    with open(file_path, "r", encoding="utf-8") as f:
        data = json.load(f)
    
    normalized_data = {}
    for key, value in data.items():        
        normalized_data[key] = value
    
    return normalized_data

def load_list_info(filename, load_dir="../../reports/phase_1_4/lists_info/ultimate_last"):
    """
    Load a list of dictionaries saved as JSON (via save_list_info).
    
    Parameters
    ----------
    filename : str
        The name of the JSON file (e.g., 'ensemble_samples_0.json').
    load_dir : str, optional
        Path to the directory containing the saved file.
        
    Returns
    -------
    list
        Loaded list of dictionaries.
    """
    load_path = os.path.join(load_dir, filename)
    if not os.path.exists(load_path):
        raise FileNotFoundError(f"File not found: {load_path}")
    
    with open(load_path, "r", encoding="utf-8") as f:
        data = json.load(f)
    
    if not isinstance(data, list):
        raise TypeError(f"Expected list, got {type(data).__name__} from {filename}")
    
    return data

In [5]:
def collect_model_metrics(models_with_names):
    """
    Collect metrics from multiple model samples_info objects into a unified DataFrame.
    
    Parameters
    ----------
    models_with_names : list[tuple[str, dict]]
        List of tuples (model_name, samples_info_dict).
    
    Returns
    -------
    pd.DataFrame
        DataFrame containing all model metrics and metadata.
    """
    records = []
    for model_name, samples_info in models_with_names:
        for audio_id, content in samples_info.items():
            metrics = content["metrics"]
            wer_data = metrics["word_error_rate"]
            cer_data = metrics["character_error_rate"]

            wer = wer_data["wer (%)"]
            cer = cer_data["cer (%)"]

            if model_name in {"ensemble", "hybrid_ensemble", "rover"}:
                inference_time = content.get("fusion_time")
            else:
                inference_time = content.get("inference_time")

            records.append({
                "audio_id": audio_id,
                "model": model_name,
                "raw_transcription": content.get("raw_transcription"),
                "normalized_transcription": content.get("normalized_transcription"),
                "raw_prediction": content.get("raw_prediction"),
                "normalized_prediction": content.get("normalized_prediction"),
                "inference_time": inference_time,
                "rtf": content.get("rtf"),
                "fusion_time": content.get("fusion_time"),
                "duration": content.get("duration"),
                "wer": wer,
                "substitutions_w": wer_data["substitutions"],
                "deletions_w": wer_data["deletions"],
                "insertions_w": wer_data["insertions"],
                "hits_w": wer_data["hits"],
                "cer": cer,
                "substitutions_c": cer_data["substitutions"],
                "deletions_c": cer_data["deletions"],
                "insertions_c": cer_data["insertions"],
                "hits_c": cer_data["hits"],
            })

    return pd.DataFrame(records)

def filter_audio_records(df_samples, ensemble_name="ensemble"):
    empty = df_samples["normalized_prediction"].fillna("").str.strip() == ""
    is_ens = df_samples["model"] == ensemble_name
    ens_empty = (empty & is_ens).groupby(df_samples["audio_id"]).transform("any")

    empty_gt = df_samples["normalized_transcription"].fillna("").str.strip() == ""
    gt_empty = empty_gt.groupby(df_samples["audio_id"]).transform("any")

    drop = ens_empty | gt_empty
    df_filtered = df_samples[~drop].reset_index(drop=True)

    print(f"Audios dropped (empty ground truth): {df_samples.loc[gt_empty, 'audio_id'].nunique()}")
    print(f"Audios dropped (empty {ensemble_name}): {df_samples.loc[ens_empty, 'audio_id'].nunique()}")
    print(f"Audios: {df_samples['audio_id'].nunique()} -> {df_filtered['audio_id'].nunique()}")
    return df_filtered

def evaluate_absolute_metrics(df_filtered):
    """
    Compute absolute WER/CER metrics for each model against human references.
    """
    agg_results = []
    for model, g in df_filtered.groupby("model"):
        refs = g["normalized_transcription"].tolist()
        hyps = g["normalized_prediction"].tolist()

        duration_mean = pd.Series(g.get("duration", [])).dropna().mean()
        inference_time_mean = pd.Series(g.get("inference_time", [])).dropna().mean()
        rtf_mean = pd.Series(g.get("rtf", [])).dropna().mean()
        fusion_time_mean = pd.Series(g.get("fusion_time", [])).dropna().mean()
        eval_result = mt.BasicSTTMetrics.evaluate(refs=refs, hyps=hyps)
        word_metrics = eval_result['word_error_rate']
        char_metrics = eval_result['character_error_rate']

        agg_results.append({
            "model": model,
            "WER (%)": word_metrics["wer (%)"],
            "w_substitutions": word_metrics["substitutions"],
            "w_deletions": word_metrics["deletions"],
            "w_insertions": word_metrics["insertions"],
            "w_hits": word_metrics["hits"],
            "word_edit_distance": word_metrics["word_edit_distance"],
            "word_similarity_ratio (%)": word_metrics["word_similarity_ratio (%)"],
            "w_ref_length": word_metrics["ref_length"],
            "w_hyp_length": word_metrics["hyp_length"],

            "CER (%)": char_metrics["cer (%)"],
            "c_substitutions": char_metrics["substitutions"],
            "c_deletions": char_metrics["deletions"],
            "c_insertions": char_metrics["insertions"],
            "c_hits": char_metrics["hits"],
            "char_edit_distance": char_metrics["char_edit_distance"],
            "char_similarity_ratio (%)": char_metrics["char_similarity_ratio (%)"],
            "c_ref_length": char_metrics["ref_length"],
            "c_hyp_length": char_metrics["hyp_length"],

            "duration_mean": duration_mean if not pd.isna(duration_mean) else None,
            "inference_time_mean": inference_time_mean if not pd.isna(inference_time_mean) else None,
            "rtf_mean": rtf_mean if not pd.isna(rtf_mean) else None,
            "inference_time_total_h": (inference_time_mean * len(g) / 3600) if not pd.isna(inference_time_mean) else None,
            "fusion_time_mean": fusion_time_mean
            
        })

    df_eval = pd.DataFrame(agg_results)
    df_eval = df_eval.sort_values(
        by=["WER (%)", "word_similarity_ratio (%)"],
        ascending=[True, False]
    ).reset_index(drop=True)
    return df_eval

def evaluate_relative_metrics(df_filtered, model_name, exclude_models=[]):
    """
    Compute relative WER/CER metrics for each model using ensemble outputs as reference.
    """
    agg_results = []

    ensemble_df = (
        df_filtered[df_filtered['model'] == model_name]
        [["audio_id", "normalized_prediction"]]
        .reset_index(drop=True)
    )
    ensemble_df['_order'] = range(len(ensemble_df))

    assert ensemble_df["audio_id"].is_unique, "Duplicate audio_id in ensemble."
    assert ensemble_df["normalized_prediction"].notna().all(), "Ensemble contains None normalized_prediction."

    models_to_compare = df_filtered[~df_filtered['model'].isin(exclude_models)]

    for model, g in models_to_compare.groupby("model"):
        g = g[["audio_id", "normalized_prediction"]].reset_index(drop=True)

        assert g["audio_id"].is_unique, f"Duplicate audio_id in model {model}."
        assert g["normalized_prediction"].notna().all(), f"Model {model} contains None normalized_prediction."

        merged = ensemble_df.merge(g, on="audio_id", suffixes=("_ref", "_hyp"), how="inner")
        merged = merged.sort_values("_order").reset_index(drop=True)
        assert len(merged) == len(ensemble_df), f"Alignment mismatch for {model}: {len(merged)} vs {len(ensemble_df)}."

        refs = merged["normalized_prediction_ref"].tolist()
        hyps = merged["normalized_prediction_hyp"].tolist()
        assert len(refs) > 0, f"No valid reference for model {model}."

        eval_result = mt.BasicSTTMetrics.evaluate(refs=refs, hyps=hyps)
        word_metrics = eval_result['word_error_rate']
        char_metrics = eval_result['character_error_rate']

        agg_results.append({
            "model": model,
            "WER (%)": word_metrics["wer (%)"],
            "w_substitutions": word_metrics["substitutions"],
            "w_deletions": word_metrics["deletions"],
            "w_insertions": word_metrics["insertions"],
            "w_hits": word_metrics["hits"],
            "word_edit_distance": word_metrics["word_edit_distance"],
            "word_similarity_ratio (%)": word_metrics["word_similarity_ratio (%)"],
            "w_ref_length": word_metrics["ref_length"],
            "w_hyp_length": word_metrics["hyp_length"],

            "CER (%)": char_metrics["cer (%)"],
            "c_substitutions": char_metrics["substitutions"],
            "c_deletions": char_metrics["deletions"],
            "c_insertions": char_metrics["insertions"],
            "c_hits": char_metrics["hits"],
            "char_edit_distance": char_metrics["char_edit_distance"],
            "char_similarity_ratio (%)": char_metrics["char_similarity_ratio (%)"],
            "c_ref_length": char_metrics["ref_length"],
            "c_hyp_length": char_metrics["hyp_length"],
        })

    df_relative = pd.DataFrame(agg_results)
    df_relative = df_relative.sort_values(
        by=["WER (%)", "word_similarity_ratio (%)"],
        ascending=[True, False]
    ).reset_index(drop=True)
    return df_relative

In [6]:
import numpy as np
import pandas as pd
from scipy.stats import spearmanr, kendalltau, pearsonr

# assumes `mt` (your metrics module) is importable in the calling scope,
# i.e. mt.BasicSTTMetrics.evaluate(refs=..., hyps=...) as used elsewhere.


def add_pseudo_reference_wer(df_filtered, ensemble, transcript_key="normalized_prediction"):
    """
    Add per-sample pseudo-reference WER/CER.

    ensemble : dict[audio_id -> dict] with the fused transcript under `transcript_key`.
    """
    ens = {aid: v[transcript_key] for aid, v in ensemble.items()}

    refs = df_filtered["audio_id"].map(ens)
    hyps = df_filtered[transcript_key]

    pseudo_wer, pseudo_cer = [], []
    for ref, hyp in zip(refs, hyps):
        if not isinstance(ref, str) or not ref.strip() or not isinstance(hyp, str):
            pseudo_wer.append(np.nan)
            pseudo_cer.append(np.nan)
            continue
        r = mt.BasicSTTMetrics.evaluate(refs=ref, hyps=hyp)
        pseudo_wer.append(r["word_error_rate"]["wer (%)"])
        pseudo_cer.append(r["character_error_rate"]["cer (%)"])

    df = df_filtered.copy()
    df["pseudo_wer"] = pseudo_wer
    df["pseudo_cer"] = pseudo_cer

    missing = refs.isna().sum()
    if missing:
        print(f"Rows with no ensemble reference: {missing}")
    return df

def _corr(x, y):
    if len(x) < 3 or pd.Series(x).nunique() < 2 or pd.Series(y).nunique() < 2:
        return None
    sp = spearmanr(x, y)
    kt = kendalltau(x, y)
    pr = pearsonr(x, y)
    return {
        "pearson": pr.statistic, "pearson_p": pr.pvalue,
        "spearman": sp.statistic, "spearman_p": sp.pvalue,
        "kendall": kt.statistic, "kendall_p": kt.pvalue,
    }


def per_sample_correlation(df_pseudo, exclude_models=("ensemble", "rover"),
                           metric_pair=("wer", "pseudo_wer"), min_pairs=30):
    """
    Option A. Per-sample WER tracking: correlate true WER vs pseudo-reference WER.

    Returns a df with one row per model (within-model, across samples) plus an
    'ALL' row (pooled over every sample-model pair, the direct NoRefER analogue).
    """
    true_col, pseudo_col = metric_pair
    sub = df_pseudo[~df_pseudo["model"].isin(exclude_models)].copy()
    rows = []

    for model, g in sub.groupby("model"):
        d = g[[true_col, pseudo_col]].dropna()
        if len(d) < min_pairs:
            continue
        c = _corr(d[true_col].values, d[pseudo_col].values)
        if c:
            rows.append({"model": model, "n": len(d), **c})

    d_all = sub[[true_col, pseudo_col]].dropna()
    c_all = _corr(d_all[true_col].values, d_all[pseudo_col].values)
    if c_all:
        rows.append({"model": "ALL (pooled)", "n": len(d_all), **c_all})

    return pd.DataFrame(rows).sort_values("spearman", ascending=False).reset_index(drop=True)


def per_sample_ranking(df_pseudo, exclude_models=("ensemble", "rover"),
                       metric_cols=("wer", "pseudo_wer"),
                       tiebreak_cols=("cer", "pseudo_cer"),
                       min_models=3):
    """
    Per-sample ranking agreement, WER primary with CER as tiebreak only.

    For each sample, systems are ordered by true (WER, then CER) and by
    pseudo (WER, then CER); CER is consulted solely to break exact WER ties,
    so the axis remains a WER ranking, not a WER+CER blend. The two orderings
    are correlated within the sample, then aggregated across samples.

    Returns a one-row summary df with mean/median/std of Spearman and Kendall,
    usable/dropped sample counts, and the residual WER tie fraction.
    """
    true_w, pseudo_w = metric_cols
    true_c, pseudo_c = tiebreak_cols
    sub = df_pseudo[~df_pseudo["model"].isin(exclude_models)].copy()

    sp_vals, kt_vals, tie_fracs = [], [], []
    n_dropped = 0

    for audio_id, g in sub.groupby("audio_id"):
        d = g[[true_w, pseudo_w, true_c, pseudo_c]].dropna()
        if len(d) < min_models:
            n_dropped += 1
            continue

        # residual WER-only tie fraction, before CER breaks them (diagnostic)
        _, counts = np.unique(d[true_w].values, return_counts=True)
        tie_fracs.append(1.0 - len(counts) / len(d))

        # composite ranks: WER primary, CER tiebreak. lexsort keys are
        # applied last-key-first, so primary key goes last.
        true_rank = np.lexsort((d[true_c].values, d[true_w].values)).argsort()
        pseudo_rank = np.lexsort((d[pseudo_c].values, d[pseudo_w].values)).argsort()

        if pd.Series(true_rank).nunique() < 2 or pd.Series(pseudo_rank).nunique() < 2:
            n_dropped += 1
            continue

        sp_vals.append(spearmanr(true_rank, pseudo_rank).statistic)
        kt_vals.append(kendalltau(true_rank, pseudo_rank).statistic)

    summary = {
        "n_samples_used": len(sp_vals),
        "n_samples_dropped": n_dropped,
        "mean_wer_ties": float(np.mean(tie_fracs)) if tie_fracs else np.nan,
        "spearman_mean": float(np.nanmean(sp_vals)) if sp_vals else np.nan,
        "spearman_median": float(np.nanmedian(sp_vals)) if sp_vals else np.nan,
        "spearman_std": float(np.nanstd(sp_vals)) if sp_vals else np.nan,
        "kendall_mean": float(np.nanmean(kt_vals)) if kt_vals else np.nan,
        "kendall_median": float(np.nanmedian(kt_vals)) if kt_vals else np.nan,
        "kendall_std": float(np.nanstd(kt_vals)) if kt_vals else np.nan,
    }
    return pd.DataFrame([summary])


def ranking_correlation(df_absolute, df_relative, exclude_models=("ensemble", "rover")):
    """
    Option B (headline). Correlate the reference ranking against the
    pseudo-reference ranking over models, on full-set aggregate WER.

    df_absolute : output of evaluate_absolute_metrics
    df_relative : output of evaluate_relative_metrics
    Returns (merged_df, coefficients_dict).
    """
    a = df_absolute[["model", "WER (%)"]].rename(columns={"WER (%)": "wer_abs"})
    r = df_relative[["model", "WER (%)"]].rename(columns={"WER (%)": "wer_rel"})
    m = a.merge(r, on="model", how="inner")
    m = m[~m["model"].isin(exclude_models)].reset_index(drop=True)

    c = _corr(m["wer_abs"].values, m["wer_rel"].values)
    return m, c

In [7]:
seamless_samples = load_samples_info("seamless_samples.json")
whisper_v3_samples = load_samples_info("whisper_v3_samples.json")
whisper_v2_samples = load_samples_info("whisper_v2_samples.json")
nvidia_samples = load_samples_info("fastconformer_samples.json")
xlsr_samples = load_samples_info("xlsr_samples.json")
w2vbert_samples = load_samples_info("w2vbert_samples.json")
hubert_samples = load_samples_info("hubert_samples.json")
wav2vec_sb_samples = load_samples_info("wav2vec_sb_samples.json")
cohere_samples = load_samples_info("cohere_samples.json")

In [8]:
all_models = [
    seamless_samples,
    whisper_v3_samples,
    whisper_v2_samples,
    nvidia_samples,
    xlsr_samples,
    w2vbert_samples,
    hubert_samples,
    wav2vec_sb_samples,
    cohere_samples
]

model_names = [
    "seamless_m4t",
    "whisper_v3",
    "whisper_v2",
    "fastconformer",
    "xlsr",
    "w2vbert",
    "hubert",
    "wav2vec_sb",
    "cohere"
]

voters = ["seamless_m4t", "whisper_v3", "fastconformer", "w2vbert", "hubert", "wav2vec_sb", "cohere"]
voters_as_elements = [
    seamless_samples,
    whisper_v3_samples,
    nvidia_samples,
    w2vbert_samples,
    hubert_samples,
    wav2vec_sb_samples,
    cohere_samples]

# ROVER - Evaluation Protocol

In [ ]:
from stt_benchmarking.utils import evaluation_protocol
from stt_benchmarking.models.speech_to_text.arabic import rover
importlib.reload(evaluation_protocol)
importlib.reload(rover)

proto = evaluation_protocol.EvaluationProtocol(
    model_samples=dict(zip(model_names, all_models)),
    voters=voters,
    ensemble_factory=rover.ROVER,
    outdir="protocol_out/mozilla_commonvoice_final_rover",
    n_boot=10000, seed=42, min_pool_size=3,
    main_kwargs={"substitute": False, "normalize_final_letters": True},
    suffix="_rover_cv",
)
report = proto.run()

2026-09-10 12:56:38 - [stt_benchmarking.utils.evaluation_protocol.step0_decorrelation:265] INFO - Step 0 Finished.
2026-09-10 12:56:38 - [stt_benchmarking.models.speech_to_text.arabic.main:406] INFO - Using substitute: False, Replace Final Char: True
ROVER Fusion...: 100%|██████████| 10500/10500 [00:53<00:00, 196.46it/s]
2026-09-10 12:57:35 - [stt_benchmarking.models.speech_to_text.arabic.main:406] INFO - Using substitute: False, Replace Final Char: True
ROVER Fusion...: 100%|██████████| 10500/10500 [00:44<00:00, 234.87it/s]
2026-09-10 12:58:22 - [stt_benchmarking.models.speech_to_text.arabic.main:406] INFO - Using substitute: False, Replace Final Char: True
ROVER Fusion...: 100%|██████████| 10500/10500 [00:41<00:00, 250.31it/s]
2026-09-10 12:59:09 - [stt_benchmarking.models.speech_to_text.arabic.main:406] INFO - Using substitute: False, Replace Final Char: True
ROVER Fusion...: 100%|██████████| 10500/10500 [00:42<00:00, 248.53it/s]
2026-09-10 12:59:56 - [stt_benchmarking.models.speech_to_text.arabic.main:406] INFO - Using substitute: False, Replace Final Char: True
ROVER Fusion...: 100%|██████████| 10500/10500 [00:42<00:00, 246.03it/s]
2026-09-10 13:00:42 - [stt_benchmarking.models.speech_to_text.arabic.main:406] INFO - Using substitute: False, Replace Final Char: True
ROVER Fusion...: 100%|██████████| 10500/10500 [00:44<00:00, 238.02it/s]
2026-09-10 13:01:31 - [stt_benchmarking.models.speech_to_text.arabic.main:406] INFO - Using substitute: False, Replace Final Char: True
ROVER Fusion...: 100%|██████████| 10500/10500 [00:42<00:00, 248.49it/s]
2026-09-10 13:02:17 - [stt_benchmarking.models.speech_to_text.arabic.main:406] INFO - Using substitute: False, Replace Final Char: True
ROVER Fusion...: 100%|██████████| 10500/10500 [00:42<00:00, 247.52it/s]
2026-09-10 13:03:03 - [stt_benchmarking.utils.evaluation_protocol.step1_bias:295] INFO - Step 1 Finished.
2026-09-10 13:03:04 - [stt_benchmarking.utils.evaluation_protocol.step2_ranking:328] INFO - Step 2 Finished.
2026-09-10 13:03:05 - [stt_benchmarking.models.speech_to_text.arabic.main:406] INFO - Using substitute: False, Replace Final Char: True
ROVER Fusion...: 100%|██████████| 10500/10500 [00:50<00:00, 209.69it/s]
2026-09-10 13:04:01 - [stt_benchmarking.utils.evaluation_protocol.step3_pipeline:383] INFO - Step 3 Finished.
2026-09-10 13:04:08 - [stt_benchmarking.utils.evaluation_protocol.step4_bootstrap:427] INFO - Step 4 Finished.
2026-09-10 13:04:16 - [stt_benchmarking.utils.evaluation_protocol.step4_bootstrap:427] INFO - Step 4 Finished.
2026-09-10 13:05:07 - [stt_benchmarking.utils.evaluation_protocol.step5_baselines:471] INFO - Step 5 Finished.
2026-09-10 13:05:07 - [stt_benchmarking.models.speech_to_text.arabic.main:406] INFO - Using substitute: False, Replace Final Char: True
ROVER Fusion...: 100%|██████████| 10500/10500 [00:01<00:00, 9986.92it/s]
2026-09-10 13:05:09 - [stt_benchmarking.models.speech_to_text.arabic.main:406] INFO - Using substitute: False, Replace Final Char: True
ROVER Fusion...: 100%|██████████| 10500/10500 [00:01<00:00, 8780.40it/s]
2026-09-10 13:05:14 - [stt_benchmarking.models.speech_to_text.arabic.main:406] INFO - Using substitute: False, Replace Final Char: True
ROVER Fusion...: 100%|██████████| 10500/10500 [00:00<00:00, 15683.86it/s]
2026-09-10 13:05:19 - [stt_benchmarking.models.speech_to_text.arabic.main:406] INFO - Using substitute: False, Replace Final Char: True
ROVER Fusion...: 100%|██████████| 10500/10500 [00:00<00:00, 13286.77it/s]
2026-09-10 13:05:22 - [stt_benchmarking.models.speech_to_text.arabic.main:406] INFO - Using substitute: False, Replace Final Char: True
ROVER Fusion...: 100%|██████████| 10500/10500 [00:00<00:00, 17862.09it/s]
2026-09-10 13:05:27 - [stt_benchmarking.models.speech_to_text.arabic.main:406] INFO - Using substitute: False, Replace Final Char: True
ROVER Fusion...: 100%|██████████| 10500/10500 [00:00<00:00, 15307.05it/s]
2026-09-10 13:05:30 - [stt_benchmarking.models.speech_to_text.arabic.main:406] INFO - Using substitute: False, Replace Final Char: True
ROVER Fusion...: 100%|██████████| 10500/10500 [00:00<00:00, 13119.62it/s]
2026-09-10 13:05:35 - [stt_benchmarking.models.speech_to_text.arabic.main:406] INFO - Using substitute: False, Replace Final Char: True
ROVER Fusion...: 100%|██████████| 10500/10500 [00:00<00:00, 11218.29it/s]
2026-09-10 13:05:38 - [stt_benchmarking.models.speech_to_text.arabic.main:406] INFO - Using substitute: False, Replace Final Char: True
ROVER Fusion...: 100%|██████████| 10500/10500 [00:00<00:00, 13041.16it/s]
2026-09-10 13:05:43 - [stt_benchmarking.models.speech_to_text.arabic.main:406] INFO - Using substitute: False, Replace Final Char: True
ROVER Fusion...: 100%|██████████| 10500/10500 [00:00<00:00, 17786.07it/s]
2026-09-10 13:05:46 - [stt_benchmarking.models.speech_to_text.arabic.main:406] INFO - Using substitute: False, Replace Final Char: True
ROVER Fusion...: 100%|██████████| 10500/10500 [00:01<00:00, 9025.30it/s]
2026-09-10 13:05:51 - [stt_benchmarking.models.speech_to_text.arabic.main:406] INFO - Using substitute: False, Replace Final Char: True
ROVER Fusion...: 100%|██████████| 10500/10500 [00:00<00:00, 17281.89it/s]
2026-09-10 13:05:54 - [stt_benchmarking.models.speech_to_text.arabic.main:406] INFO - Using substitute: False, Replace Final Char: True
ROVER Fusion...: 100%|██████████| 10500/10500 [00:00<00:00, 13169.41it/s]
2026-09-10 13:06:00 - [stt_benchmarking.models.speech_to_text.arabic.main:406] INFO - Using substitute: False, Replace Final Char: True
ROVER Fusion...: 100%|██████████| 10500/10500 [00:00<00:00, 11589.39it/s]
2026-09-10 13:06:03 - [stt_benchmarking.models.speech_to_text.arabic.main:406] INFO - Using substitute: False, Replace Final Char: True
ROVER Fusion...: 100%|██████████| 10500/10500 [00:03<00:00, 2900.47it/s]
2026-09-10 13:06:09 - [stt_benchmarking.models.speech_to_text.arabic.main:406] INFO - Using substitute: False, Replace Final Char: True
ROVER Fusion...: 100%|██████████| 10500/10500 [00:00<00:00, 17084.18it/s]
2026-09-10 13:06:13 - [stt_benchmarking.models.speech_to_text.arabic.main:406] INFO - Using substitute: False, Replace Final Char: True
ROVER Fusion...: 100%|██████████| 10500/10500 [00:00<00:00, 16559.14it/s]
2026-09-10 13:06:17 - [stt_benchmarking.models.speech_to_text.arabic.main:406] INFO - Using substitute: False, Replace Final Char: True
ROVER Fusion...: 100%|██████████| 10500/10500 [00:01<00:00, 8338.05it/s]
2026-09-10 13:06:24 - [stt_benchmarking.models.speech_to_text.arabic.main:406] INFO - Using substitute: False, Replace Final Char: True
ROVER Fusion...: 100%|██████████| 10500/10500 [00:00<00:00, 12699.28it/s]
2026-09-10 13:06:28 - [stt_benchmarking.models.speech_to_text.arabic.main:406] INFO - Using substitute: False, Replace Final Char: True
ROVER Fusion...: 100%|██████████| 10500/10500 [00:00<00:00, 11498.30it/s]
2026-09-10 13:06:31 - [stt_benchmarking.models.speech_to_text.arabic.main:406] INFO - Using substitute: False, Replace Final Char: True
ROVER Fusion...: 100%|██████████| 10500/10500 [00:01<00:00, 10352.84it/s]
2026-09-10 13:06:39 - [stt_benchmarking.models.speech_to_text.arabic.main:406] INFO - Using substitute: False, Replace Final Char: True
ROVER Fusion...: 100%|██████████| 10500/10500 [00:00<00:00, 12983.77it/s]
2026-09-10 13:06:43 - [stt_benchmarking.models.speech_to_text.arabic.main:406] INFO - Using substitute: False, Replace Final Char: True
ROVER Fusion...: 100%|██████████| 10500/10500 [00:00<00:00, 11774.73it/s]
2026-09-10 13:06:51 - [stt_benchmarking.models.speech_to_text.arabic.main:406] INFO - Using substitute: False, Replace Final Char: True
ROVER Fusion...: 100%|██████████| 10500/10500 [00:00<00:00, 13611.41it/s]
2026-09-10 13:06:54 - [stt_benchmarking.models.speech_to_text.arabic.main:406] INFO - Using substitute: False, Replace Final Char: True
ROVER Fusion...: 100%|██████████| 10500/10500 [00:00<00:00, 12317.37it/s]
2026-09-10 13:06:58 - [stt_benchmarking.models.speech_to_text.arabic.main:406] INFO - Using substitute: False, Replace Final Char: True
ROVER Fusion...: 100%|██████████| 10500/10500 [00:00<00:00, 18189.85it/s]
2026-09-10 13:07:04 - [stt_benchmarking.models.speech_to_text.arabic.main:406] INFO - Using substitute: False, Replace Final Char: True
ROVER Fusion...: 100%|██████████| 10500/10500 [00:01<00:00, 9662.35it/s]
2026-09-10 13:07:13 - [stt_benchmarking.models.speech_to_text.arabic.main:406] INFO - Using substitute: False, Replace Final Char: True
ROVER Fusion...: 100%|██████████| 10500/10500 [00:00<00:00, 10750.80it/s]
2026-09-10 13:07:18 - [stt_benchmarking.models.speech_to_text.arabic.main:406] INFO - Using substitute: False, Replace Final Char: True
ROVER Fusion...: 100%|██████████| 10500/10500 [00:00<00:00, 12131.64it/s]
2026-09-10 13:07:24 - [stt_benchmarking.models.speech_to_text.arabic.main:406] INFO - Using substitute: False, Replace Final Char: True
ROVER Fusion...: 100%|██████████| 10500/10500 [00:00<00:00, 15152.19it/s]
2026-09-10 13:07:34 - [stt_benchmarking.models.speech_to_text.arabic.main:406] INFO - Using substitute: False, Replace Final Char: True
ROVER Fusion...: 100%|██████████| 10500/10500 [00:00<00:00, 13615.65it/s]
2026-09-10 13:07:39 - [stt_benchmarking.models.speech_to_text.arabic.main:406] INFO - Using substitute: False, Replace Final Char: True
ROVER Fusion...: 100%|██████████| 10500/10500 [00:01<00:00, 9623.66it/s]
2026-09-10 13:07:46 - [stt_benchmarking.models.speech_to_text.arabic.main:406] INFO - Using substitute: False, Replace Final Char: True
ROVER Fusion...: 100%|██████████| 10500/10500 [00:05<00:00, 1809.17it/s]
2026-09-10 13:07:59 - [stt_benchmarking.models.speech_to_text.arabic.main:406] INFO - Using substitute: False, Replace Final Char: True
ROVER Fusion...: 100%|██████████| 10500/10500 [00:00<00:00, 13951.65it/s]
2026-09-10 13:08:06 - [stt_benchmarking.models.speech_to_text.arabic.main:406] INFO - Using substitute: False, Replace Final Char: True
ROVER Fusion...: 100%|██████████| 10500/10500 [00:00<00:00, 17657.98it/s]
2026-09-10 13:08:14 - [stt_benchmarking.models.speech_to_text.arabic.main:406] INFO - Using substitute: False, Replace Final Char: True
ROVER Fusion...: 100%|██████████| 10500/10500 [00:16<00:00, 626.04it/s]
2026-09-10 13:08:47 - [stt_benchmarking.models.speech_to_text.arabic.main:406] INFO - Using substitute: False, Replace Final Char: True
ROVER Fusion...: 100%|██████████| 10500/10500 [00:20<00:00, 509.16it/s]
2026-09-10 13:09:22 - [stt_benchmarking.models.speech_to_text.arabic.main:406] INFO - Using substitute: False, Replace Final Char: True
ROVER Fusion...: 100%|██████████| 10500/10500 [00:15<00:00, 686.85it/s]
2026-09-10 13:09:54 - [stt_benchmarking.models.speech_to_text.arabic.main:406] INFO - Using substitute: False, Replace Final Char: True
ROVER Fusion...: 100%|██████████| 10500/10500 [00:14<00:00, 725.03it/s]
2026-09-10 13:10:26 - [stt_benchmarking.models.speech_to_text.arabic.main:406] INFO - Using substitute: False, Replace Final Char: True
ROVER Fusion...: 100%|██████████| 10500/10500 [00:17<00:00, 604.80it/s]
2026-09-10 13:10:58 - [stt_benchmarking.models.speech_to_text.arabic.main:406] INFO - Using substitute: False, Replace Final Char: True
ROVER Fusion...: 100%|██████████| 10500/10500 [00:18<00:00, 554.18it/s]
2026-09-10 13:11:35 - [stt_benchmarking.models.speech_to_text.arabic.main:406] INFO - Using substitute: False, Replace Final Char: True
ROVER Fusion...: 100%|██████████| 10500/10500 [00:19<00:00, 551.93it/s]
2026-09-10 13:12:07 - [stt_benchmarking.models.speech_to_text.arabic.main:406] INFO - Using substitute: False, Replace Final Char: True
ROVER Fusion...: 100%|██████████| 10500/10500 [00:17<00:00, 587.27it/s]
2026-09-10 13:12:39 - [stt_benchmarking.models.speech_to_text.arabic.main:406] INFO - Using substitute: False, Replace Final Char: True
ROVER Fusion...: 100%|██████████| 10500/10500 [00:16<00:00, 652.55it/s]
2026-09-10 13:13:11 - [stt_benchmarking.models.speech_to_text.arabic.main:406] INFO - Using substitute: False, Replace Final Char: True
ROVER Fusion...: 100%|██████████| 10500/10500 [00:15<00:00, 665.27it/s]
2026-09-10 13:13:49 - [stt_benchmarking.models.speech_to_text.arabic.main:406] INFO - Using substitute: False, Replace Final Char: True
ROVER Fusion...: 100%|██████████| 10500/10500 [00:15<00:00, 672.85it/s]
2026-09-10 13:14:19 - [stt_benchmarking.models.speech_to_text.arabic.main:406] INFO - Using substitute: False, Replace Final Char: True
ROVER Fusion...: 100%|██████████| 10500/10500 [00:16<00:00, 655.76it/s]
2026-09-10 13:14:50 - [stt_benchmarking.models.speech_to_text.arabic.main:406] INFO - Using substitute: False, Replace Final Char: True
ROVER Fusion...: 100%|██████████| 10500/10500 [00:18<00:00, 555.56it/s]
2026-09-10 13:15:22 - [stt_benchmarking.models.speech_to_text.arabic.main:406] INFO - Using substitute: False, Replace Final Char: True
ROVER Fusion...: 100%|██████████| 10500/10500 [00:15<00:00, 670.02it/s]
2026-09-10 13:15:54 - [stt_benchmarking.models.speech_to_text.arabic.main:406] INFO - Using substitute: False, Replace Final Char: True
ROVER Fusion...: 100%|██████████| 10500/10500 [00:19<00:00, 544.37it/s]
2026-09-10 13:16:31 - [stt_benchmarking.models.speech_to_text.arabic.main:406] INFO - Using substitute: False, Replace Final Char: True
ROVER Fusion...: 100%|██████████| 10500/10500 [00:17<00:00, 584.10it/s]
2026-09-10 13:17:03 - [stt_benchmarking.models.speech_to_text.arabic.main:406] INFO - Using substitute: False, Replace Final Char: True
ROVER Fusion...: 100%|██████████| 10500/10500 [00:17<00:00, 602.16it/s]
2026-09-10 13:17:35 - [stt_benchmarking.models.speech_to_text.arabic.main:406] INFO - Using substitute: False, Replace Final Char: True
ROVER Fusion...: 100%|██████████| 10500/10500 [00:17<00:00, 592.18it/s]
2026-09-10 13:18:06 - [stt_benchmarking.models.speech_to_text.arabic.main:406] INFO - Using substitute: False, Replace Final Char: True
ROVER Fusion...: 100%|██████████| 10500/10500 [00:21<00:00, 494.63it/s]
2026-09-10 13:18:39 - [stt_benchmarking.models.speech_to_text.arabic.main:406] INFO - Using substitute: False, Replace Final Char: True
ROVER Fusion...: 100%|██████████| 10500/10500 [00:22<00:00, 461.79it/s]
2026-09-10 13:19:16 - [stt_benchmarking.models.speech_to_text.arabic.main:406] INFO - Using substitute: False, Replace Final Char: True
ROVER Fusion...: 100%|██████████| 10500/10500 [00:14<00:00, 707.72it/s]
2026-09-10 13:19:47 - [stt_benchmarking.models.speech_to_text.arabic.main:406] INFO - Using substitute: False, Replace Final Char: True
ROVER Fusion...: 100%|██████████| 10500/10500 [00:15<00:00, 689.92it/s]
2026-09-10 13:20:18 - [stt_benchmarking.models.speech_to_text.arabic.main:406] INFO - Using substitute: False, Replace Final Char: True
ROVER Fusion...: 100%|██████████| 10500/10500 [00:14<00:00, 703.82it/s]
2026-09-10 13:20:48 - [stt_benchmarking.models.speech_to_text.arabic.main:406] INFO - Using substitute: False, Replace Final Char: True
ROVER Fusion...: 100%|██████████| 10500/10500 [00:17<00:00, 600.62it/s]
2026-09-10 13:21:20 - [stt_benchmarking.models.speech_to_text.arabic.main:406] INFO - Using substitute: False, Replace Final Char: True
ROVER Fusion...: 100%|██████████| 10500/10500 [00:24<00:00, 422.68it/s]
2026-09-10 13:21:58 - [stt_benchmarking.models.speech_to_text.arabic.main:406] INFO - Using substitute: False, Replace Final Char: True
ROVER Fusion...: 100%|██████████| 10500/10500 [00:18<00:00, 577.02it/s]
2026-09-10 13:22:29 - [stt_benchmarking.models.speech_to_text.arabic.main:406] INFO - Using substitute: False, Replace Final Char: True
ROVER Fusion...: 100%|██████████| 10500/10500 [00:18<00:00, 568.12it/s]
2026-09-10 13:23:00 - [stt_benchmarking.models.speech_to_text.arabic.main:406] INFO - Using substitute: False, Replace Final Char: True
ROVER Fusion...: 100%|██████████| 10500/10500 [00:18<00:00, 572.73it/s]
2026-09-10 13:23:33 - [stt_benchmarking.models.speech_to_text.arabic.main:406] INFO - Using substitute: False, Replace Final Char: True
ROVER Fusion...: 100%|██████████| 10500/10500 [00:20<00:00, 518.35it/s]
2026-09-10 13:24:06 - [stt_benchmarking.models.speech_to_text.arabic.main:406] INFO - Using substitute: False, Replace Final Char: True
ROVER Fusion...: 100%|██████████| 10500/10500 [00:17<00:00, 590.21it/s]
2026-09-10 13:24:39 - [stt_benchmarking.models.speech_to_text.arabic.main:406] INFO - Using substitute: False, Replace Final Char: True
ROVER Fusion...: 100%|██████████| 10500/10500 [00:17<00:00, 608.19it/s]
2026-09-10 13:25:20 - [stt_benchmarking.models.speech_to_text.arabic.main:406] INFO - Using substitute: False, Replace Final Char: True
ROVER Fusion...: 100%|██████████| 10500/10500 [00:17<00:00, 590.72it/s]
2026-09-10 13:25:52 - [stt_benchmarking.models.speech_to_text.arabic.main:406] INFO - Using substitute: False, Replace Final Char: True
ROVER Fusion...: 100%|██████████| 10500/10500 [00:17<00:00, 601.01it/s]
2026-09-10 13:26:26 - [stt_benchmarking.models.speech_to_text.arabic.main:406] INFO - Using substitute: False, Replace Final Char: True
ROVER Fusion...: 100%|██████████| 10500/10500 [00:20<00:00, 520.74it/s]
2026-09-10 13:26:59 - [stt_benchmarking.models.speech_to_text.arabic.main:406] INFO - Using substitute: False, Replace Final Char: True
ROVER Fusion...: 100%|██████████| 10500/10500 [00:16<00:00, 646.03it/s]
2026-09-10 13:27:31 - [stt_benchmarking.models.speech_to_text.arabic.main:406] INFO - Using substitute: False, Replace Final Char: True
ROVER Fusion...: 100%|██████████| 10500/10500 [00:31<00:00, 331.47it/s]
2026-09-10 13:28:10 - [stt_benchmarking.models.speech_to_text.arabic.main:406] INFO - Using substitute: False, Replace Final Char: True
ROVER Fusion...: 100%|██████████| 10500/10500 [00:31<00:00, 338.63it/s]
2026-09-10 13:28:48 - [stt_benchmarking.models.speech_to_text.arabic.main:406] INFO - Using substitute: False, Replace Final Char: True
ROVER Fusion...: 100%|██████████| 10500/10500 [00:30<00:00, 349.63it/s]
2026-09-10 13:29:26 - [stt_benchmarking.models.speech_to_text.arabic.main:406] INFO - Using substitute: False, Replace Final Char: True
ROVER Fusion...: 100%|██████████| 10500/10500 [00:31<00:00, 334.67it/s]
2026-09-10 13:30:14 - [stt_benchmarking.models.speech_to_text.arabic.main:406] INFO - Using substitute: False, Replace Final Char: True
ROVER Fusion...: 100%|██████████| 10500/10500 [00:29<00:00, 356.28it/s]
2026-09-10 13:30:52 - [stt_benchmarking.models.speech_to_text.arabic.main:406] INFO - Using substitute: False, Replace Final Char: True
ROVER Fusion...: 100%|██████████| 10500/10500 [00:28<00:00, 365.28it/s]
2026-09-10 13:31:29 - [stt_benchmarking.models.speech_to_text.arabic.main:406] INFO - Using substitute: False, Replace Final Char: True
ROVER Fusion...: 100%|██████████| 10500/10500 [00:31<00:00, 330.57it/s]
2026-09-10 13:32:08 - [stt_benchmarking.models.speech_to_text.arabic.main:406] INFO - Using substitute: False, Replace Final Char: True
ROVER Fusion...: 100%|██████████| 10500/10500 [00:30<00:00, 344.83it/s]
2026-09-10 13:32:46 - [stt_benchmarking.models.speech_to_text.arabic.main:406] INFO - Using substitute: False, Replace Final Char: True
ROVER Fusion...: 100%|██████████| 10500/10500 [00:31<00:00, 334.09it/s]
2026-09-10 13:33:25 - [stt_benchmarking.models.speech_to_text.arabic.main:406] INFO - Using substitute: False, Replace Final Char: True
ROVER Fusion...: 100%|██████████| 10500/10500 [00:30<00:00, 342.93it/s]
2026-09-10 13:34:03 - [stt_benchmarking.models.speech_to_text.arabic.main:406] INFO - Using substitute: False, Replace Final Char: True
ROVER Fusion...: 100%|██████████| 10500/10500 [00:21<00:00, 491.11it/s]
2026-09-10 13:34:39 - [stt_benchmarking.models.speech_to_text.arabic.main:406] INFO - Using substitute: False, Replace Final Char: True
ROVER Fusion...: 100%|██████████| 10500/10500 [00:30<00:00, 344.95it/s]
2026-09-10 13:35:27 - [stt_benchmarking.models.speech_to_text.arabic.main:406] INFO - Using substitute: False, Replace Final Char: True
ROVER Fusion...: 100%|██████████| 10500/10500 [00:29<00:00, 351.61it/s]

=== skipped_empty_gt ===
0

=== main_kwargs_applied ===
{
  "substitute": false,
  "normalize_final_letters": true
}

=== main_kwargs_dropped ===
[]

=== step0_cross_wer ===
               seamless_m4t  whisper_v3  whisper_v2  fastconformer   xlsr  w2vbert  hubert  wav2vec_sb  cohere
seamless_m4t           0.00       15.80       19.40          11.85  24.88    25.77   13.86       30.72   10.23
whisper_v3            15.80        0.00       14.77          15.00  25.50    26.23   17.06       31.71   13.88
whisper_v2            19.40       14.77        0.00          18.63  28.03    28.83   20.50       33.99   17.57
fastconformer         11.85       15.00       18.63           0.00  22.77    24.06   10.30       28.80    7.05
xlsr                  24.88       25.50       28.03          22.77   0.00    31.68   23.49       31.10   22.29
w2vbert               25.77       26.23       28.83          24.06  31.68     0.00   25.33       37.20   23.32
hubert                13.86       17.06       20.50          10.30  23.49    25.33    0.00       29.58    9.23
wav2vec_sb            30.72       31.71       33.99          28.80  31.10    37.20   29.58        0.00   28.81
cohere                10.23       13.88       17.57           7.05  22.29    23.32    9.23       28.81    0.00

=== step0_err_corr ===
               seamless_m4t  whisper_v3  whisper_v2  fastconformer    xlsr  w2vbert  hubert  wav2vec_sb  cohere
seamless_m4t         1.0000      0.4930      0.4572         0.4468  0.3933   0.3559  0.3527      0.3807  0.4864
whisper_v3           0.4930      1.0000      0.6827         0.4367  0.4573   0.4390  0.3487      0.4105  0.4442
whisper_v2           0.4572      0.6827      1.0000         0.3904  0.4453   0.4221  0.3313      0.4116  0.4045
fastconformer        0.4468      0.4367      0.3904         1.0000  0.4100   0.3553  0.4155      0.4007  0.5511
xlsr                 0.3933      0.4573      0.4453         0.4100  1.0000   0.4547  0.4217      0.6335  0.3863
w2vbert              0.3559      0.4390      0.4221         0.3553  0.4547   1.0000  0.3421      0.4296  0.3379
hubert               0.3527      0.3487      0.3313         0.4155  0.4217   0.3421  1.0000      0.4044  0.3997
wav2vec_sb           0.3807      0.4105      0.4116         0.4007  0.6335   0.4296  0.4044      1.0000  0.3594
cohere               0.4864      0.4442      0.4045         0.5511  0.3863   0.3379  0.3997      0.3594  1.0000

=== step0_flags ===
                         pair  cross_wer  err_corr                                                            note
0  seamless_m4t|fastconformer      11.85    0.4468  unusually similar hypotheses - suspect shared lab/data/teacher
1         seamless_m4t|hubert      13.86    0.3527  unusually similar hypotheses - suspect shared lab/data/teacher
2         seamless_m4t|cohere      10.23    0.4864  unusually similar hypotheses - suspect shared lab/data/teacher
3           whisper_v3|cohere      13.88    0.4442  unusually similar hypotheses - suspect shared lab/data/teacher
4        fastconformer|hubert      10.30    0.4155  unusually similar hypotheses - suspect shared lab/data/teacher
5        fastconformer|cohere       7.05    0.5511  unusually similar hypotheses - suspect shared lab/data/teacher
6               hubert|cohere       9.23    0.3997  unusually similar hypotheses - suspect shared lab/data/teacher

=== step1_bias ===
           model                  role  n_samples  spearman_full  spearman_loo  kendall_full  kendall_loo  delta_spearman  delta_kendall
0         cohere                 voter      10495         0.5832        0.5818        0.5573       0.5525         -0.0014        -0.0048
1  fastconformer                 voter      10495         0.7057        0.7092        0.6727       0.6740          0.0035         0.0013
2         hubert                 voter      10495         0.7213        0.7056        0.6895       0.6709         -0.0158        -0.0186
3   seamless_m4t                 voter      10495         0.8005        0.8062        0.7633       0.7675          0.0057         0.0042
4     whisper_v3                 voter      10495         0.8694        0.8837        0.8273       0.8454          0.0143         0.0180
5     whisper_v2  ranked_only(control)      10495         0.9054        0.9054        0.8640       0.8640          0.0000         0.0000
6        w2vbert                 voter      10495         0.9212        0.9315        0.8768       0.8893          0.0104         0.0124
7           xlsr  ranked_only(control)      10495         0.9279        0.9279        0.8866       0.8866          0.0000         0.0000
8     wav2vec_sb                 voter      10495         0.9518        0.9573        0.9137       0.9206          0.0054         0.0069

=== step2_ranking ===
           model         role  n_samples  wer_true  cer_true  wer_pseudo_loo  cer_pseudo_loo  rank_true  rank_pseudo  wer_compression
0         cohere        voter      10496    5.5591    1.5028          5.6430          1.7637          1            1          -0.0839
1  fastconformer        voter      10496    7.1898    2.1580          7.0657          2.2595          2            2           0.1241
2         hubert        voter      10495    7.8081    2.1291          9.0767          2.5375          3            3          -1.2687
3   seamless_m4t        voter      10495   10.7671    3.4897          9.8725          3.4809          4            4           0.8946
4     whisper_v3        voter      10495   14.7106    4.6360         13.2142          4.3401          5            5           1.4964
5     whisper_v2  ranked_only      10495   18.4155    6.0072         16.5904          5.6871          6            6           1.8251
6           xlsr  ranked_only      10495   22.8174    6.4330         21.4653          6.1227          7            7           1.3521
7        w2vbert        voter      10495   23.9822    6.5829         22.7165          6.3372          8            8           1.2657
8     wav2vec_sb        voter      10495   29.1187    9.6559         27.9510          9.3329          9            9           1.1676

=== step2_stats ===
{
  "n_models": 9,
  "spearman": 1.0,
  "kendall_b": 1.0,
  "spearman_exact_p_onetailed": 2.7557319223985893e-06,
  "kendall_exact_p_onetailed": 2.7557319223985893e-06,
  "p_method": "exact",
  "n_permutations": 362880,
  "min_attainable_p": 2.7557319223985893e-06,
  "pearson": 0.9957892500061175,
  "pearson_p": 1.588604882299806e-08,
  "mean_wer_compression": 0.752563017997661
}

=== step3_runs ===
                       run  n_voters  n_samples  filter_fire_rate  tie_rate  refsel_rover_full_wtn
0                full_pool         7      10495            0.8566    0.0416                    1.0
1   LOO_minus_seamless_m4t         6      10495            0.8351    0.0348                    1.0
2     LOO_minus_whisper_v3         6      10495            0.8309    0.0309                    1.0
3  LOO_minus_fastconformer         6      10496            0.8407    0.0371                    1.0
4        LOO_minus_w2vbert         6      10495            0.7747    0.0261                    1.0
5         LOO_minus_hubert         6      10495            0.8411    0.0353                    1.0
6     LOO_minus_wav2vec_sb         6      10495            0.7482    0.0253                    1.0
7         LOO_minus_cohere         6      10496            0.8413    0.0409                    1.0

=== step3_model_dropout ===
           model  times_filtered_out  times_in_pool  filtered_out_rate
5     wav2vec_sb               39018          73467             0.5311
3        w2vbert               29852          73467             0.4063
1     whisper_v3               13295          73467             0.1810
0   seamless_m4t                8429          73467             0.1147
4         hubert                6275          73467             0.0854
2  fastconformer                4214          73466             0.0574
6         cohere                2518          73466             0.0343

=== step3_determinism ===
{
  "identical_outputs": 10495,
  "n": 10495,
  "deterministic": true,
  "main_kwargs": {
    "substitute": false,
    "normalize_final_letters": true
  }
}

=== step4_pairs_true ===
                            pair  adjacent  gap_wer  preserved_frac  resolved_95
0         fastconformer < hubert      True   0.6214             1.0         True
1                 xlsr < w2vbert      True   1.1621             1.0         True
2         cohere < fastconformer      True   1.6296             1.0         True
3                cohere < hubert     False   2.2511             1.0         True
4          hubert < seamless_m4t      True   2.9664             1.0         True
5   fastconformer < seamless_m4t     False   3.5878             1.0         True
6        whisper_v3 < whisper_v2      True   3.7042             1.0         True
7      seamless_m4t < whisper_v3      True   3.9295             1.0         True
8              whisper_v2 < xlsr      True   4.3988             1.0         True
9           w2vbert < wav2vec_sb      True   5.1348             1.0         True
10         cohere < seamless_m4t     False   5.2174             1.0         True
11          whisper_v2 < w2vbert     False   5.5610             1.0         True
12             xlsr < wav2vec_sb     False   6.2969             1.0         True
13           hubert < whisper_v3     False   6.8958             1.0         True
14    fastconformer < whisper_v3     False   7.5173             1.0         True
15     seamless_m4t < whisper_v2     False   7.6337             1.0         True
16             whisper_v3 < xlsr     False   8.1030             1.0         True
17           cohere < whisper_v3     False   9.1469             1.0         True
18          whisper_v3 < w2vbert     False   9.2652             1.0         True
19           hubert < whisper_v2     False  10.6000             1.0         True
20       whisper_v2 < wav2vec_sb     False  10.6958             1.0         True
21    fastconformer < whisper_v2     False  11.2215             1.0         True
22           seamless_m4t < xlsr     False  12.0325             1.0         True
23           cohere < whisper_v2     False  12.8511             1.0         True
24        seamless_m4t < w2vbert     False  13.1947             1.0         True
25       whisper_v3 < wav2vec_sb     False  14.4000             1.0         True
26                 hubert < xlsr     False  14.9989             1.0         True
27          fastconformer < xlsr     False  15.6203             1.0         True
28              hubert < w2vbert     False  16.1610             1.0         True
29       fastconformer < w2vbert     False  16.7824             1.0         True
30                 cohere < xlsr     False  17.2499             1.0         True
31     seamless_m4t < wav2vec_sb     False  18.3295             1.0         True
32              cohere < w2vbert     False  18.4121             1.0         True
33           hubert < wav2vec_sb     False  21.2958             1.0         True
34    fastconformer < wav2vec_sb     False  21.9172             1.0         True
35           cohere < wav2vec_sb     False  23.5469             1.0         True

=== step4_resolution_true ===
{
  "reference": "true",
  "n_boot": 10000,
  "n_samples": 10500,
  "min_resolved_gap_wer": 0.6214328627215382,
  "max_unresolved_gap_wer": 0.0,
  "n_resolved": 36,
  "n_pairs": 36
}

=== step4_pairs_pseudo ===
                            pair  adjacent  gap_wer  preserved_frac  resolved_95
0          hubert < seamless_m4t      True   0.7957             1.0         True
1                 xlsr < w2vbert      True   1.2512             1.0         True
2         cohere < fastconformer      True   1.4227             1.0         True
3         fastconformer < hubert      True   2.0128             1.0         True
4   fastconformer < seamless_m4t     False   2.8085             1.0         True
5      seamless_m4t < whisper_v3      True   3.3417             1.0         True
6        whisper_v3 < whisper_v2      True   3.3762             1.0         True
7                cohere < hubert     False   3.4355             1.0         True
8            hubert < whisper_v3     False   4.1374             1.0         True
9          cohere < seamless_m4t     False   4.2312             1.0         True
10             whisper_v2 < xlsr      True   4.8749             1.0         True
11          w2vbert < wav2vec_sb      True   5.2345             1.0         True
12          whisper_v2 < w2vbert     False   6.1261             1.0         True
13    fastconformer < whisper_v3     False   6.1502             1.0         True
14             xlsr < wav2vec_sb     False   6.4858             1.0         True
15     seamless_m4t < whisper_v2     False   6.7179             1.0         True
16           hubert < whisper_v2     False   7.5137             1.0         True
17           cohere < whisper_v3     False   7.5729             1.0         True
18             whisper_v3 < xlsr     False   8.2511             1.0         True
19          whisper_v3 < w2vbert     False   9.5024             1.0         True
20    fastconformer < whisper_v2     False   9.5264             1.0         True
21           cohere < whisper_v2     False  10.9492             1.0         True
22       whisper_v2 < wav2vec_sb     False  11.3606             1.0         True
23           seamless_m4t < xlsr     False  11.5928             1.0         True
24                 hubert < xlsr     False  12.3885             1.0         True
25        seamless_m4t < w2vbert     False  12.8441             1.0         True
26              hubert < w2vbert     False  13.6398             1.0         True
27          fastconformer < xlsr     False  14.4013             1.0         True
28       whisper_v3 < wav2vec_sb     False  14.7369             1.0         True
29       fastconformer < w2vbert     False  15.6526             1.0         True
30                 cohere < xlsr     False  15.8241             1.0         True
31              cohere < w2vbert     False  17.0753             1.0         True
32     seamless_m4t < wav2vec_sb     False  18.0786             1.0         True
33           hubert < wav2vec_sb     False  18.8743             1.0         True
34    fastconformer < wav2vec_sb     False  20.8871             1.0         True
35           cohere < wav2vec_sb     False  22.3098             1.0         True

=== step4_resolution_pseudo ===
{
  "reference": "pseudo",
  "n_boot": 10000,
  "n_samples": 10495,
  "min_resolved_gap_wer": 0.7957328864478725,
  "max_unresolved_gap_wer": 0.0,
  "n_resolved": 36,
  "n_pairs": 36
}

=== step5_baselines ===
                                         reference  n_models  spearman  kendall_b  spearman_exact_p_onetailed  kendall_exact_p_onetailed p_method  n_permutations  min_attainable_p  mean_abs_wer_err
0                          LOO ensemble (proposed)         9    1.0000     1.0000                      0.0000                     0.0000    exact          362880               0.0            1.0531
1                           full ensemble (biased)         9    1.0000     1.0000                      0.0000                     0.0000    exact          362880               0.0            1.7173
2                       single model: seamless_m4t         8    1.0000     1.0000                      0.0000                     0.0000    exact           40320               0.0            2.8048
3    LOO ensemble matched to n-1 (vs seamless_m4t)         8    1.0000     1.0000                      0.0000                     0.0000    exact           40320               0.0            1.0729
4                         single model: whisper_v3         8    0.8333     0.7143                      0.0077                     0.0071    exact           40320               0.0            5.1675
5      LOO ensemble matched to n-1 (vs whisper_v3)         8    1.0000     1.0000                      0.0000                     0.0000    exact           40320               0.0            0.9977
6                      single model: fastconformer         8    1.0000     1.0000                      0.0000                     0.0000    exact           40320               0.0            0.7331
7   LOO ensemble matched to n-1 (vs fastconformer)         8    1.0000     1.0000                      0.0000                     0.0000    exact           40320               0.0            1.1693
8                            single model: w2vbert         8    1.0000     1.0000                      0.0000                     0.0000    exact           40320               0.0           13.2048
9         LOO ensemble matched to n-1 (vs w2vbert)         8    1.0000     1.0000                      0.0000                     0.0000    exact           40320               0.0            1.0266
10                            single model: hubert         8    1.0000     1.0000                      0.0000                     0.0000    exact           40320               0.0            2.0030
11         LOO ensemble matched to n-1 (vs hubert)         8    1.0000     1.0000                      0.0000                     0.0000    exact           40320               0.0            1.0262
12                        single model: wav2vec_sb         8    0.9286     0.8571                      0.0011                     0.0009    exact           40320               0.0           17.8119
13     LOO ensemble matched to n-1 (vs wav2vec_sb)         8    1.0000     1.0000                      0.0000                     0.0000    exact           40320               0.0            1.0388
14                            single model: cohere         8    1.0000     1.0000                      0.0000                     0.0000    exact           40320               0.0            0.7447
15         LOO ensemble matched to n-1 (vs cohere)         8    1.0000     1.0000                      0.0000                     0.0000    exact           40320               0.0            1.1743

=== step6_pools ===
                                                                      pool  k  ensemble_wer_vs_true  ensemble_cer_vs_true  ranking_spearman  ranking_exact_p  ranking_kendall_b  ranking_kendall_exact_p  n_pairs_wrong  n_pairs_wrong_resolvable  worst_wrong_gap_wer            worst_wrong_pair
0                                 seamless_m4t+fastconformer+hubert+cohere  4                4.5334                1.2955            1.0000           0.0000             1.0000                   0.0000            0.0                       0.0               0.0000
1                         seamless_m4t+fastconformer+w2vbert+hubert+cohere  5                4.6029                1.2993            1.0000           0.0000             1.0000                   0.0000            0.0                       0.0               0.0000
2                      seamless_m4t+fastconformer+hubert+wav2vec_sb+cohere  5                4.6818                1.3442            1.0000           0.0000             1.0000                   0.0000            0.0                       0.0               0.0000
3                      seamless_m4t+whisper_v3+fastconformer+hubert+cohere  5                4.6893                1.3031            1.0000           0.0000             1.0000                   0.0000            0.0                       0.0               0.0000
4              seamless_m4t+fastconformer+w2vbert+hubert+wav2vec_sb+cohere  6                4.7852                1.4561            1.0000           0.0000             1.0000                   0.0000            0.0                       0.0               0.0000
5              seamless_m4t+whisper_v3+fastconformer+w2vbert+hubert+cohere  6                4.8002                1.4066            1.0000           0.0000             1.0000                   0.0000            0.0                       0.0               0.0000

# Ensemble - Evaluation Protocol

In [11]:
from stt_benchmarking.utils import evaluation_protocol
from stt_benchmarking.models.speech_to_text.arabic import ensemble
importlib.reload(evaluation_protocol)
importlib.reload(ensemble)

proto = evaluation_protocol.EvaluationProtocol(
    model_samples=dict(zip(model_names, all_models)),
    voters=voters,
    ensemble_factory=ensemble.HybridEnsemble,
    outdir="protocol_out/cv_validated_ensemble",
    n_boot=10000, seed=42, min_pool_size=3,
    main_kwargs={"substitute": False, "normalize_final_letters": True},
    suffix="_validated_ensemble_cv",
)
report = proto.run()

2026-09-22 18:07:01 - [stt_benchmarking.utils.evaluation_protocol.step0_decorrelation:265] INFO - Step 0 Finished.
2026-09-22 18:07:01 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:26<00:00, 401.53it/s]
2026-09-22 18:07:28 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:21<00:00, 487.19it/s]
2026-09-22 18:07:51 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:21<00:00, 494.46it/s]
2026-09-22 18:08:14 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:21<00:00, 481.01it/s]
2026-09-22 18:08:37 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:39<00:00, 263.74it/s]
2026-09-22 18:09:18 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:44<00:00, 236.12it/s]
2026-09-22 18:10:04 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:43<00:00, 241.57it/s]
2026-09-22 18:10:49 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:43<00:00, 244.01it/s]
2026-09-22 18:11:33 - [stt_benchmarking.utils.evaluation_protocol.step1_bias:295] INFO - Step 1 Finished.
2026-09-22 18:11:34 - [stt_benchmarking.utils.evaluation_protocol.step2_ranking:328] INFO - Step 2 Finished.
2026-09-22 18:11:34 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:34<00:00, 300.39it/s]
2026-09-22 18:12:12 - [stt_benchmarking.utils.evaluation_protocol.step3_pipeline:383] INFO - Step 3 Finished.
2026-09-22 18:12:16 - [stt_benchmarking.utils.evaluation_protocol.step4_bootstrap:427] INFO - Step 4 Finished.
2026-09-22 18:12:20 - [stt_benchmarking.utils.evaluation_protocol.step4_bootstrap:427] INFO - Step 4 Finished.
2026-09-22 18:12:39 - [stt_benchmarking.utils.evaluation_protocol.step5_baselines:471] INFO - Step 5 Finished.
2026-09-22 18:12:39 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:04<00:00, 2506.18it/s]
2026-09-22 18:12:44 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:05<00:00, 1912.25it/s]
2026-09-22 18:12:50 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:04<00:00, 2467.53it/s]
2026-09-22 18:12:54 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:05<00:00, 1880.88it/s]
2026-09-22 18:13:00 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:04<00:00, 2511.20it/s]
2026-09-22 18:13:05 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:04<00:00, 2426.05it/s]
2026-09-22 18:13:10 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:04<00:00, 2503.61it/s]
2026-09-22 18:13:16 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:04<00:00, 2420.74it/s]
2026-09-22 18:13:20 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:05<00:00, 1819.44it/s]
2026-09-22 18:13:27 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:04<00:00, 2419.03it/s]
2026-09-22 18:13:31 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:04<00:00, 2346.51it/s]
2026-09-22 18:13:36 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:06<00:00, 1707.01it/s]
2026-09-22 18:13:43 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:04<00:00, 2403.32it/s]
2026-09-22 18:13:48 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:04<00:00, 2515.66it/s]
2026-09-22 18:13:52 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:06<00:00, 1623.45it/s]
2026-09-22 18:13:59 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:04<00:00, 2421.39it/s]
2026-09-22 18:14:04 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:04<00:00, 2481.58it/s]
2026-09-22 18:14:09 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:04<00:00, 2404.04it/s]
2026-09-22 18:14:14 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:06<00:00, 1586.15it/s]
2026-09-22 18:14:21 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:04<00:00, 2410.33it/s]
2026-09-22 18:14:27 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:04<00:00, 2366.20it/s]
2026-09-22 18:14:32 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:04<00:00, 2440.18it/s]
2026-09-22 18:14:37 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:07<00:00, 1491.54it/s]
2026-09-22 18:14:44 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:04<00:00, 2509.34it/s]
2026-09-22 18:14:49 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:04<00:00, 2420.84it/s]
2026-09-22 18:14:54 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:04<00:00, 2505.58it/s]
2026-09-22 18:15:00 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:07<00:00, 1423.13it/s]
2026-09-22 18:15:09 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:04<00:00, 2484.34it/s]
2026-09-22 18:15:14 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:04<00:00, 2452.68it/s]
2026-09-22 18:15:20 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:04<00:00, 2606.68it/s]
2026-09-22 18:15:25 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:04<00:00, 2474.83it/s]
2026-09-22 18:15:31 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:07<00:00, 1368.82it/s]
2026-09-22 18:15:40 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:04<00:00, 2496.33it/s]
2026-09-22 18:15:46 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:04<00:00, 2401.78it/s]
2026-09-22 18:15:53 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:04<00:00, 2467.64it/s]
2026-09-22 18:15:59 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:13<00:00, 759.94it/s]
2026-09-22 18:16:16 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:13<00:00, 768.16it/s]
2026-09-22 18:16:36 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:13<00:00, 759.86it/s]
2026-09-22 18:16:53 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:13<00:00, 767.30it/s]
2026-09-22 18:17:10 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:13<00:00, 762.23it/s]
2026-09-22 18:17:26 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:13<00:00, 765.53it/s]
2026-09-22 18:17:43 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:13<00:00, 765.03it/s]
2026-09-22 18:18:04 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:13<00:00, 757.54it/s]
2026-09-22 18:18:21 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:13<00:00, 763.80it/s]
2026-09-22 18:18:37 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:13<00:00, 757.27it/s]
2026-09-22 18:18:54 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:13<00:00, 764.20it/s]
2026-09-22 18:19:11 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:13<00:00, 760.74it/s]
2026-09-22 18:19:32 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:13<00:00, 752.24it/s]
2026-09-22 18:19:49 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:13<00:00, 760.47it/s]
2026-09-22 18:20:06 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:13<00:00, 767.72it/s]
2026-09-22 18:20:22 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:13<00:00, 763.29it/s]
2026-09-22 18:20:39 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:13<00:00, 756.89it/s]
2026-09-22 18:20:56 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:13<00:00, 771.71it/s]
2026-09-22 18:21:13 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:19<00:00, 545.63it/s]
2026-09-22 18:21:35 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:13<00:00, 769.11it/s]
2026-09-22 18:21:51 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:13<00:00, 759.95it/s]
2026-09-22 18:22:08 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:13<00:00, 753.37it/s]
2026-09-22 18:22:25 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:13<00:00, 764.66it/s]
2026-09-22 18:22:41 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:13<00:00, 755.94it/s]
2026-09-22 18:22:58 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:13<00:00, 769.59it/s]
2026-09-22 18:23:15 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:19<00:00, 528.92it/s]
2026-09-22 18:23:38 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:13<00:00, 769.25it/s]
2026-09-22 18:23:54 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:13<00:00, 764.68it/s]
2026-09-22 18:24:11 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:13<00:00, 760.46it/s]
2026-09-22 18:24:28 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:13<00:00, 758.76it/s]
2026-09-22 18:24:44 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:13<00:00, 758.36it/s]
2026-09-22 18:25:01 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:13<00:00, 767.47it/s]
2026-09-22 18:25:18 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:13<00:00, 761.39it/s]
2026-09-22 18:25:35 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:13<00:00, 766.08it/s]
2026-09-22 18:25:58 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:13<00:00, 754.38it/s]
2026-09-22 18:26:15 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:17<00:00, 611.98it/s]
2026-09-22 18:26:34 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:17<00:00, 609.57it/s]
2026-09-22 18:26:53 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:17<00:00, 607.89it/s]
2026-09-22 18:27:12 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:17<00:00, 612.02it/s]
2026-09-22 18:27:31 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:16<00:00, 622.91it/s]
2026-09-22 18:27:50 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:17<00:00, 616.47it/s]
2026-09-22 18:28:08 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:17<00:00, 612.78it/s]
2026-09-22 18:28:27 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:17<00:00, 617.47it/s]
2026-09-22 18:28:46 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:25<00:00, 418.84it/s]
2026-09-22 18:29:13 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:16<00:00, 618.46it/s]
2026-09-22 18:29:31 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:17<00:00, 613.73it/s]
2026-09-22 18:29:50 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:16<00:00, 622.02it/s]
2026-09-22 18:30:09 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True

=== skipped_empty_gt ===
0

=== main_kwargs_applied ===
{
  "substitute": false,
  "normalize_final_letters": true
}

=== main_kwargs_dropped ===
[]

=== step0_cross_wer ===
               seamless_m4t  whisper_v3  whisper_v2  fastconformer   xlsr  w2vbert  hubert  wav2vec_sb  cohere
seamless_m4t           0.00       15.80       19.40          11.85  24.88    25.77   13.86       30.72   10.23
whisper_v3            15.80        0.00       14.77          15.00  25.50    26.23   17.06       31.71   13.88
whisper_v2            19.40       14.77        0.00          18.63  28.03    28.83   20.50       33.99   17.57
fastconformer         11.85       15.00       18.63           0.00  22.77    24.06   10.30       28.80    7.05
xlsr                  24.88       25.50       28.03          22.77   0.00    31.68   23.49       31.10   22.29
w2vbert               25.77       26.23       28.83          24.06  31.68     0.00   25.33       37.20   23.32
hubert                13.86       17.06       20.50          10.30  23.49    25.33    0.00       29.58    9.23
wav2vec_sb            30.72       31.71       33.99          28.80  31.10    37.20   29.58        0.00   28.81
cohere                10.23       13.88       17.57           7.05  22.29    23.32    9.23       28.81    0.00

=== step0_err_corr ===
               seamless_m4t  whisper_v3  whisper_v2  fastconformer    xlsr  w2vbert  hubert  wav2vec_sb  cohere
seamless_m4t         1.0000      0.4930      0.4572         0.4468  0.3933   0.3559  0.3527      0.3807  0.4864
whisper_v3           0.4930      1.0000      0.6827         0.4367  0.4573   0.4390  0.3487      0.4105  0.4442
whisper_v2           0.4572      0.6827      1.0000         0.3904  0.4453   0.4221  0.3313      0.4116  0.4045
fastconformer        0.4468      0.4367      0.3904         1.0000  0.4100   0.3553  0.4155      0.4007  0.5511
xlsr                 0.3933      0.4573      0.4453         0.4100  1.0000   0.4547  0.4217      0.6335  0.3863
w2vbert              0.3559      0.4390      0.4221         0.3553  0.4547   1.0000  0.3421      0.4296  0.3379
hubert               0.3527      0.3487      0.3313         0.4155  0.4217   0.3421  1.0000      0.4044  0.3997
wav2vec_sb           0.3807      0.4105      0.4116         0.4007  0.6335   0.4296  0.4044      1.0000  0.3594
cohere               0.4864      0.4442      0.4045         0.5511  0.3863   0.3379  0.3997      0.3594  1.0000

=== step0_flags ===
                         pair  cross_wer  err_corr                                                            note
0  seamless_m4t|fastconformer      11.85    0.4468  unusually similar hypotheses - suspect shared lab/data/teacher
1         seamless_m4t|hubert      13.86    0.3527  unusually similar hypotheses - suspect shared lab/data/teacher
2         seamless_m4t|cohere      10.23    0.4864  unusually similar hypotheses - suspect shared lab/data/teacher
3           whisper_v3|cohere      13.88    0.4442  unusually similar hypotheses - suspect shared lab/data/teacher
4        fastconformer|hubert      10.30    0.4155  unusually similar hypotheses - suspect shared lab/data/teacher
5        fastconformer|cohere       7.05    0.5511  unusually similar hypotheses - suspect shared lab/data/teacher
6               hubert|cohere       9.23    0.3997  unusually similar hypotheses - suspect shared lab/data/teacher

=== step1_bias ===
           model                  role  n_samples  spearman_full  spearman_loo  kendall_full  kendall_loo  delta_spearman  delta_kendall
0         cohere                 voter      10495         0.5883        0.5824        0.5633       0.5539         -0.0059        -0.0094
1  fastconformer                 voter      10495         0.7077        0.7088        0.6771       0.6755          0.0011        -0.0016
2         hubert                 voter      10495         0.7210        0.7077        0.6907       0.6740         -0.0133        -0.0167
3   seamless_m4t                 voter      10495         0.7979        0.8062        0.7630       0.7692          0.0084         0.0061
4     whisper_v3                 voter      10495         0.8672        0.8824        0.8275       0.8449          0.0152         0.0174
5     whisper_v2  ranked_only(control)      10495         0.9034        0.9034        0.8641       0.8641          0.0000         0.0000
6        w2vbert                 voter      10495         0.9228        0.9302        0.8800       0.8892          0.0074         0.0091
7           xlsr  ranked_only(control)      10495         0.9279        0.9279        0.8876       0.8876          0.0000         0.0000
8     wav2vec_sb                 voter      10495         0.9519        0.9560        0.9144       0.9205          0.0041         0.0061

=== step2_ranking ===
           model         role  n_samples  wer_true  cer_true  wer_pseudo_loo  cer_pseudo_loo  rank_true  rank_pseudo  wer_compression
0         cohere        voter      10496    5.5591    1.5028          5.4842          1.6077          1            1           0.0749
1  fastconformer        voter      10496    7.1898    2.1580          6.8721          2.0654          2            2           0.3178
2         hubert        voter      10495    7.8081    2.1291          9.0306          2.4110          3            3          -1.2225
3   seamless_m4t        voter      10495   10.7671    3.4897          9.7145          3.3357          4            4           1.0526
4     whisper_v3        voter      10495   14.7106    4.6360         13.0371          4.1872          5            5           1.6735
5     whisper_v2  ranked_only      10495   18.4155    6.0072         16.4124          5.4924          6            6           2.0030
6           xlsr  ranked_only      10495   22.8174    6.4330         21.3202          5.9605          7            7           1.4972
7        w2vbert        voter      10495   23.9822    6.5829         22.6039          6.2056          8            8           1.3783
8     wav2vec_sb        voter      10495   29.1187    9.6559         27.8553          9.2316          9            9           1.2634

=== step2_stats ===
{
  "n_models": 9,
  "spearman": 1.0,
  "kendall_b": 1.0,
  "spearman_exact_p_onetailed": 2.7557319223985893e-06,
  "kendall_exact_p_onetailed": 2.7557319223985893e-06,
  "p_method": "exact",
  "n_permutations": 362880,
  "min_attainable_p": 2.7557319223985893e-06,
  "pearson": 0.9952967572835393,
  "pearson_p": 2.3385162213214438e-08,
  "mean_wer_compression": 0.893126578792571
}

=== step3_runs ===
                       run  n_voters  n_samples  filter_fire_rate  tie_rate  refsel_longest_match_validation  refsel_most_common_words
0                full_pool         7      10495            0.8568    0.0406                           0.7316                    0.2684
1   LOO_minus_seamless_m4t         6      10495            0.8332    0.0344                           0.7644                    0.2356
2     LOO_minus_whisper_v3         6      10495            0.8289    0.0309                           0.7683                    0.2317
3  LOO_minus_fastconformer         6      10496            0.8380    0.0369                           0.7570                    0.2430
4        LOO_minus_w2vbert         6      10495            0.7719    0.0263                           0.8016                    0.1984
5         LOO_minus_hubert         6      10495            0.8388    0.0353                           0.7597                    0.2403
6     LOO_minus_wav2vec_sb         6      10495            0.7447    0.0258                           0.8188                    0.1812
7         LOO_minus_cohere         6      10496            0.8396    0.0407                           0.7487                    0.2513

=== step3_model_dropout ===
           model  times_filtered_out  times_in_pool  filtered_out_rate
5     wav2vec_sb               38946          73467             0.5301
3        w2vbert               29796          73467             0.4056
1     whisper_v3               13227          73467             0.1800
0   seamless_m4t                8356          73467             0.1137
4         hubert                6225          73467             0.0847
2  fastconformer                4157          73466             0.0566
6         cohere                2447          73466             0.0333

=== step3_determinism ===
{
  "identical_outputs": 10495,
  "n": 10495,
  "deterministic": true,
  "main_kwargs": {
    "substitute": false,
    "normalize_final_letters": true
  }
}

=== step4_pairs_true ===
                            pair  adjacent  gap_wer  preserved_frac  resolved_95
0         fastconformer < hubert      True   0.6214             1.0         True
1                 xlsr < w2vbert      True   1.1621             1.0         True
2         cohere < fastconformer      True   1.6296             1.0         True
3                cohere < hubert     False   2.2511             1.0         True
4          hubert < seamless_m4t      True   2.9664             1.0         True
5   fastconformer < seamless_m4t     False   3.5878             1.0         True
6        whisper_v3 < whisper_v2      True   3.7042             1.0         True
7      seamless_m4t < whisper_v3      True   3.9295             1.0         True
8              whisper_v2 < xlsr      True   4.3988             1.0         True
9           w2vbert < wav2vec_sb      True   5.1348             1.0         True
10         cohere < seamless_m4t     False   5.2174             1.0         True
11          whisper_v2 < w2vbert     False   5.5610             1.0         True
12             xlsr < wav2vec_sb     False   6.2969             1.0         True
13           hubert < whisper_v3     False   6.8958             1.0         True
14    fastconformer < whisper_v3     False   7.5173             1.0         True
15     seamless_m4t < whisper_v2     False   7.6337             1.0         True
16             whisper_v3 < xlsr     False   8.1030             1.0         True
17           cohere < whisper_v3     False   9.1469             1.0         True
18          whisper_v3 < w2vbert     False   9.2652             1.0         True
19           hubert < whisper_v2     False  10.6000             1.0         True
20       whisper_v2 < wav2vec_sb     False  10.6958             1.0         True
21    fastconformer < whisper_v2     False  11.2215             1.0         True
22           seamless_m4t < xlsr     False  12.0325             1.0         True
23           cohere < whisper_v2     False  12.8511             1.0         True
24        seamless_m4t < w2vbert     False  13.1947             1.0         True
25       whisper_v3 < wav2vec_sb     False  14.4000             1.0         True
26                 hubert < xlsr     False  14.9989             1.0         True
27          fastconformer < xlsr     False  15.6203             1.0         True
28              hubert < w2vbert     False  16.1610             1.0         True
29       fastconformer < w2vbert     False  16.7824             1.0         True
30                 cohere < xlsr     False  17.2499             1.0         True
31     seamless_m4t < wav2vec_sb     False  18.3295             1.0         True
32              cohere < w2vbert     False  18.4121             1.0         True
33           hubert < wav2vec_sb     False  21.2958             1.0         True
34    fastconformer < wav2vec_sb     False  21.9172             1.0         True
35           cohere < wav2vec_sb     False  23.5469             1.0         True

=== step4_resolution_true ===
{
  "reference": "true",
  "n_boot": 10000,
  "n_samples": 10500,
  "min_resolved_gap_wer": 0.6214328627215382,
  "max_unresolved_gap_wer": 0.0,
  "n_resolved": 36,
  "n_pairs": 36
}

=== step4_pairs_pseudo ===
                            pair  adjacent  gap_wer  preserved_frac  resolved_95
0          hubert < seamless_m4t      True   0.6839          0.9996         True
1                 xlsr < w2vbert      True   1.2837          1.0000         True
2         cohere < fastconformer      True   1.3879          1.0000         True
3         fastconformer < hubert      True   2.1603          1.0000         True
4   fastconformer < seamless_m4t     False   2.8442          1.0000         True
5      seamless_m4t < whisper_v3      True   3.3226          1.0000         True
6        whisper_v3 < whisper_v2      True   3.3753          1.0000         True
7                cohere < hubert     False   3.5482          1.0000         True
8            hubert < whisper_v3     False   4.0065          1.0000         True
9          cohere < seamless_m4t     False   4.2321          1.0000         True
10             whisper_v2 < xlsr      True   4.9077          1.0000         True
11          w2vbert < wav2vec_sb      True   5.2514          1.0000         True
12    fastconformer < whisper_v3     False   6.1668          1.0000         True
13          whisper_v2 < w2vbert     False   6.1915          1.0000         True
14             xlsr < wav2vec_sb     False   6.5351          1.0000         True
15     seamless_m4t < whisper_v2     False   6.6979          1.0000         True
16           hubert < whisper_v2     False   7.3818          1.0000         True
17           cohere < whisper_v3     False   7.5547          1.0000         True
18             whisper_v3 < xlsr     False   8.2831          1.0000         True
19    fastconformer < whisper_v2     False   9.5421          1.0000         True
20          whisper_v3 < w2vbert     False   9.5668          1.0000         True
21           cohere < whisper_v2     False  10.9300          1.0000         True
22       whisper_v2 < wav2vec_sb     False  11.4428          1.0000         True
23           seamless_m4t < xlsr     False  11.6056          1.0000         True
24                 hubert < xlsr     False  12.2895          1.0000         True
25        seamless_m4t < w2vbert     False  12.8894          1.0000         True
26              hubert < w2vbert     False  13.5733          1.0000         True
27          fastconformer < xlsr     False  14.4498          1.0000         True
28       whisper_v3 < wav2vec_sb     False  14.8182          1.0000         True
29       fastconformer < w2vbert     False  15.7336          1.0000         True
30                 cohere < xlsr     False  15.8378          1.0000         True
31              cohere < w2vbert     False  17.1215          1.0000         True
32     seamless_m4t < wav2vec_sb     False  18.1407          1.0000         True
33           hubert < wav2vec_sb     False  18.8247          1.0000         True
34    fastconformer < wav2vec_sb     False  20.9850          1.0000         True
35           cohere < wav2vec_sb     False  22.3729          1.0000         True

=== step4_resolution_pseudo ===
{
  "reference": "pseudo",
  "n_boot": 10000,
  "n_samples": 10495,
  "min_resolved_gap_wer": 0.6839286447628208,
  "max_unresolved_gap_wer": 0.0,
  "n_resolved": 36,
  "n_pairs": 36
}

=== step5_baselines ===
                                         reference  n_models  spearman  kendall_b  spearman_exact_p_onetailed  kendall_exact_p_onetailed p_method  n_permutations  min_attainable_p  mean_abs_wer_err
0                          LOO ensemble (proposed)         9    1.0000     1.0000                      0.0000                     0.0000    exact          362880               0.0            1.1648
1                           full ensemble (biased)         9    1.0000     1.0000                      0.0000                     0.0000    exact          362880               0.0            1.8296
2                       single model: seamless_m4t         8    1.0000     1.0000                      0.0000                     0.0000    exact           40320               0.0            2.8048
3    LOO ensemble matched to n-1 (vs seamless_m4t)         8    1.0000     1.0000                      0.0000                     0.0000    exact           40320               0.0            1.1788
4                         single model: whisper_v3         8    0.8333     0.7143                      0.0077                     0.0071    exact           40320               0.0            5.1675
5      LOO ensemble matched to n-1 (vs whisper_v3)         8    1.0000     1.0000                      0.0000                     0.0000    exact           40320               0.0            1.1012
6                      single model: fastconformer         8    1.0000     1.0000                      0.0000                     0.0000    exact           40320               0.0            0.7331
7   LOO ensemble matched to n-1 (vs fastconformer)         8    1.0000     1.0000                      0.0000                     0.0000    exact           40320               0.0            1.2707
8                            single model: w2vbert         8    1.0000     1.0000                      0.0000                     0.0000    exact           40320               0.0           13.2048
9         LOO ensemble matched to n-1 (vs w2vbert)         8    1.0000     1.0000                      0.0000                     0.0000    exact           40320               0.0            1.1381
10                            single model: hubert         8    1.0000     1.0000                      0.0000                     0.0000    exact           40320               0.0            2.0030
11         LOO ensemble matched to n-1 (vs hubert)         8    1.0000     1.0000                      0.0000                     0.0000    exact           40320               0.0            1.1576
12                        single model: wav2vec_sb         8    0.9286     0.8571                      0.0011                     0.0009    exact           40320               0.0           17.8119
13     LOO ensemble matched to n-1 (vs wav2vec_sb)         8    1.0000     1.0000                      0.0000                     0.0000    exact           40320               0.0            1.1525
14                            single model: cohere         8    1.0000     1.0000                      0.0000                     0.0000    exact           40320               0.0            0.7447
15         LOO ensemble matched to n-1 (vs cohere)         8    1.0000     1.0000                      0.0000                     0.0000    exact           40320               0.0            1.3010

=== step6_pools ===
                                                                      pool  k  ensemble_wer_vs_true  ensemble_cer_vs_true  ranking_spearman  ranking_exact_p  ranking_kendall_b  ranking_kendall_exact_p  n_pairs_wrong  n_pairs_wrong_resolvable  worst_wrong_gap_wer            worst_wrong_pair
0                                 seamless_m4t+fastconformer+hubert+cohere  4                4.4357                1.2548            1.0000           0.0000             1.0000                   0.0000            0.0                       0.0               0.0000
1                         seamless_m4t+fastconformer+w2vbert+hubert+cohere  5                4.4752                1.2711            1.0000           0.0000             1.0000                   0.0000            0.0                       0.0               0.0000
2                      seamless_m4t+fastconformer+hubert+wav2vec_sb+cohere  5                4.5297                1.2993            1.0000           0.0000             1.0000                   0.0000            0.0                       0.0               0.0000
3                      seamless_m4t+whisper_v3+fastconformer+hubert+cohere  5                4.5860                1.2753            1.0000           0.0000             1.0000                   0.0000            0.0                       0.0               0.0000

In [9]:
from stt_benchmarking.utils import deployment_protocol as dp
from stt_benchmarking.models.speech_to_text.arabic import ensemble

importlib.reload(dp)

dp = dp.DeploymentProtocol.from_hypotheses(
    model_samples=dict(zip(model_names, all_models)),
    voters=model_names,
    ensemble_factory=ensemble.HybridEnsemble,
    main_kwargs={"substitute": False, "normalize_final_letters": True},
    n_boot=1000, seed=42, min_pool_size=3,
    outdir="deployment_out/cv_validated_all_voting_ensemble", suffix="cv_validated_all_voting_ensemble")
    
r = dp.run(weighting="filtration")

2026-09-22 19:01:38 - [stt_benchmarking.utils.decorators.execution_time_wrapper:21] INFO - Execution time for function cross_wer: 0 minutes 9 seconds (9.5s)
2026-09-22 19:01:38 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:31<00:00, 329.50it/s]
2026-09-22 19:02:10 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:31<00:00, 329.41it/s]
2026-09-22 19:02:43 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:31<00:00, 330.43it/s]
2026-09-22 19:03:16 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:31<00:00, 329.77it/s]
2026-09-22 19:03:48 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:32<00:00, 327.00it/s]
2026-09-22 19:04:21 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:32<00:00, 327.15it/s]
2026-09-22 19:04:53 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:32<00:00, 324.39it/s]
2026-09-22 19:05:26 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:31<00:00, 328.18it/s]
2026-09-22 19:05:59 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:31<00:00, 329.93it/s]
2026-09-22 19:06:31 - [stt_benchmarking.utils.decorators.execution_time_wrapper:21] INFO - Execution time for function ranking: 4 minutes 53 seconds (293.1s)
2026-09-22 19:06:31 - [stt_benchmarking.utils.decorators.execution_time_wrapper:21] INFO - Execution time for function ranking: 0 minutes 0 seconds (0.1s)
2026-09-22 19:06:31 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:13<00:00, 751.69it/s]
2026-09-22 19:06:46 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:15<00:00, 696.23it/s]
2026-09-22 19:07:01 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:14<00:00, 748.27it/s]
2026-09-22 19:07:16 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:15<00:00, 690.80it/s]
2026-09-22 19:07:31 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:14<00:00, 749.33it/s]
2026-09-22 19:07:45 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:15<00:00, 684.05it/s]
2026-09-22 19:08:01 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:14<00:00, 746.10it/s]
2026-09-22 19:08:15 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:15<00:00, 670.67it/s]
2026-09-22 19:08:31 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:13<00:00, 771.46it/s]
2026-09-22 19:08:44 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:13<00:00, 766.54it/s]
2026-09-22 19:08:58 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:15<00:00, 679.30it/s]
2026-09-22 19:09:14 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:13<00:00, 766.02it/s]
2026-09-22 19:09:28 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:13<00:00, 772.06it/s]
2026-09-22 19:09:42 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:13<00:00, 768.06it/s]
2026-09-22 19:09:57 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:13<00:00, 769.82it/s]
2026-09-22 19:10:11 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:13<00:00, 767.07it/s]
2026-09-22 19:10:25 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:16<00:00, 649.49it/s]
2026-09-22 19:10:41 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:13<00:00, 770.99it/s]
2026-09-22 19:10:55 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:13<00:00, 765.49it/s]
2026-09-22 19:11:09 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:13<00:00, 774.38it/s]
2026-09-22 19:11:23 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:13<00:00, 774.43it/s]
2026-09-22 19:11:39 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:13<00:00, 775.21it/s]
2026-09-22 19:11:53 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:13<00:00, 766.00it/s]
2026-09-22 19:12:07 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:16<00:00, 630.73it/s]
2026-09-22 19:12:24 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:13<00:00, 766.01it/s]
2026-09-22 19:12:37 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:13<00:00, 755.17it/s]
2026-09-22 19:12:52 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:14<00:00, 745.03it/s]
2026-09-22 19:13:06 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:13<00:00, 757.38it/s]
2026-09-22 19:13:20 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:17<00:00, 604.97it/s]
2026-09-22 19:13:37 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:13<00:00, 759.15it/s]
2026-09-22 19:13:51 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:13<00:00, 752.08it/s]
2026-09-22 19:14:05 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:14<00:00, 747.13it/s]
2026-09-22 19:14:20 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:13<00:00, 756.62it/s]
2026-09-22 19:14:34 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:13<00:00, 755.40it/s]
2026-09-22 19:14:52 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:13<00:00, 764.45it/s]
2026-09-22 19:15:06 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:13<00:00, 758.13it/s]
2026-09-22 19:15:20 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:13<00:00, 760.53it/s]
2026-09-22 19:15:34 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:13<00:00, 766.42it/s]
2026-09-22 19:15:47 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:18<00:00, 574.34it/s]
2026-09-22 19:16:06 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:13<00:00, 758.52it/s]
2026-09-22 19:16:20 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:13<00:00, 762.59it/s]
2026-09-22 19:16:34 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:13<00:00, 755.53it/s]
2026-09-22 19:16:48 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:13<00:00, 762.28it/s]
2026-09-22 19:17:02 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:13<00:00, 751.01it/s]
2026-09-22 19:17:16 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:18<00:00, 567.84it/s]
2026-09-22 19:17:35 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:13<00:00, 765.38it/s]
2026-09-22 19:17:48 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:13<00:00, 752.69it/s]
2026-09-22 19:18:03 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:14<00:00, 745.94it/s]
2026-09-22 19:18:17 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:13<00:00, 752.69it/s]
2026-09-22 19:18:31 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:14<00:00, 747.67it/s]
2026-09-22 19:18:45 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:13<00:00, 753.70it/s]
2026-09-22 19:18:59 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:19<00:00, 540.19it/s]
2026-09-22 19:19:19 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:13<00:00, 753.04it/s]
2026-09-22 19:19:33 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:13<00:00, 759.84it/s]
2026-09-22 19:19:47 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:14<00:00, 748.94it/s]
2026-09-22 19:20:01 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:13<00:00, 750.92it/s]
2026-09-22 19:20:15 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:13<00:00, 752.03it/s]
2026-09-22 19:20:29 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:13<00:00, 755.40it/s]
2026-09-22 19:20:43 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:13<00:00, 756.08it/s]
2026-09-22 19:20:57 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:13<00:00, 755.40it/s]
2026-09-22 19:21:18 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:13<00:00, 760.79it/s]
2026-09-22 19:21:32 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:13<00:00, 757.33it/s]
2026-09-22 19:21:46 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:13<00:00, 755.45it/s]
2026-09-22 19:22:00 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:14<00:00, 749.27it/s]
2026-09-22 19:22:14 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:13<00:00, 754.51it/s]
2026-09-22 19:22:28 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:13<00:00, 755.08it/s]
2026-09-22 19:22:42 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:14<00:00, 749.67it/s]
2026-09-22 19:22:56 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:20<00:00, 501.67it/s]
2026-09-22 19:23:17 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:13<00:00, 754.04it/s]
2026-09-22 19:23:31 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:13<00:00, 763.37it/s]
2026-09-22 19:23:45 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:13<00:00, 755.05it/s]
2026-09-22 19:23:59 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:14<00:00, 748.11it/s]
2026-09-22 19:24:14 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:13<00:00, 753.82it/s]
2026-09-22 19:24:28 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:14<00:00, 742.21it/s]
2026-09-22 19:24:42 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:13<00:00, 750.95it/s]
2026-09-22 19:24:56 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:13<00:00, 753.72it/s]
2026-09-22 19:25:10 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:13<00:00, 751.12it/s]
2026-09-22 19:25:24 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:13<00:00, 758.11it/s]
2026-09-22 19:25:46 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:13<00:00, 753.04it/s]
2026-09-22 19:26:00 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:13<00:00, 755.06it/s]
2026-09-22 19:26:14 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:13<00:00, 752.65it/s]
2026-09-22 19:26:28 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:13<00:00, 751.12it/s]
2026-09-22 19:26:42 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:14<00:00, 746.12it/s]
2026-09-22 19:26:57 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:13<00:00, 755.65it/s]

In [12]:
from stt_benchmarking.utils import deployment_protocol as dp
from stt_benchmarking.models.speech_to_text.arabic import ensemble

importlib.reload(dp)

dp = dp.DeploymentProtocol.from_hypotheses(
    model_samples={n: s for n, s in zip(model_names, all_models) if n in voters},
    voters=voters,
    ensemble_factory=ensemble.HybridEnsemble,
    main_kwargs={"substitute": False, "normalize_final_letters": True},
    n_boot=1000, seed=42, min_pool_size=3,
    outdir="deployment_out/cv_validated_voters_ensemble", suffix="cv_validated_voters_ensemble")

r = dp.run(weighting="filtration")

2026-09-22 18:37:16 - [stt_benchmarking.utils.decorators.execution_time_wrapper:21] INFO - Execution time for function cross_wer: 0 minutes 12 seconds (12.6s)
2026-09-22 18:37:17 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:21<00:00, 489.75it/s]
2026-09-22 18:37:38 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:21<00:00, 496.80it/s]
2026-09-22 18:38:00 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:21<00:00, 494.15it/s]
2026-09-22 18:38:22 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:21<00:00, 496.14it/s]
2026-09-22 18:38:43 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:21<00:00, 496.46it/s]
2026-09-22 18:39:05 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:20<00:00, 502.99it/s]
2026-09-22 18:39:26 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:21<00:00, 499.73it/s]
2026-09-22 18:39:48 - [stt_benchmarking.utils.decorators.execution_time_wrapper:21] INFO - Execution time for function ranking: 2 minutes 31 seconds (151.2s)
2026-09-22 18:39:48 - [stt_benchmarking.utils.decorators.execution_time_wrapper:21] INFO - Execution time for function ranking: 0 minutes 0 seconds (0.1s)
2026-09-22 18:39:48 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:13<00:00, 770.58it/s]
2026-09-22 18:40:02 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:13<00:00, 770.40it/s]
2026-09-22 18:40:15 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:13<00:00, 762.67it/s]
2026-09-22 18:40:29 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:13<00:00, 771.83it/s]
2026-09-22 18:40:43 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:13<00:00, 763.62it/s]
2026-09-22 18:40:57 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:13<00:00, 755.63it/s]
2026-09-22 18:41:22 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:13<00:00, 768.76it/s]
2026-09-22 18:41:35 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:13<00:00, 769.41it/s]
2026-09-22 18:41:49 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:13<00:00, 771.06it/s]
2026-09-22 18:42:03 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:13<00:00, 759.33it/s]
2026-09-22 18:42:17 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:13<00:00, 761.93it/s]
2026-09-22 18:42:31 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:13<00:00, 755.40it/s]
2026-09-22 18:42:45 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:13<00:00, 763.00it/s]
2026-09-22 18:42:59 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:13<00:00, 760.02it/s]
2026-09-22 18:43:13 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:13<00:00, 772.06it/s]
2026-09-22 18:43:27 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:13<00:00, 766.83it/s]
2026-09-22 18:43:40 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:13<00:00, 759.22it/s]
2026-09-22 18:43:54 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:13<00:00, 760.89it/s]
2026-09-22 18:44:08 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:13<00:00, 756.98it/s]
2026-09-22 18:44:22 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:13<00:00, 762.26it/s]
2026-09-22 18:44:36 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:25<00:00, 411.36it/s]
2026-09-22 18:45:02 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:13<00:00, 760.81it/s]
2026-09-22 18:45:16 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:13<00:00, 769.36it/s]
2026-09-22 18:45:30 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:13<00:00, 767.85it/s]
2026-09-22 18:45:44 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:13<00:00, 774.85it/s]
2026-09-22 18:45:57 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:13<00:00, 760.69it/s]
2026-09-22 18:46:11 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:13<00:00, 756.94it/s]
2026-09-22 18:46:25 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:13<00:00, 762.07it/s]
2026-09-22 18:46:39 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:14<00:00, 748.72it/s]
2026-09-22 18:46:53 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:13<00:00, 759.03it/s]
2026-09-22 18:47:08 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:13<00:00, 755.47it/s]
2026-09-22 18:47:22 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:13<00:00, 768.87it/s]
2026-09-22 18:47:35 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:13<00:00, 763.00it/s]
2026-09-22 18:47:49 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:13<00:00, 762.20it/s]
2026-09-22 18:48:03 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:13<00:00, 753.10it/s]
2026-09-22 18:48:17 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:17<00:00, 610.98it/s]
2026-09-22 18:48:35 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:17<00:00, 602.36it/s]
2026-09-22 18:48:52 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:17<00:00, 612.70it/s]
2026-09-22 18:49:10 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:17<00:00, 611.58it/s]
2026-09-22 18:49:40 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:16<00:00, 617.68it/s]
2026-09-22 18:49:58 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:17<00:00, 608.81it/s]
2026-09-22 18:50:15 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:17<00:00, 604.54it/s]
2026-09-22 18:50:33 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:17<00:00, 612.13it/s]
2026-09-22 18:50:50 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:17<00:00, 610.17it/s]
2026-09-22 18:51:07 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:17<00:00, 612.04it/s]
2026-09-22 18:51:25 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:17<00:00, 612.32it/s]
2026-09-22 18:51:42 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:16<00:00, 618.18it/s]
2026-09-22 18:51:59 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:17<00:00, 605.49it/s]
2026-09-22 18:52:17 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:17<00:00, 611.10it/s]
2026-09-22 18:52:34 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:17<00:00, 608.30it/s]
2026-09-22 18:52:51 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:17<00:00, 606.32it/s]
2026-09-22 18:53:09 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:17<00:00, 614.04it/s]
2026-09-22 18:53:26 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:17<00:00, 612.60it/s]
2026-09-22 18:53:43 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:17<00:00, 614.93it/s]
2026-09-22 18:54:01 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:17<00:00, 607.82it/s]
2026-09-22 18:54:18 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:17<00:00, 607.81it/s]
2026-09-22 18:54:36 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:41<00:00, 254.90it/s]
2026-09-22 18:55:17 - [stt_benchmarking.utils.decorators.execution_time_wrapper:21] INFO - Execution time for function model_filtration: 15 minutes 29 seconds (929.6s)
2026-09-22 18:55:17 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:04<00:00, 2438.33it/s]
2026-09-22 18:55:22 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:04<00:00, 2457.89it/s]
2026-09-22 18:55:27 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:04<00:00, 2427.65it/s]
2026-09-22 18:55:31 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:04<00:00, 2511.81it/s]
2026-09-22 18:55:37 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:04<00:00, 2522.43it/s]
2026-09-22 18:55:42 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:04<00:00, 2511.85it/s]
2026-09-22 18:55:46 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:04<00:00, 2501.86it/s]
2026-09-22 18:55:52 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:04<00:00, 2417.16it/s]
2026-09-22 18:55:57 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:04<00:00, 2427.18it/s]
2026-09-22 18:56:02 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:04<00:00, 2407.46it/s]
2026-09-22 18:56:08 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:04<00:00, 2524.47it/s]
2026-09-22 18:56:12 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:04<00:00, 2549.24it/s]
2026-09-22 18:56:17 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:04<00:00, 2499.52it/s]
2026-09-22 18:56:23 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:04<00:00, 2424.05it/s]
2026-09-22 18:56:28 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:04<00:00, 2429.38it/s]
2026-09-22 18:56:34 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:04<00:00, 2384.07it/s]
2026-09-22 18:56:39 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:04<00:00, 2381.19it/s]
2026-09-22 18:56:45 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:04<00:00, 2449.07it/s]
2026-09-22 18:56:50 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:04<00:00, 2465.23it/s]
2026-09-22 18:56:56 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:04<00:00, 2411.99it/s]
2026-09-22 18:57:01 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:04<00:00, 2437.16it/s]
2026-09-22 18:57:07 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:21<00:00, 497.67it/s]
2026-09-22 18:57:29 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:04<00:00, 2567.03it/s]
2026-09-22 18:57:35 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:04<00:00, 2457.28it/s]
2026-09-22 18:57:39 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:04<00:00, 2454.25it/s]
2026-09-22 18:57:46 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:04<00:00, 2472.00it/s]
2026-09-22 18:57:52 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:04<00:00, 2396.61it/s]
2026-09-22 18:57:59 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:04<00:00, 2493.86it/s]

In [10]:
from stt_benchmarking.utils import deployment_protocol as dp
from stt_benchmarking.models.speech_to_text.arabic import ensemble
importlib.reload(dp)

dp = dp.DeploymentProtocol.from_hypotheses(
    model_samples={n: s for n, s in zip(model_names, all_models) if n in voters},
    voters=voters,
    ensemble_factory=ensemble.HybridEnsemble,
    main_kwargs={"substitute": False, "normalize_final_letters": True},
    n_boot=1000, seed=42, min_pool_size=3,
    outdir="deployment_out/cv_validated_voters_unweighted_ensemble", suffix="cv_validated_voters_unweighted_ensemble")

r = dp.run(weighting="uniform")

2026-09-22 21:33:20 - [stt_benchmarking.utils.decorators.execution_time_wrapper:21] INFO - Execution time for function cross_wer: 0 minutes 5 seconds (5.8s)
2026-09-22 21:33:20 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:21<00:00, 478.88it/s]
2026-09-22 21:33:42 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:22<00:00, 470.67it/s]
2026-09-22 21:34:05 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:37<00:00, 277.71it/s]
2026-09-22 21:34:44 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:34<00:00, 306.45it/s]
2026-09-22 21:35:20 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:22<00:00, 462.50it/s]
2026-09-22 21:35:43 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:22<00:00, 474.58it/s]
2026-09-22 21:36:06 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:22<00:00, 463.83it/s]
2026-09-22 21:36:29 - [stt_benchmarking.utils.decorators.execution_time_wrapper:21] INFO - Execution time for function ranking: 3 minutes 9 seconds (189.1s)
2026-09-22 21:36:29 - [stt_benchmarking.utils.decorators.execution_time_wrapper:21] INFO - Execution time for function ranking: 0 minutes 0 seconds (0.1s)
2026-09-22 21:36:29 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:05<00:00, 1981.04it/s]
2026-09-22 21:36:35 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:05<00:00, 1964.97it/s]
2026-09-22 21:36:40 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:04<00:00, 2326.68it/s]
2026-09-22 21:36:45 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:05<00:00, 1922.20it/s]
2026-09-22 21:36:51 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:14<00:00, 743.04it/s]
2026-09-22 21:37:06 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:04<00:00, 2417.27it/s]
2026-09-22 21:37:12 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:05<00:00, 1882.42it/s]
2026-09-22 21:37:18 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:04<00:00, 2370.35it/s]
2026-09-22 21:37:23 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:15<00:00, 680.13it/s]
2026-09-22 21:37:40 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:04<00:00, 2330.07it/s]
2026-09-22 21:37:45 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:04<00:00, 2400.63it/s]
2026-09-22 21:37:50 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:04<00:00, 2312.96it/s]
2026-09-22 21:37:56 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:14<00:00, 737.33it/s]
2026-09-22 21:38:12 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:06<00:00, 1697.71it/s]
2026-09-22 21:38:19 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:05<00:00, 1792.97it/s]
2026-09-22 21:38:25 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:08<00:00, 1293.34it/s]
2026-09-22 21:38:34 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:24<00:00, 420.20it/s]
2026-09-22 21:39:01 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:04<00:00, 2346.38it/s]
2026-09-22 21:39:06 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:04<00:00, 2339.28it/s]
2026-09-22 21:39:11 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:16<00:00, 624.53it/s]
2026-09-22 21:39:29 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:04<00:00, 2314.64it/s]
2026-09-22 21:39:34 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:04<00:00, 2151.95it/s]
2026-09-22 21:39:39 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:15<00:00, 699.26it/s]
2026-09-22 21:39:56 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:07<00:00, 1477.24it/s]
2026-09-22 21:40:04 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:04<00:00, 2365.01it/s]
2026-09-22 21:40:09 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:14<00:00, 725.39it/s]
2026-09-22 21:40:25 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:04<00:00, 2278.56it/s]
2026-09-22 21:40:30 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:07<00:00, 1407.06it/s]
2026-09-22 21:40:38 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:20<00:00, 509.01it/s]
2026-09-22 21:41:02 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:08<00:00, 1300.28it/s]
2026-09-22 21:41:11 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:06<00:00, 1557.56it/s]
2026-09-22 21:41:19 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:32<00:00, 322.85it/s]
2026-09-22 21:41:56 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:08<00:00, 1264.40it/s]
2026-09-22 21:42:05 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:07<00:00, 1360.33it/s]
2026-09-22 21:42:14 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:21<00:00, 489.77it/s]
2026-09-22 21:42:37 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:04<00:00, 2417.09it/s]
2026-09-22 21:42:42 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:17<00:00, 592.98it/s]
2026-09-22 21:43:02 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:04<00:00, 2224.78it/s]
2026-09-22 21:43:07 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:14<00:00, 736.71it/s]
2026-09-22 21:43:23 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:04<00:00, 2309.51it/s]
2026-09-22 21:43:28 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:14<00:00, 731.78it/s]
2026-09-22 21:43:44 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:04<00:00, 2377.41it/s]
2026-09-22 21:43:49 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:14<00:00, 730.54it/s]
2026-09-22 21:44:09 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:04<00:00, 2102.64it/s]
2026-09-22 21:44:15 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:26<00:00, 391.18it/s]
2026-09-22 21:44:46 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:08<00:00, 1277.88it/s]
2026-09-22 21:44:55 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:27<00:00, 385.62it/s]
2026-09-22 21:45:27 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:14<00:00, 722.24it/s]
2026-09-22 21:45:44 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:27<00:00, 383.83it/s]
2026-09-22 21:46:15 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:08<00:00, 1268.00it/s]
2026-09-22 21:46:25 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:27<00:00, 381.77it/s]
2026-09-22 21:46:56 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:07<00:00, 1476.28it/s]
2026-09-22 21:47:05 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:27<00:00, 384.19it/s]
2026-09-22 21:47:37 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:07<00:00, 1457.61it/s]
2026-09-22 21:47:46 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:36<00:00, 289.96it/s]
2026-09-22 21:48:26 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:27<00:00, 385.99it/s]
2026-09-22 21:48:58 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:27<00:00, 382.67it/s]
2026-09-22 21:49:30 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:27<00:00, 387.55it/s]
2026-09-22 21:50:02 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:27<00:00, 387.63it/s]
2026-09-22 21:50:34 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:26<00:00, 393.39it/s]
2026-09-22 21:51:05 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:27<00:00, 388.86it/s]
2026-09-22 21:51:37 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:37<00:00, 279.82it/s]
2026-09-22 21:52:19 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:27<00:00, 388.80it/s]
2026-09-22 21:52:51 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:27<00:00, 386.33it/s]
2026-09-22 21:53:23 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:27<00:00, 387.39it/s]
2026-09-22 21:53:55 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:27<00:00, 384.96it/s]
2026-09-22 21:54:27 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:26<00:00, 390.94it/s]
2026-09-22 21:54:58 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:26<00:00, 390.50it/s]
2026-09-22 21:55:30 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:26<00:00, 395.16it/s]
2026-09-22 21:56:01 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:26<00:00, 389.37it/s]
2026-09-22 21:56:31 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:17<00:00, 599.18it/s]
2026-09-22 21:56:49 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:17<00:00, 608.28it/s]
2026-09-22 21:57:07 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:31<00:00, 336.82it/s]
2026-09-22 21:57:40 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:33<00:00, 311.43it/s]
2026-09-22 21:58:16 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:33<00:00, 317.40it/s]
2026-09-22 21:58:51 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:33<00:00, 316.85it/s]
2026-09-22 21:59:26 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:33<00:00, 317.85it/s]
2026-09-22 22:00:01 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:32<00:00, 319.19it/s]
2026-09-22 22:00:35 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:45<00:00, 229.03it/s]
2026-09-22 22:01:23 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:33<00:00, 316.24it/s]
2026-09-22 22:01:58 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:33<00:00, 314.51it/s]
2026-09-22 22:02:34 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:32<00:00, 322.87it/s]
2026-09-22 22:03:08 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:32<00:00, 321.02it/s]
2026-09-22 22:03:43 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:31<00:00, 328.89it/s]
2026-09-22 22:04:16 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:25<00:00, 408.61it/s]
2026-09-22 22:04:43 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:18<00:00, 563.38it/s]

## Rover

In [9]:
importlib.reload(rover)

ROVEROBJECT = rover.ROVER()
ROVEROBJECT.combine_models_transcriptions(seamless_samples,
    whisper_v3_samples,
    nvidia_samples,
    w2vbert_samples,
    hubert_samples,
    wav2vec_sb_samples,
    cohere_samples)
ROVEROBJECT.main(substitute=False, normalize_final_letters=True)
ROVEROBJECT.eval(cv_audios)
rover_samples = ROVEROBJECT.fusion_results
ROVEROBJECT.overall_metrics

2026-09-07 10:55:19 - [stt_benchmarking.models.speech_to_text.arabic.main:406] INFO - Using substitute: False, Replace Final Char: True
ROVER Fusion...: 100%|██████████| 10500/10500 [00:21<00:00, 489.03it/s]

{'word_error_rate': {'wer (%)': 5.04,
  'word_similarity_ratio (%)': 97.48,
  'word_edit_distance': 2687,
  'substitutions': 2169,
  'deletions': 234,
  'insertions': 284,
  'hits': 50861,
  'ref_length': 53264,
  'hyp_length': 53314},
 'character_error_rate': {'cer (%)': 1.63,
  'char_similarity_ratio (%)': 99.19,
  'char_edit_distance': 4286,
  'substitutions': 1064,
  'deletions': 1585,
  'insertions': 1637,
  'hits': 260370,
  'ref_length': 263019,
  'hyp_length': 263071}}

In [11]:
ROVEROBJECT.fusion_wall_time

32.46507287025452

## Ensemble

In [9]:
importlib.reload(ensemble)

ENSEMBLE_OBJ = ensemble.HybridEnsemble()
ENSEMBLE_OBJ.combine_models_transcriptions(
    seamless_samples,
    whisper_v3_samples,
    nvidia_samples,
    w2vbert_samples,
    hubert_samples,
    wav2vec_sb_samples,
    cohere_samples
)
ENSEMBLE_OBJ.main(substitute=False, normalize_final_letters=True)
ENSEMBLE_OBJ.eval(cv_audios)
ensemble_samples = ENSEMBLE_OBJ.samples_info
ENSEMBLE_OBJ.overall_metrics

2026-09-07 10:57:27 - [stt_benchmarking.models.speech_to_text.arabic.main:912] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:54<00:00, 191.36it/s]

{'word_error_rate': {'wer (%)': 4.88,
  'word_similarity_ratio (%)': 97.56,
  'word_edit_distance': 2597,
  'substitutions': 2121,
  'deletions': 322,
  'insertions': 154,
  'hits': 50821,
  'ref_length': 53264,
  'hyp_length': 53096},
 'character_error_rate': {'cer (%)': 1.44,
  'char_similarity_ratio (%)': 99.28,
  'char_edit_distance': 3780,
  'substitutions': 1021,
  'deletions': 1841,
  'insertions': 918,
  'hits': 260157,
  'ref_length': 263019,
  'hyp_length': 262096}}

In [10]:
importlib.reload(ensemble)

ENSEMBLE_OBJ = ensemble.HybridEnsemble()
ENSEMBLE_OBJ.combine_models_transcriptions(
    seamless_samples,
    whisper_v3_samples,
    nvidia_samples,
    w2vbert_samples,
    hubert_samples,
    wav2vec_sb_samples,
    cohere_samples
)
ENSEMBLE_OBJ.main(substitute=False, normalize_final_letters=True)
ENSEMBLE_OBJ.eval(cv_audios)
ensemble_samples = ENSEMBLE_OBJ.samples_info
ENSEMBLE_OBJ.overall_metrics

2026-09-22 18:06:03 - [stt_benchmarking.models.speech_to_text.arabic.main:864] INFO - Using substitute: False, Replace Final Char: True
Fusing Inputs...: 100%|██████████| 10500/10500 [00:28<00:00, 372.86it/s]

{'word_error_rate': {'wer (%)': 4.88,
  'word_similarity_ratio (%)': 97.55,
  'word_edit_distance': 2601,
  'substitutions': 2121,
  'deletions': 322,
  'insertions': 158,
  'hits': 50821,
  'ref_length': 53264,
  'hyp_length': 53100},
 'character_error_rate': {'cer (%)': 1.44,
  'char_similarity_ratio (%)': 99.28,
  'char_edit_distance': 3778,
  'substitutions': 1022,
  'deletions': 1834,
  'insertions': 922,
  'hits': 260163,
  'ref_length': 263019,
  'hyp_length': 262107}}

In [10]:
ENSEMBLE_OBJ.fusion_wall_time

55.17088532447815

In [10]:
import json

def wer_of(samples, path):
    m = samples.get(path, {}).get("metrics")
    if not m: return None
    return m["word_error_rate"]["wer (%)"]

model_dicts = {
    "seamless_m4t": seamless_samples, "whisper_v3": whisper_v3_samples,
    "fastconformer": nvidia_samples, "w2vbert": w2vbert_samples,
    "hubert": hubert_samples, "wav2vec_sb": wav2vec_sb_samples,
    "cohere": cohere_samples,
}

rows = []
for path in ensemble_samples:
    ens_wer = wer_of(ensemble_samples, path)
    if ens_wer is None: continue
    sys_wers = {n: wer_of(d, path) for n, d in model_dicts.items()}
    sys_wers = {n: w for n, w in sys_wers.items() if w is not None}
    if not sys_wers: continue
    best_single = min(sys_wers.values())
    margin = best_single - ens_wer            # positive = ensemble beats all
    ref = ensemble_samples[path].get("normalized_transcription", "")
    n_words = len(ref.split())
    md = ensemble_samples[path]["metadata"]
    n_filtered = md["records_filtration"].get("num_filtered", 0)
    n_ties = sum(
        1 for vd in md["voting"]["voting_details"]
        if vd.get("token_votes") and
        sorted(vd["token_votes"].values())[-1] == (sorted(vd["token_votes"].values())[-2] if len(vd["token_votes"])>1 else -1)
    )
    rows.append({
        "path": path, "ens_wer": round(ens_wer,2), "best_single": round(best_single,2),
        "margin": round(margin,2), "n_words": n_words,
        "n_filtered": n_filtered, "n_ties": n_ties,
        "strategy": md["reference_selection"].get("strategy_metric"),
    })

# ensemble strictly beats every single system, short enough to typeset, exercises filter+tie
cand = [r for r in rows if r["margin"] > 0 and 5 <= r["n_words"] <= 12]
cand.sort(key=lambda r: (r["n_filtered"]>0, r["n_ties"]>0, r["margin"]), reverse=True)

for r in cand[:15]:
    print(r)

{'path': '../../data/mozilla_commonvoice/cv-corpus/ar/clips\\common_voice_ar_19486916.mp3', 'ens_wer': 0.0, 'best_single': 20.0, 'margin': 20.0, 'n_words': 5, 'n_filtered': 1, 'n_ties': 1, 'strategy': 'most_common_words'}
{'path': '../../data/mozilla_commonvoice/cv-corpus/ar/clips\\common_voice_ar_24030002.mp3', 'ens_wer': 0.0, 'best_single': 20.0, 'margin': 20.0, 'n_words': 5, 'n_filtered': 1, 'n_ties': 1, 'strategy': 'most_common_words'}
{'path': '../../data/mozilla_commonvoice/cv-corpus/ar/clips\\common_voice_ar_25193257.mp3', 'ens_wer': 0.0, 'best_single': 20.0, 'margin': 20.0, 'n_words': 5, 'n_filtered': 1, 'n_ties': 1, 'strategy': 'longest_match_validation'}
{'path': '../../data/mozilla_commonvoice/cv-corpus/ar/clips\\common_voice_ar_25202531.mp3', 'ens_wer': 20.0, 'best_single': 40.0, 'margin': 20.0, 'n_words': 5, 'n_filtered': 2, 'n_ties': 1, 'strategy': 'longest_match_validation'}
{'path': '../../data/mozilla_commonvoice/cv-corpus/ar/clips\\common_voice_ar_32382534.mp3', 'ens_wer': 0.0, 'best_single': 20.0, 'margin': 20.0, 'n_words': 5, 'n_filtered': 1, 'n_ties': 1, 'strategy': 'longest_match_validation'}
{'path': '../../data/mozilla_commonvoice/cv-corpus/ar/clips\\common_voice_ar_32520354.mp3', 'ens_wer': 0.0, 'best_single': 20.0, 'margin': 20.0, 'n_words': 5, 'n_filtered': 1, 'n_ties': 1, 'strategy': 'most_common_words'}
{'path': '../../data/mozilla_commonvoice/cv-corpus/ar/clips\\common_voice_ar_26081244.mp3', 'ens_wer': 11.11, 'best_single': 22.22, 'margin': 11.11, 'n_words': 9, 'n_filtered': 1, 'n_ties': 1, 'strategy': 'most_common_words'}
{'path': '../../data/mozilla_commonvoice/cv-corpus/ar/clips\\common_voice_ar_19205821.mp3', 'ens_wer': 10.0, 'best_single': 20.0, 'margin': 10.0, 'n_words': 10, 'n_filtered': 2, 'n_ties': 1, 'strategy': 'most_common_words'}
{'path': '../../data/mozilla_commonvoice/cv-corpus/ar/clips\\common_voice_ar_24362455.mp3', 'ens_wer': 9.09, 'best_single': 18.18, 'margin': 9.09, 'n_words': 11, 'n_filtered': 3, 'n_ties': 1, 'strategy': 'most_common_words'}
{'path': '../../data/mozilla_commonvoice/cv-corpus/ar/clips\\common_voice_ar_25986963.mp3', 'ens_wer': 8.33, 'best_single': 16.67, 'margin': 8.34, 'n_words': 12, 'n_filtered': 1, 'n_ties': 1, 'strategy': 'most_common_words'}
{'path': '../../data/mozilla_commonvoice/cv-corpus/ar/clips\\common_voice_ar_24599602.mp3', 'ens_wer': 0.0, 'best_single': 16.67, 'margin': 16.67, 'n_words': 6, 'n_filtered': 1, 'n_ties': 0, 'strategy': 'most_common_words'}
{'path': '../../data/mozilla_commonvoice/cv-corpus/ar/clips\\common_voice_ar_34916824.mp3', 'ens_wer': 0.0, 'best_single': 16.67, 'margin': 16.67, 'n_words': 6, 'n_filtered': 1, 'n_ties': 0, 'strategy': 'most_common_words'}
{'path': '../../data/mozilla_commonvoice/cv-corpus/ar/clips\\common_voice_ar_37146093.mp3', 'ens_wer': 33.33, 'best_single': 50.0, 'margin': 16.67, 'n_words': 6, 'n_filtered': 1, 'n_ties': 0, 'strategy': 'longest_match_validation'}
{'path': '../../data/mozilla_commonvoice/cv-corpus/ar/clips\\common_voice_ar_24028682.mp3', 'ens_wer': 0.0, 'best_single': 14.29, 'margin': 14.29, 'n_words': 7, 'n_filtered': 2, 'n_ties': 0, 'strategy': 'longest_match_validation'}
{'path': '../../data/mozilla_commonvoice/cv-corpus/ar/clips\\common_voice_ar_25195870.mp3', 'ens_wer': 0.0, 'best_single': 14.29, 'margin': 14.29, 'n_words': 7, 'n_filtered': 1, 'n_ties': 0, 'strategy': 'most_common_words'}

In [14]:
model_dicts={"seamless_m4t":seamless_samples,"whisper_v3":whisper_v3_samples,"fastconformer":nvidia_samples,"w2vbert":w2vbert_samples,"hubert":hubert_samples,"wav2vec_sb":wav2vec_sb_samples,"cohere":cohere_samples}
disp={"seamless_m4t":"SeamlessM4T v2","whisper_v3":"Whisper large-v3","fastconformer":"FastConformer-Hybrid","w2vbert":"w2v-BERT 2.0","hubert":"HuBERT","wav2vec_sb":"SpeechBrain wav2vec2","cohere":"Cohere Transcribe Arabic"}
AUDIO_ID="../../data/mozilla_commonvoice/cv-corpus/ar/clips\\common_voice_ar_24362455.mp3"

In [15]:
from stt_benchmarking.utils import ensemble_analysis
importlib.reload(ensemble_analysis)

fp=ensemble_analysis.download_amiri("fonts")     # OFL, one-time; returns Amiri-Regular.ttf
ensemble_analysis.render_stages(AUDIO_ID,ensemble_samples,model_dicts,voters,disp,ensemble_name="Proposed ensemble",fig_dir="figures_commonvoice",font_path=fp,max_tokens=14,col_chunk=12)

font: fonts\Amiri-Regular.ttf

TSIV NOT subset; don't know how to subset; dropped

saved: figures_commonvoice\stage0_reference.pdf | figures_commonvoice\stage0_reference.png

TSIV NOT subset; don't know how to subset; dropped
TSIV NOT subset; don't know how to subset; dropped

saved: figures_commonvoice\stage1_filtration.pdf | figures_commonvoice\stage1_filtration.png
saved: figures_commonvoice\stage2_reference_selection.pdf | figures_commonvoice\stage2_reference_selection.png

TSIV NOT subset; don't know how to subset; dropped

saved: figures_commonvoice\stage3_alignment.pdf | figures_commonvoice\stage3_alignment.png

TSIV NOT subset; don't know how to subset; dropped

saved: figures_commonvoice\stage4_voting.pdf | figures_commonvoice\stage4_voting.png

TSIV NOT subset; don't know how to subset; dropped

saved: figures_commonvoice\stage5_comparison.pdf | figures_commonvoice\stage5_comparison.png

['figures_commonvoice\\stage0_reference.pdf',
 'figures_commonvoice\\stage0_reference.png',
 'figures_commonvoice\\stage1_filtration.pdf',
 'figures_commonvoice\\stage1_filtration.png',
 'figures_commonvoice\\stage2_reference_selection.pdf',
 'figures_commonvoice\\stage2_reference_selection.png',
 'figures_commonvoice\\stage3_alignment.pdf',
 'figures_commonvoice\\stage3_alignment.png',
 'figures_commonvoice\\stage4_voting.pdf',
 'figures_commonvoice\\stage4_voting.png',
 'figures_commonvoice\\stage5_comparison.pdf',
 'figures_commonvoice\\stage5_comparison.png']

In [11]:
all_models.append(rover_samples)
model_names.append("rover")

all_models.append(ensemble_samples)
model_names.append("ensemble")

In [12]:
models_with_names = list(zip(model_names, all_models))
df_full = collect_model_metrics(models_with_names)
df_filtered_full = filter_audio_records(df_full)

Audios dropped (empty ground truth): 0
Audios dropped (empty ensemble): 5
Audios: 10500 -> 10495

In [13]:
df_full_eval = evaluate_absolute_metrics(df_filtered_full)
df_full_eval[["model", "WER (%)", "CER (%)", "rtf_mean", "inference_time_total_h", "fusion_time_mean"]]

,model,WER (%),CER (%),rtf_mean,inference_time_total_h,fusion_time_mean
0,ensemble,4.81,1.37,NaN,0.125067,0.042901
1,rover,4.98,1.56,NaN,0.052627,0.018052
2,cohere,5.56,1.50,0.045209,0.556292,NaN
3,fastconformer,7.19,2.16,0.016741,0.196160,NaN
4,hubert,7.81,2.13,0.009844,0.117725,NaN
5,seamless_m4t,10.77,3.49,0.089647,1.085669,NaN
6,whisper_v3,14.71,4.64,0.160151,1.921033,NaN
7,whisper_v2,18.42,6.01,0.165181,2.003316,NaN
8,xlsr,22.82,6.43,0.007376,0.087706,NaN
9,w2vbert,23.98,6.58,0.008883,0.106979,NaN
10,wav2vec_sb,29.12,9.66,0.006173,0.073634,NaN

In [ ]:
df_full_eval = evaluate_absolute_metrics(df_filtered_full)
df_full_eval[["model", "WER (%)", "CER (%)", "rtf_mean", "inference_time_total_h", "fusion_time_mean"]]

            model  WER (%)  CER (%)
0        ensemble     4.81     1.37
1           rover     4.98     1.56
2          cohere     5.56     1.50
3   fastconformer     7.19     2.16
4          hubert     7.81     2.13
5    seamless_m4t    10.77     3.49
6      whisper_v3    14.71     4.64
7      whisper_v2    18.42     6.01
8            xlsr    22.82     6.43
9         w2vbert    23.98     6.58
10     wav2vec_sb    29.12     9.66

In [14]:
df_relative_ensemble = evaluate_relative_metrics(df_filtered_full, "ensemble", exclude_models=["rover", "hybrid_ensemble"])
df_relative_ensemble[["model", "WER (%)", "CER (%)"]]

           model  WER (%)  CER (%)
0       ensemble     0.00     0.00
1         cohere     3.68     1.09
2  fastconformer     5.29     1.65
3         hubert     7.52     2.05
4   seamless_m4t     8.37     2.95
5     whisper_v3    11.97     3.92
6     whisper_v2    16.41     5.49
7           xlsr    21.32     5.96
8        w2vbert    21.90     6.05
9     wav2vec_sb    27.44     9.14

# END

In [17]:
df_relative_rover = evaluate_relative_metrics(df_filtered_full, "rover", exclude_models=["ensemble", "hybrid_ensemble"])
df_relative_rover.to_csv("../../reports/phase_1_4/metrics/relative/ultimate_last/rover_relative_metrics.csv", index=False)
df_relative_ensemble = evaluate_relative_metrics(df_filtered_full, "ensemble", exclude_models=["rover", "hybrid_ensemble"])
df_relative_ensemble.to_csv("../../reports/phase_1_4/metrics/relative/ultimate_last/ensemble_relative_metrics.csv", index=False)

In [ ]:
# ---- Option B: headline ranking correlation (reference order vs pseudo-reference order) ----
merged_B, coeffs_B = ranking_correlation(df_full_eval, df_relative_ensemble)
print("=== Option B: pooled system-ranking correlation (ensemble as pseudo-reference) ===")
print(merged_B.to_string(index=False))
print(coeffs_B)

# ---- Option A: per-sample pseudo-WER tracking (NoRefER analogue) ----
df_ps = add_pseudo_reference_wer(df_filtered_full, ensemble_samples)
corr_A = per_sample_correlation(df_ps)
corr_A.to_csv("../../reports/phase_1_4/metrics/relative/ultimate_last/per_sample_correlation_cohere.csv", index=False)
print("\n=== Option A: per-sample WER tracking (per-model + pooled) ===")
print(corr_A.to_string(index=False))

=== Option B: pooled system-ranking correlation (ensemble as pseudo-reference) ===
        model  wer_abs  wer_rel
       cohere     5.56     3.83
fastconformer     7.19     5.50
       hubert     7.81     7.71
 seamless_m4t    10.77     8.47
   whisper_v3    14.71    11.88
         xlsr    22.82    20.61
      w2vbert    23.98    21.78
   wav2vec_sb    29.12    27.22
{'pearson': 0.9963394902954462, 'pearson_p': 1.222845606765019e-07, 'spearman': 1.0, 'spearman_p': 0.0, 'kendall': 0.9999999999999998, 'kendall_p': 4.96031746031746e-05}

=== Option A: per-sample WER tracking (per-model + pooled) ===
        model     n  pearson  pearson_p  spearman  spearman_p  kendall  kendall_p
   wav2vec_sb 10496 0.945278        0.0  0.948045         0.0 0.907969        0.0
      w2vbert 10496 0.936345        0.0  0.919205         0.0 0.874470        0.0
         xlsr 10496 0.922583        0.0  0.914378         0.0 0.871513        0.0
   whisper_v3 10496 0.907703        0.0  0.860109         0.0 0.819068        0.0
 ALL (pooled) 83968 0.883574        0.0  0.858810         0.0 0.819176        0.0
 seamless_m4t 10496 0.887317        0.0  0.787358         0.0 0.751551        0.0
       hubert 10496 0.735356        0.0  0.711877         0.0 0.680524        0.0
fastconformer 10496 0.726318        0.0  0.698120         0.0 0.666942        0.0
       cohere 10496 0.645284        0.0  0.565675         0.0 0.541215        0.0